### ISSUE TITLE
Describe general constraints for Hush-Hush medal solutions

### ISSUE THREAD

**Issue by minusQuantumNeko** [ppy/osu-wiki#10294]
In my opinion it would be nice to describe what wouldn't work for Hush-Hush medals in [Medal unlock requirements](https://osu.ppy.sh/wiki/en/Medals/Unlock_requirements) just like what was done for [Hush-Hush (Expert)](https://osu.ppy.sh/wiki/en/Medals#hush-hush), so people don't waste their time on what will not work. 

I suggest to add 2 things:
- That map-specific (meaning they can only be obtained on specific map(s)) Hushes cannot be non-FA (song(s) not from Featured Artist(s));
- That if medal does not show up in specific gamemode profile - you cannot obtain it in said gamemode;

Both of these are publicly known and confirmed, so there should be no harm in adding it to wiki 👀

**Comment by chromb** [comment]
Personally don't really get the point in adding this, the first point has exceptions from early medals, and the latter is pretty self-explanatory.

**Comment by minusQuantumNeko** [comment]
> Personally don't really get the point in adding this, the first point has exceptions from early medals, and the latter is pretty self-explanatory.

Yes, as you said there were **early** medals that were an exception, but these also were licensed later. Also with how many Featured Artists osu! has now I don't see that exception happening again.
As for 2nd point, we've already seen people trying to get medals in gamemodes that don't show them in gamemode profile, so turns out it's not very self-explanatory.

**Comment by cl8n** [comment]
more info doesn't hurt but try to take care for how it's introduced and what context is appropriate for the article. for example, the first point is not inherently part of how medals work, it's just recent convention and should be explained as such

the other note about how "expert" medals work should probably also be copied to the unlock conditions article.

---

completely unrelated but the tone of "for obvious reasons" in that linked article should really not be present on the wiki lol

**Comment by cl8n** [comment]
@minusQuantumNeko still interested in trying this one?

**Comment by minusQuantumNeko** [comment]
> @minusQuantumNeko still interested in trying this one?

Yes, I am, just need to think of a good wording for it
