### ISSUE TITLE
Hold note ticks section in osu!mania gameplay differences in lazer is outdated

### ISSUE THREAD

**Issue by Bruno5430** [ppy/osu-wiki#10381]
Since https://github.com/ppy/osu/pull/25062 hold note ticks no longer exist in lazer, and is more in-line with stable

https://osu.ppy.sh/wiki/en/Client/Release_stream/Lazer/Gameplay_differences_in_osu!(lazer)#hold-note-ticks-give-score-and-are-responsible-for-combo-breaks

**Comment by cl8n** [comment]
fixed in #10922
