### ISSUE TITLE
Sitemap Auto-updater

### ISSUE THREAD

**Issue by sr229** [ppy/osu-wiki#1042]
Recently in  #1041 a needed auto-updater was needed for Sitemap, and I came up with a solution.

[Project URL](https://github.com/sr229/Cartographer)

### Initial Program flow

![image](https://user-images.githubusercontent.com/14976516/36153872-a8bc372c-110a-11e8-8c5c-0bae9cf53e58.png)

**Comment by sr229** [comment]
However, a much more plausible solution is raising this to osu-web devs

**Comment by sr229** [comment]
Implemented via [Cartographer Project](https://github.com/sr229/Cartographer)

**Comment by Joehuu** [comment]
Same issue already made in osu-web. Closing.
