### ISSUE TITLE
The new osu!Lazer update falsely flags me as a touchscreen player and makes me have other problems (besides lower pp)

### ISSUE THREAD

**Issue by kuka012** [ppy/osu-wiki#10461]
I am posting here because it was too long to post it on the recommended site (https://osu.ppy.sh/community/forums/5)

Problem details: In the new update 2023.1114.1-lazer you implemented a touchscreen mod popup and adjusted the star rating for these users.

Now here are my problems: I have been using my samsung galaxy s6 lite (since this July) connected to my pc via spacedesk and have always been using the S pen to play. Also spacedesk has an inbuilt "enable touchscreen control" which I turned off and stayed off from the very beggining of my time playing (there is also an "enable stylus screen control" which is obviously turned on so i can play with the S pen). I was never sure whether it detected me as playing with a touch screen or not but because I turned off the setting I figured it probably didn't. But apperantly I count as a touchscreen user now.

Even though I believe I shouldn't be flagged, I can live with earning less pp than normal. The problem I am facing now is the following: Even though the "disable cliclks during gameplay" is turned off, my stylus still registers clicks during gameplay. This also means that while my stylus is on the screen it holds down button 1 until I press "c" (my b1 on keyboard). Which leads me to having to press "c" even before the music starts so I can hit the 1st note. Not to mention that I can baisically never pull my pen away from the screen mid game because it will mess me up. I hope there will be a fix for this.

Another thing, I would love to have a star rating adjustment toggle setting because it is very frustrating to see those numbers go down while I grinded so much on getting better.

**Comment by Joehuu** [comment]
Already reported osu!-side: https://github.com/ppy/osu/issues/25446
