### ISSUE TITLE
Wiki license is not a Free Cultural license

### ISSUE THREAD

**Issue by soopax** [ppy/osu-wiki#10471]
The wiki's current license CC BY-NC isn't a Free Cultural license. Content on the wiki should be free to use for any purpose - even commercially.

Unfortunately and as far as I know, changing the license for existing articles would require obtaining permission to do so from every current and past contributor of the wiki, which is impossible. Therefore I propose this:

1. Set the license for **new articles** to CC BY-SA, which is a free license, and
2. Include a license notice with each wiki page, indicating whether that page is licensed under CC BY-NC or CC BY-SA.

The license notice of each page would be visible for wiki readers at the bottom of the page, similar to Wikipedia. The new license should slowly gain a foothold as new articles are written with the new license.

**Comment by cl8n** [comment]
how would this be an improvement? you don't explain your position in this issue

**Comment by peppy** [comment]
I don't see any benefit to be gained here. You can use the wiki as a reference for your article, but if you are selling or advertising on your article, you should definitely not be directly copying content from the wiki.
