### ISSUE TITLE
New skinnables should be added to wiki

### ISSUE THREAD

**Issue by tomm13** [ppy/osu-wiki#10732]
These should be added to the wiki, as they are otherwise challenging to find:
 `spinnerbonus-max.wav`
`slidertickmiss@2x.png` 
`sliderendmiss@2x.png`

**Comment by cl8n** [comment]
this may not really be related but just putting some other skin elements here I don't see on the wiki anywhere

`nightcore-clap.wav`
`nightcore-finish.wav`
`nightcore-hat.wav`
`nightcore-kick.wav`
`scoreboard-explosion@2x.png`
`star3@2x.png`
`taiko-barline@2x.png`
