### ISSUE TITLE
No crowns on "Best of series"

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1101]
Saw the crown icons on top of code. Also when on web, pressing those numbers will go to the icon. I'll do it if it was intended.
![](https://puu.sh/zAqVv/c051d5815a.png)
![](https://puu.sh/zAqVa/d7eb8287f3.png) ![](https://puu.sh/zAqUI/33ed04a0fd.png)

**Comment by MegaApplePi** [comment]
oh huh, I think that was a typo that went uncaught, those crowns should be images
