### ISSUE TITLE
Scorebar-colour info duplicated under count-1

### ISSUE THREAD

**Issue by Bauke** [ppy/osu-wiki#1113]
As seen in the picture the scorebar-colour information is duplicated under count1:

<img src="https://user-images.githubusercontent.com/19501722/37049919-c21090c4-2172-11e8-81f8-ca24eb36952c.png" width="500px">

Scorebar-colour information in the right place:

<img src="https://user-images.githubusercontent.com/19501722/37050094-3dacf8f8-2173-11e8-928c-4c78639286d3.png" width="500px">

**Comment by MegaApplePi** [comment]
sorry for the sloppiness, but this is being reworked on one of my branches right now
