### ISSUE TITLE
"Contest" ranking system should be the same on "best of/community choice" pages

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1115]
Edit: This might help- https://en.wikipedia.org/wiki/Ranking
Also on:
ppy/osu-web#2637 (for contest page)
On the wiki, the pages will change from all beatmaps to only top 50 from #1105, but wondering if the ranks should be the same, In the contests, it only shows that one beatmap and not the other on the spreadsheet. On the wiki, I put that other beatmap b/c it was upper. A whole new problem is when there are multiple beatmaps with the same pts(votes) on the same listing.
![](https://puu.sh/zC9wl/25016e7cd9.png)
![](https://puu.sh/zC9xQ/4f360e94e4.png)
![](https://puu.sh/zC9BG/ff4c342101.png)

Edit: This is dense ranking, after some research.
~Plan to have white space. Now 2009 should have 28 placings. Here there are 2 beatmaps with the same vote.~ Pick a ranking system.
Placing | Votes
![](https://puu.sh/zC9UH/902b7e9536.png) ![](https://puu.sh/zC9UX/4f14ae1caf.png)
~Edit: This, duplicate numbers and crowns, or multiple beatmaps on the same row.~ Idk pick a ranking system.
~Edit: I don't know how placing actually works.~ I did research.

**Comment by MegaApplePi** [comment]
Is this still relevant? The tables for the Best Of were deleted when the page was moved to Contests in #2482

**Comment by Joehuu** [comment]
Nope.
