### ISSUE TITLE
Add tenure badges for tournament committee 

### ISSUE THREAD

**Issue by hburn7** [ppy/osu-wiki#11202]
Pages such as [People / Global Moderation Team](https://osu.ppy.sh/wiki/en/People/Global_Moderation_Team) have tenure badges on display. The [People / Tournament Committee](https://osu.ppy.sh/wiki/en/People/Tournament_Committee) page should be updated to include the new tenure badges. (Same applies to the contest committee if they have tenure badges).

**Comment by Albionthegreat** [comment]
Contest committee does not have separate tenure badges. They will receive the same tenure badges as the Tournament Committee.
