### ISSUE TITLE
skin.ini page still labels the Name and Author commands as unused

### ISSUE THREAD

**Issue by nagi-desuuu** [ppy/osu-wiki#11234]
The Name and Author entries are still labelled as Unused as it does nothing in stable, yet these values are used in lazer.

**Comment by CloneWith** [comment]
osu!wiki is targeted at the stable version now, so there wouldn't be much content about osu!lazer and its technical details.

You can see #7139 for extra information. Anyway it's foreseeable that they will be added, and we just need to wait.

**Comment by RockRoller01** [comment]
at least one of these values actually is used in stable, IIRC when you export a skin it does not use the folder name but rather the name from the skin.ini
