### ISSUE TITLE
Simplified Chinese 简体中文

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-wiki#114]
https://github.com/ppy/osu-web/pull/932#discussion_r99564733

What should I do to solve this problem?
rename ALL 'zh.md' -> 'zh-CN.md'?
or I use 'zh' on osu-web?

怎样解决这个问题
是我用PR把osu-wiki的所有"zh.md"改成"zh-CN.md"
还是我在osu-web上使用"zh"

**Comment by sr229** [comment]
Keep in mind we use the [ISO 639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) for language coding.

**Comment by johnmave126** [comment]
the ISO 639-1 codes is designed to classify spoken language. In other words, the language is distinguished by its oral characteristics and underlying region. Whereas I believe osu-wiki should classify languages by its writing system. As a result I suggest using [ISO 15924](https://en.wikipedia.org/wiki/ISO_15924) instead. For example, both Hong Kong and Guangdong Province in China speak Cantonese ([yue in ISO 639-3](http://www-01.sil.org/iso639-3/documentation.asp?id=yue), a dialect under Chinese). But they use difference writing/script system. Guangdong Province, as a part of mainland China, uses Simplified Chinese (hans in ISO 15924) whereas Hong Kong uses Traditional Chinese (hant in ISO 15924). The same story happens between mainland China and Taiwan.

**Comment by kj415j45** [comment]
I decide to use 'zh' ,thanks a lot
