### ISSUE TITLE
Add separate pages for help centre how-to's

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1145]
The main page will only have Q&A while the separate pages show how to do it.

**Comment by TicClick** [comment]
the split doesn't happen; filling in the blanks from `#osu-wiki`, [2020-08-31(https://discord.com/channels/188630481301012481/218677502141399041/750019737576144996):

> **[5:50 PM] MilkyIQ**: `@Ephemeral` If you're not too busy, do you think you could give word on whether we should split up/reorganize the help centre articles? The pr I have opened has been sitting in silence for a while and I'm considering closing it
> **[6:11 PM] Ephemeral**: i don't think we should split them up, though the other wording changes you made seem okay, are you able to pull those out into another PR?
> **[6:23 PM] Zeus-**: Keeping all the sections cluttered in one article is really tiring for someone requiring actual help. While it looks quite demotivating and even harder to read due to the small size of headings, I'm pretty sure not everyone knows about that good old ctrl+f function while looking for something. Personally, leaving all of them intact as one large sized article would just make everything harder for everyone, while there's an easier option to sort everything out at hand.
> **[6:42 PM] Ephemeral**: i really don't think that's the case, it takes more effort to try and figure out what category your problem falls under to open the correct article for it than it does to ctrl-f a keyword

[2020-10-23](https://discord.com/channels/188630481301012481/218677502141399041/769260549044568134)
> ...
> [8:06 PM] MilkyIQ: But in this case, I'd say go for it. The articles I'm currently working on are advancing at a snail's pace, so the help centre (which is on my backlog) is gonna take a while to actually get finished

@MilkyIQ as you have removed the branch with changes, you won't be making any changes to the article, right?

**Comment by MilkyIQ** [comment]
> @MilkyIQ as you have removed the branch with changes, you won't be making any changes to the article, right?

@TicClick I don't plan to make any changes at this time, no. I do plan on eventually fixing up some typos, outdated info, confusing language, etc. over the summer, but that'll be a while and it won't be splitting any articles up.

**Comment by TicClick** [comment]
that is still manageable if [enough keywords for every section are added](https://discord.com/channels/188630481301012481/218677502141399041/801505281905131590) (yay), reopening
