### ISSUE TITLE
Conversion and Fun mods Wiki

### ISSUE THREAD

**Issue by Anax2i** [ppy/osu-wiki#11904]
Is there any wiki talking about all the conversion and fun mods in detail? It seems like I cannot find anything atm.

Original thread: https://osu.ppy.sh/community/forums/topics/1957698

(clayton edit) first PR with a few mods to figure out best practices: #12105

**Comment by The-Last-Cookie** [comment]
I'm pretty sure you're talking about the mods from osu! lazer, aren't you?

The wiki page `Game modifiers` only includes mods from osu! stable for now.

As far as I can tell, no one has worked on lazer mods and new mod features like adjustable speed modifiers yet.

Related to #7139 and #9920.

**Comment by cl8n** [comment]
#12105
most are stubs for now but don't really need an issue to track stubs
