### ISSUE TITLE
Conflicting information about tournament bans

### ISSUE THREAD

**Issue by Awesome-Aasim** [ppy/osu-wiki#11989]
The page [Tournament bans](/ppy/osu-wiki/tree/master/wiki/Help_centre/Tournament_bans/en.md) states that tournament bans are appealable, but the page [Account restrictions](/ppy/osu-wiki/tree/master/wiki/Help_centre/Account_restrictions/en.md) states that tournament bans cannot be appealed. This discrepancy should be cleared up, it should specify when a tournament ban may be reconsidered for appeal and when it cannot on both pages.

**Comment by Albionthegreat** [comment]
The page on tournament bans was most recently updated when permanent tournament bans were renamed to indefinite. See https://osu.ppy.sh/community/forums/topics/1798871 for more on this.

Perhaps these changes did not propagate to the Account restrictions page back then.

In any case, temporary tournament bans are **not** appealable. Indefinite ones are, after a period of at least 2 years has passed.

**Comment by Awesome-Aasim** [comment]
Okay, then can the restrictions page be updated?
