### ISSUE TITLE
Mascots listing doesn't include Mocha and has broken links

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-wiki#1202]
https://osu.ppy.sh/help/wiki/Mascots/Gallery
https://osu.ppy.sh/help/wiki/Mascots/

This does need to be addressed at some point, perhaps populated with some relevant winning pieces from fan art contests?

**Comment by MegaApplePi** [comment]
I will work on this. We will also include the community mascots in the listing for history.
![image](https://user-images.githubusercontent.com/14264992/38271140-360519a8-374b-11e8-933a-422b650051d7.png)
