### ISSUE TITLE
Error in word on the page

### ISSUE THREAD

**Issue by Dan1meR4ik-12** [ppy/osu-wiki#12047]
In the russian version of the "Perfomance Points" page is a spelling error:

(FAQ -> Как набрать PP?)
![изображение](https://github.com/user-attachments/assets/a531aded-ed36-40cc-af2b-cace1715cda4)

Here "рекодры" should be "рекорды" or am i wrong?
https://osu.ppy.sh/wiki/ru/Performance_points

**Comment by cl8n** [comment]
@TicClick

**Comment by Y2nn1c** [comment]
Asked a friend of mine who speaks russian and he agrees. I think you just make a PR cus a russian speaker will have to look over it in that case anyways
