### ISSUE TITLE
Change YouTube downloader tools to working ones

### ISSUE THREAD

**Issue by Userlog2** [ppy/osu-wiki#12133]
ytmp3.cc doesn't work (when I click it, it hangs).
https://youtube-dl.org doesn't work either - it was taken down for legal reasons (something about copyright, based on the [ruling](https://openjur.de/u/2466945.html))
EDIT: While https://ytdl-org.github.io/youtube-dl/ still works, none of the executable downloads work.

New tools need to be added to replace ytmp3.cc. Make sure these are safe to use (virus-free).

**Comment by 0x84f** [comment]
Is it worth even mentioning stuff like that on the official osu! wiki?

All of these tools die out eventually as well so keeping up is a sisyphean task

**Comment by The-Last-Cookie** [comment]
For what it's worth, I think this refers to [Guides/Videos from YouTube](https://osu.ppy.sh/wiki/en/Guides/Videos_from_YouTube).

**Comment by Hiviexd** [comment]
I'd be up for removing the article entirely. I don't think we should be promoting ToS violations of 3rd party services.
