### ISSUE TITLE
<Lazer>We need complete Chinese language translation 

### ISSUE THREAD

**Issue by MoliTecarlly** [ppy/osu-wiki#12268]
plz!
We need **complete** Chinese language translation for osu lazer(I can't wait for it)
the untranslated list:

1. the playing mods list
2. Map filter options(Does not affect the actual experience)
3. Grade Filter options(Does not affect the actual experience)
4. Setting Shortcut keys(Does not affect the actual experience)

thanks for more addition,all above is done by web translator because i am an chinese speaker and isn't good at en

**Comment by SamHou0** [comment]
我认为你应该把这个 issue 发送到[这里](https://github.com/ppy/osu/issues).
这是 osu!wiki 的存储库。此处进行的是 [https://osu.ppy.sh/wiki/](https://osu.ppy.sh/wiki/) 的翻译。

> We need complete Chinese language translation for osu lazer(I can't wait for it)

我不认为这是翻译问题。在 osu!lazer 中，无论选择除了英语的何种语言，它们都以英语显示。所以翻译者很可能并不能作出它们的翻译。（实际上，在对于 osu! 本身的翻译网页中，似乎并没有这一项，lazer 的翻译进度显示为100%）

---

I think you should post the issue [here](https://github.com/ppy/osu/issues).
This is the osu!wiki repository. It's for [https://osu.ppy.sh/wiki/](https://osu.ppy.sh/wiki/).

> We need complete Chinese language translation for osu lazer(I can't wait for it)

However, I don't think it's a translation problem. In osu!lazer, these are displayed in English when you choose every language other than English itself. So they cannot not be translated by translators. (In [crowdin](https://crowdin.com/project/osu-web), Chinese Simplified shows 100% progress)

**Comment by cl8n** [comment]
closing since the above is correct from what I can tell. @peppy im not sure if this is supposed to be tracked somewhere but i didnt find anything in lazer issues or discussions
