### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by Naville** [ppy/osu-wiki#128]
As in https://github.com/ppy/osu-wiki/blob/8d14e350faed166a3c0a436a9c7cfce0f6454cea/wiki/osu!_File_Formats/Osu_(file_format)/en.md

Which says the second last value of a timing point is "inherited"
But the first example below ,which claims to be a non-inherited tp has "1" as the second last value,
While the second example, which claims to be an inherited tp, has "0" as the second last value

**Comment by RaikireHiuduo** [comment]
Read #97 changes and post a review/comment there?

**Comment by sr229** [comment]
might as well make a PR to fix those Typos you found @Naville 
😉

**Comment by RaikireHiuduo** [comment]
From Deimos in Discord dev chat, `#general-dev`

```
1 = uninherited (red)
0 = inherited (green)
```

**Comment by sr229** [comment]
Requesting closure for this issue since it's obsolete.
