### ISSUE TITLE
Indonesian Wiki Completion

### ISSUE THREAD

**Issue by mfaishalakbar** [ppy/osu-wiki#13]
# Wiki Completion
### Getting Started
- [x] Registration
- [x] Installation
- [x] Newbie's Guide
- [x] Game's Interface
- [ ] Options
- [x] Hit Objects
- [x] Rules
- [x] Rules (simplified)
- [ ] Glossary
- [x] Shortcut Key Reference
- [x] osu! Program Files
- [x] osu! File Formats
- [x] BBCode
- [x] List of Guides
- [x] Help Center
### osu! Game Styles
- [ ] Basic explantation
- [x] Multi-play
- [x] Standard
- [x] Taiko
- [ ] Mania
- [x] Catch the Beat
- [x] osu!stream
- [x] osu!droid
- [ ] opsu!
- [ ] osu!wp
- [ ] T-Aiko
- [ ] Beats
- [ ] osu!MapDownloader
### Beatmap Editor
- [ ] Beatmap Editor
- [ ] Compose
- [ ] Design
- [ ] Timing
- [ ] Song Setup
- [ ] Storyboard Scripting
- [ ] Beatmapping
- [x] Beat Snap Divisor
- [x] Distance Snap
- [ ] Custom Sample Overrides
- [ ] Kiai Time
- [ ] Mapping Techniques
- [ ] Skinning
- [ ] Skin.ini
- [ ] Storyboarding
- [ ] Difficulty appropriate gameplay elements
### Online Editing and Ranking
- [ ] Beatmap Forum
- [x] Submission
- [x] Beatmap Approval
- [x] How to Get Your Map Ranked
- [x] Modding
- [x] Getting Your Map Modded
- [x] Kudosu
- [x] Star Priority
- [ ] Music Theory
- [ ] Audio Editing
- [ ] Ranking Criteria
- [x] Ranking Criteria: Standard
- [x] Ranking Criteria: Catch The Beat
- [x] Ranking Criteria: Taiko
- [ ] Ranking Criteria: Mania
  ### World of osu!
- [ ] Announcements Archive
- [x] Beatmaps
- [x] Game Modifiers
- [ ] Achievements
- [x] Performance Points
- [x] Play Styles
- [x] Score
- [x] Accuracy
- [x] Chat Console
- [x] BanchoBot
- [x] Mascots
- [ ] Livestreaming osu!
- [ ] osu!tourney
- [x] Internet Relay Chat
- [x] Tournaments
- [x] Showcases
- [ ] Contests
- [x] osu!academy
- [x] osu!talk
- [x] osu!supporter
- [ ] osu!store
### People
- [x] The Team
- [x] Administrators/Global Moderation Team
- [x] Quality Assurance Team
- [x] Beatmap Nomination Group
- [x] Language Moderators
- [x] osu! Alumni
- [x] Support Team
- [x] Community Contributors
### Guides
- [ ] How to Run osu! on Your Mac without using Boot Camp
- [x] GL Support Issues
- [ ] How to not Embarrass Yourself in the Modding Queues Subforum
- [ ] How to not Embarrass Yourself in the Projects Subforum
- [ ] Changing Title Text
- [ ] Starting a Beatmap Project
- [ ] Setting the Offset on the Correct Beat
- [ ] Collab Information
- [ ] Changing the Map's Artist or Title
- [ ] Making nice recording for Youtube
- [ ] Videos from YouTube
- [ ] Compressing Videos
- [ ] Getting songs from Video Games
- [ ] Basic MP3 modifications
- [ ] Reducing SB Load
- [ ] SGL Tool
- [ ] Adding custom hitsounds
- [ ] Custom Hitsound Library
- [ ] Making Properly Centered Spinners
- [ ] Cropping with Simple Backgrounds
- [ ] Cropping with Complex Backgrounds
- [ ] How to do 15° Patterns
- [ ] Making Good Sliders
- [ ] AIBat
- [ ] Fitting the Size-limit
- [ ] Mapping Taiko Difficulties
- [ ] How to time songs?
- [x] How do beatmaps get ranked?
- [x] Handling Cheating/Foul Play
- [ ] Tips and Tricks for osu!
### Skinning
- [ ] Tutorial:
- [ ] Tutorial: Interface
- [ ] Tutorial: Sounds
- [ ] Tutorial: Standard
- [ ] Tutorial: Catch the Beat
- [ ] Tutorial: Taiko
- [ ] Tutorial: Mania
- [ ] Elements: Interface
- [ ] Elements: Sounds
- [ ] Elements: Standard
- [ ] Elements: Catch the Beat
- [ ] Elements: Taiko
- [ ] Elements: Mania
### Storyboard Scripting
- [ ] Cheat Sheet
- [ ] General Rules
- [ ] Storyboard Objects
- [ ] Commands
- [ ] Compound Commands
- [ ] Miscellaneous
- [ ] Command Shorthand
- [ ] Storyboard Audio
- [ ] Storyboard Variables
- [ ] osu File Toggles
### Mapping Techniques
- [ ] Formations
- [ ] Rhythm Techniques
- [ ] Jumping Techniques
- [ ] Unrankable Techniques
- [ ] Hit Circle Techniques
- [ ] Slider Techniques
- [ ] Spinner Techniques
- [ ] Mapping Techniques/Basics
### World Cups
- [x] OWC 2010
- [x] OWC 2011
- [ ] OWC 2012
- [x] OWC 2013
- [x] OWC 2014
- [x] OWC 2015
- [x] TWC 2011
- [ ] TWC 2012
- [x] TWC 2013
- [x] TWC 2014
- [x] TWC 2015
- [ ] TWC 2016
- [ ] CWC 2012
- [ ] CWC 2013
- [x] CWC 2014
- [x] CWC 2015
- [ ] CWC 2016
- [x] MWC 2014 (4K/7K)
- [x] MWC 2015 (4K)
- [x] MWC 2016 (7K)
### Making Good Sliders
- [ ] Arcs
- [ ] Waves
- [ ] Beat Blankets
- [ ] Circles
- [ ] Elbows
- [ ] Hearts
- [ ] Wiggles
- [ ] Loops
### History of osu!
- [x] '07/'08
- [ ] '09/'10
- [ ] '11/'12
- [ ] '13/'14
- [ ] '15/'16
### osu! File Formats
- [ ] .osk
- [ ] .osz
- [ ] .osu
- [ ] .osr
- [ ] .osb
- [ ] .db
### Difficulties
- [x] Easy
- [x] Normal
- [x] Hard
- [x] Insane
- [x] Expert
- [ ] Kantan
- [ ] Futsuu
- [ ] Muzukashii
- [ ] Oni
- [ ] Ura Oni
- [ ] Cup
- [ ] Sallad
- [ ] Platter
- [ ] Rain
- [ ] Overdose
- [ ] Basic
- [ ] Novice
- [ ] Advanced
- [ ] Exhaust
- [ ] Maximum
### Osu! namespace
- [ ] About
- [ ] Copyrights
- [ ] Article Style Guide
- [ ] Current events
- [ ] Autoconfirmed users
- [ ] How you can help!
### Disambiguation (article choice)
- [ ] Bancho
- [ ] Easy
- [ ] Mod
### Miscellaneous
- [ ] Code of Conduct
- [ ] T-Aiko v1.0
- [ ] Timelines
- [ ] Beatmap Editor/Menu
- [ ] AIMod
- [ ] Best of 2012
- [ ] Project: akrolsmir
- [ ] Qianese
- [ ] Report System
- [ ] Tablet purchase
- [ ] Slider
- [ ] User configuration file
- [ ] Universal Offset

**Comment by TPGPL** [comment]
emm, you have to insert **x** into square brackets to get check.

**Comment by Rumberkren** [comment]
# Wiki Completion
## Articles
### Getting Started
- [x] Registration
- [ ] Installation
- [x] Newbie's Guide
- [x] Game's Interface
- [ ] Options
- [x] Hit Objects
- [x] Rules
- [x] Rules (simplified)
- [ ] Glossary
- [x] Shortcut Key Reference
- [x] osu! Program Files
- [x] osu! File Formats
- [x] BBCode
- [x] List of Guides
- [x] Help Center
 
### osu! Game Styles
- [ ] Basic explantation
- [x] Multi-play
- [x] Standard
- [x] Taiko
- [ ] Mania
- [x] Catch the Beat
- [x] osu!stream
- [x] osu!droid
- [ ] opsu!
- [ ] osu!wp
- [ ] T-Aiko
- [ ] Beats
- [ ] osu!MapDownloader
 
### Beatmap Editor
- [ ] Beatmap Editor
- [ ] Compose
- [ ] Design
- [ ] Timing
- [ ] Song Setup
- [ ] Storyboard Scripting
- [ ] Beatmapping
- [x] Beat Snap Divisor
- [x] Distance Snap
- [ ] Custom Sample Overrides
- [ ] Kiai Time
- [ ] Mapping Techniques
- [ ] Skinning
- [ ] Skin.ini
- [ ] Storyboarding
- [ ] Difficulty appropriate gameplay elements
 
### Online Editing and Ranking
- [ ] Beatmap Forum
- [x] Submission
- [x] Beatmap Approval
- [x] How to Get Your Map Ranked
- [x] Modding
- [x] Getting Your Map Modded
- [x] Kudosu
- [x] Star Priority
- [ ] Music Theory
- [ ] Audio Editing
- [ ] Ranking Criteria
- [x] Ranking Criteria: Standard
- [x] Ranking Criteria: Catch The Beat
- [x] Ranking Criteria: Taiko
- [ ] Ranking Criteria: Mania
 
 ### World of osu!
- [ ] Announcements Archive
- [x] Beatmaps
- [x] Game Modifiers
- [ ] Achievements
- [x] Performance Points
- [x] Play Styles
- [x] Score
- [x] Accuracy
- [x] Chat Console
- [x] BanchoBot
- [ ] Mascots
- [ ] Livestreaming osu!
- [ ] osu!tourney
- [x] Internet Relay Chat
- [x] Tournaments
- [x] Showcases
- [ ] Contests
- [x] osu!academy
- [x] osu!talk
- [x] osu!supporter
- [ ] osu!store
 
### People
- [x] The Team
- [x] Administrators/Global Moderation Team
- [x] Quality Assurance Team
- [x] Beatmap Nomination Group
- [x] Language Moderators
- [x] osu! Alumni
- [x] Support Team
- [x] Community Contributors
 
### Guides
- [ ] How to Run osu! on Your Mac without using Boot Camp
- [x] GL Support Issues
- [ ] How to not Embarrass Yourself in the Modding Queues Subforum
- [ ] How to not Embarrass Yourself in the Projects Subforum
- [ ] Changing Title Text
- [ ] Starting a Beatmap Project
- [ ] Setting the Offset on the Correct Beat
- [ ] Collab Information
- [ ] Changing the Map's Artist or Title
- [ ] Making nice recording for Youtube
- [ ] Videos from YouTube
- [ ] Compressing Videos
- [ ] Getting songs from Video Games
- [ ] Basic MP3 modifications
- [ ] Reducing SB Load
- [ ] SGL Tool
- [ ] Adding custom hitsounds
- [ ] Custom Hitsound Library
- [ ] Making Properly Centered Spinners
- [ ] Cropping with Simple Backgrounds
- [ ] Cropping with Complex Backgrounds
- [ ] How to do 15° Patterns
- [ ] Making Good Sliders
- [ ] AIBat
- [ ] Fitting the Size-limit
- [ ] Mapping Taiko Difficulties
- [ ] How to time songs?
- [x] How do beatmaps get ranked?
- [x] Handling Cheating/Foul Play
- [ ] Tips and Tricks for osu!
 
### Skinning
- [ ] Tutorial:
- [ ] Tutorial: Interface
- [ ] Tutorial: Sounds
- [ ] Tutorial: Standard
- [ ] Tutorial: Catch the Beat
- [ ] Tutorial: Taiko
- [ ] Tutorial: Mania
- [ ] Elements: Interface
- [ ] Elements: Sounds
- [ ] Elements: Standard
- [ ] Elements: Catch the Beat
- [ ] Elements: Taiko
- [ ] Elements: Mania
 
### Storyboard Scripting
- [ ] Cheat Sheet
- [ ] General Rules
- [ ] Storyboard Objects
- [ ] Commands
- [ ] Compound Commands
- [ ] Miscellaneous
- [ ] Command Shorthand
- [ ] Storyboard Audio
- [ ] Storyboard Variables
- [ ] osu File Toggles
 
### Mapping Techniques
- [ ] Formations
- [ ] Rhythm Techniques
- [ ] Jumping Techniques
- [ ] Unrankable Techniques
- [ ] Hit Circle Techniques
- [ ] Slider Techniques
- [ ] Spinner Techniques
- [ ] Mapping Techniques/Basics
 
### World Cups
- [x] OWC 2010
- [x] OWC 2011
- [ ] OWC 2012
- [x] OWC 2013
- [x] OWC 2014
- [x] OWC 2015
- [x] TWC 2011
- [ ] TWC 2012
- [x] TWC 2013
- [x] TWC 2014
- [x] TWC 2015
- [ ] TWC 2016
- [ ] CWC 2012
- [ ] CWC 2013
- [x] CWC 2014
- [x] CWC 2015
- [ ] CWC 2016
- [x] MWC 2014 (4K/7K)
- [x] MWC 2015 (4K)
- [x] MWC 2016 (7K)
 
### Making Good Sliders
- [ ] Arcs
- [ ] Waves
- [ ] Beat Blankets
- [ ] Circles
- [ ] Elbows
- [ ] Hearts
- [ ] Wiggles
- [ ] Loops
 
### History of osu!
- [x] '07/'08
- [ ] '09/'10
- [ ] '11/'12
- [ ] '13/'14
- [ ] '15/'16
 
### osu! File Formats
- [ ] .osk
- [ ] .osz
- [ ] .osu
- [ ] .osr
- [ ] .osb
- [ ] .db
 
### Difficulties
- [x] Easy
- [x] Normal
- [x] Hard
- [x] Insane
- [x] Expert
- [ ] Kantan
- [ ] Futsuu
- [ ] Muzukashii
- [ ] Oni
- [ ] Ura Oni
- [ ] Cup
- [ ] Sallad
- [ ] Platter
- [ ] Rain
- [ ] Overdose
- [ ] Basic
- [ ] Novice
- [ ] Advanced
- [ ] Exhaust
- [ ] Maximum
 
### Osu! namespace
- [ ] About
- [ ] Copyrights
- [ ] Article Style Guide
- [ ] Current events
- [ ] Autoconfirmed users
- [ ] How you can help!
 
### Disambiguation (article choice)
- [ ] Bancho
- [ ] Easy
- [ ] Mod
 
### Miscellaneous
- [ ] Code of Conduct
- [ ] T-Aiko v1.0
- [ ] Timelines
- [ ] Beatmap Editor/Menu
- [ ] AIMod
- [ ] Best of 2012
- [ ] Project: akrolsmir
- [ ] Qianese
- [ ] Report System
- [ ] Tablet purchase
- [ ] Slider
- [ ] User configuration file
- [ ] Universal Offset

**Comment by mfaishalakbar** [comment]
Thanks for the help :D .

**Comment by troke12** [comment]
hmm

**Comment by mfaishalakbar** [comment]
Updated.

**Comment by vzrenggamani** [comment]
- Installation has been translated #1266 by @fajar13k 
- Mascots #1272 
- osu!tourney #1205

**Comment by fajar13k** [comment]
Let's update this up.
- Welcome
- Installation
- Mascots
- osu!tourney
- Reporting Bad Behaviour
- Visual Settings
- BanchoBot
- Internet Relay Chat
- Tournaments

All translated by me, with help of @vzrenggamani , @Nivalyx , and Indonesian GMT, Shurelia

**Comment by mfaishalakbar** [comment]
Nice!

**Comment by fajar13k** [comment]
More updates as of May 19th, 2018:
- About
- Chat Console
- Disambiguation
- Do you really want to ask peppy?
- Registration
- Rules
- Twitter
- osu! wiki Contribution Guide
- osu!api
- osu!academy

Special thanks to these guys: @acylla @Nivalyx @vzrenggamani @nanaya , Shurelia, GSculerlor, TheFaR8.
Current milestone: **20/69** osu! wiki Articles & **100%** [osu! web](https://osu.ppy.sh) ID localisation.
Next update will be **a month** away from this post.

**Comment by fajar13k** [comment]
New additions as of August 25th, 2018:
- Accuracy
- Beatmaps
- Beatmaps and Packs
- Beatmapping
- Forums
- History of osu! Main Menu
- History of osu! (2007)
- History of osu! (2008)
- History of osu! (2009)
- History of osu! (2010)
- History of osu! (2011)
- History of osu! (2012)
- How Can You Help!
- Tournament Drawings
- osu!supporter

Special thanks to these guys for contributing:
@acylla @vzrenggamani @Rendyindo @GSculerlor @troke12 and the others that i can't name.
Will catch up again when i have chance.
