### ISSUE TITLE
Folder status in wiki.

### ISSUE THREAD

**Issue by RaikireHiuduo** [ppy/osu-wiki#131]
Close this issue when the wiki folder received another major restructuring.
This is roughly how the osu!wiki structured, now since #127 was merged.

[Accurate as of 14/2/2017, Valentine's Day]

Root folders must satisfy one or more of these conditions:-

- It must be an introduction to the topic in detail (FAQ, Beatmapping, Modding, ...)
- It is an index folder of a topic, separated by sections using subfolders due to distinctive difference and text length (List_of_Guides, Game_Modes, History_of_osu!, ...)
- It does not fit in any of the folders/distinctive topic/important (BBCode, Do_you_really_want_to_ask_peppy, shared, ...).

Folders with known subfolders:-

- Achievements (First version of Beatmap packs achievement)
- Annoucement (Anything from the News, except Tournaments and Best_Of)
- Beatmap_Editor (Anything that can be seen in the Beatmap Editor in Edit mode)
- Best_Of (years by folders)
- Difficulties (difficulty explanation for beatmapping/play by folder)
- Game_Modes (osu! game modes and external ports)
  - External_Ports (External ports emulating any of osu! game mode or capable of reading osu!beatmap)
- Game_Modifiers (Summary)
- History_of_osu! (osu!wiki = osu!wiki history [was Current_Events]. 1 = 2007/2008, 2 = ...)
- Legal (Copyright, TOC)
- Mapping_Techniques (Specific section separation by folder) 
- osu!_File_Formats (file extension format, for developers)
- osu!_Program_Files (files in osu! folder)
- People (self-explanatory)
- Ranking_Criteria (by game modes)
- Reporting_Bad_Behaviour (Handling_Cheating guide is inside)
- Rules (short rules)
- Skinning (Skinning elements)
- Storyboard_Scripting (Separated by sections)
- Storyboards (Maps list)
- Submission (Ranking Procedure)
- Tournaments (separated by events, separated by year)

Guides:-

- Beatmap_Editor_Guides (Forum-written guides regarding Beatmapping and offline development of beatmap)
- List_of_Guides (Forum-written guides not related to development of beatmaps)
- Modding_Guides (Forum-written guides regarding Modding and online development of beatmap)
- Tools (Any tools goes here)

General help:-

- About (two lines about osu! as a Laconic description)
- BBCode (forum styling language used)
- Do_you_really_want_to_ask_peppy (when attempting to message peppy by forum message)
- Help_Center
- Reporting_Bad_Behaviour
- Twitter

osu!wiki help:-

- Article_Style_Guide
- How_You_Can_Help! (by peppy)
- osu!wiki_contribution_guide

?

- Legal

**Comment by TPGPL** [comment]
We also have to regex the repo

**Comment by Joehuu** [comment]
We can make separate issues when folder structure is a problem. Closing as outdated.
