### ISSUE TITLE
Wrong code for "ph.md" files

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1496]
`ph` is not shown on this [*reliable* source](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). Confused if it's Tagalog(`tl`) or Filipino(`fl`). Checked other sources for reliability and couldn't find a code for `Filipino`.

**Comment by loliprotector** [comment]
It should be Filipino(`fl`) however most translation sites offer only Tagalog(`tl`)
But if both is available, it should really be Filipino as it is the [official language of the country](http://bakitwhy.com/articles/difference-between-languages-tagalog-and-filipino), while Tagalog is a dialect.
>Tagalog is the native language of the Tagalog ethnic group that is based in the provinces of Central and Southern Luzon. [...] it  was therefore declared to be the **Official Language** by the first Constitution of the Philippines, which was drafted back in __1897__.

> Filipino, on the other hand, was proclaimed by the present Constitution to be the Philippine National Language in __1987__. Additionally, along with English, it is also the **Official Language of Communication** and **Instruction in the Education System of the Philippines**. [...] There are actually a multitude of Filipino words that are in fact loan words from other languages. These source languages include former colonist languages like **Spanish** (cómo está > kumustá = hello) and **English** (kompyuter = computer), as well as from other non-native languages like **Chinese** (keh-ya  > kuya = big brother), **Arabic** (selamat > salamat = thank you), **Malay** (sedap > saráp = delicious), and **Sanskrit** (cerita > salitâ = speak), among others.

**Comment by kj415j45** [comment]
I think `ph.md` should be rename to `tl.md`, since osu-web only define
```php
        'tl' => [
            'name' => 'Tagalog',
            'flag' => 'PH',
        ],
```
at https://github.com/ppy/osu-web/blob/master/app/Libraries/LocaleMeta.php#L118

`PH` is the country code while `tl` is the language code

**Comment by Joehuu** [comment]
Going with `tl.md`. Works with the current web code and I think it's right.
