### ISSUE TITLE
"Hit sound" or "Hitsound"

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1532]
I've seen multiple occurrences for each.

**Comment by RockRoller01** [comment]
I would say hitsound. All the files are prefix-hitnormal/hitclap/...

**Comment by Okorin** [comment]
https://osu.ppy.sh/help/wiki/Article_Styling_Criteria#terminology i just went with this on most of the RC, since `hit` and the other things are separated on a general level, they should be in all other cases as well
