### ISSUE TITLE
Repos' readme format are not consistent

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1547]
The main repos have different formats.

`osu` has all heading level 1's. All the copy pasted minor repos have this format.

~`osu-web` has badges below the main header.~ That's fine.

`osu-wiki` is the one I edited at least once, ~so I think it should be this~. All repos in this organization should have at least Discord.

Edit: I think badges below title is better as they won't offset now.

**Comment by peppy** [comment]
Thanks for this!
