### ISSUE TITLE
"How you can help" needs an update

### ISSUE THREAD

**Issue by FreezyLemon** [ppy/osu-wiki#1548]
The whole thing is just a copy of a post by peppy which is now over 6 years old.

The content itself isn't bad imo, it's just that it's
1. Written in the first person (I think this should be avoided in a wiki?)
2. Extremely outdated (see e.g. osu!stream reference, osu!weekly reference)

Idk if this should just be "refactored" (keep same content, but remove old stuff & make it a non-personal post) or completely rewritten (new content). I'm just saying it probably shouldn't stay as-is.

**Comment by sr229** [comment]
The case for this is more on paraphrasing, since we want to keep the context but in a different tone and viewpoint. I think I can set this as my TODO.

**Comment by sr229** [comment]
Should be implemented in this PR ^^

OP you're CC'ed for RFC
