### ISSUE TITLE
"osu!standard" should be removed

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1557]
I think we should regress the format by going back to using `osu!` as the game mode ~and `*osu!*` as the game itself.~

In the web, osu!standard is never used anywhere, only in news and other written stuff.

**Comment by MegaApplePi** [comment]
We should keep it as is so we can easily change it in the future. Or at least, that was the initial idea from last year.

**Comment by Joehuu** [comment]
Closing this, since exceptions will be made on some articles to use `osu!` instead.

The term will still be used for most articles.
