### ISSUE TITLE
Formatting follow up for MWC articles

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1570]
Doing at this very moment for overlooked stuff.

**Comment by Joehuu** [comment]
Quick question, should the images be on it's own `img` folder or is it an exception for tournaments.

**Comment by WalterToro** [comment]
There is no stuff that is shared between tournaments so, most of their images are uploaded on the same folder.

**Comment by Joehuu** [comment]
Some tables are beautified, some are not. We need to pick one for consistent format. What should it be?

**Comment by TPGPL** [comment]
i would go with not beautified, but i don't think articles need *that kind* of changes though, as they aren't visible on the wiki anyways
