### ISSUE TITLE
Some country listings on tournaments are not in alphabetical order

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1574]
~This is one of the some occurrences.~

**Comment by TPGPL** [comment]
Could you give a link to this article?

**Comment by Joehuu** [comment]
Well, these occurrences are mostly only from MWC, so I should fix it on my PR. Also, I made this issue since these kinds of things were not checked at the time of writing.

And here (there are more occurrences):

https://osu.ppy.sh/help/wiki/Tournaments/MWC/2017/4K.

**Comment by Joehuu** [comment]
Closing. If I stumble upon another one, I'll just fix it.
