### ISSUE TITLE
Tournament template should be updated

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1580]
It should be used for future tournaments to avoid such inconsistency. It also should be linked to the ASC or whatever place, so people will know where it is.

It'll move to a folder for multiple languages, so `Tournaments/Template/en.md` maybe.

**Comment by fajar13k** [comment]
Maybe link on `See also:` on Tournaments Index page too?

**Comment by Joehuu** [comment]
That could work. Idk if people actually see that page when they make a tournament.

It's more of a formatting thing, so that's why I suggested the ASC first.

**Comment by Joehuu** [comment]
Reference #350, and look at the recently merged formatting changes to the official tournaments (OWC and MWC). *Btw, there is still formatting errors overlooked, and I plan to fix them.*
