### ISSUE TITLE
Is it a good idea not to translate anything legal-related?

### ISSUE THREAD

**Issue by axmmisaka** [ppy/osu-wiki#1582]
As Mr. peppy mentioned in commit
1fb7f10fd4045ee9ef7d76bef46f01d39ed06512
it is indeed a problem to keep translations up-to-date, and my translations is then removed.

So since I am now able to translate a up-to-date one (but I can't guarantee anything since I don't learn laws), is it a good idea to have a up-to-date one or it's better to find something else to translate?

**Comment by sr229** [comment]
@axmmisaka Please be reminded Translations in UX perspective would promote accessibility - even though its a difficult task to keep translation up to date, it's needed to promote greater clarity for non-native speakers.

**Comment by cl8n** [comment]
I think they may be worth translating, but you should include a giant disclaimer at the top stating that it's not legally binding and the translation is only for convenience. then link to the English version

**Comment by axmmisaka** [comment]
There was a disclaimer.  
And got it - I'll do that asap.

**Comment by sr229** [comment]
@TPGPL probably we should tag this

**Comment by cl8n** [comment]
@peppy what are your thoughts on bringing these back? we have an "outdated" tag now, if the articles ever fall behind the English version. the Chinese article already has a good disclaimer stating that only the English version has legal validity etc., so we could use that as a template for all other languages (see https://github.com/ppy/osu-wiki/pull/1054#issuecomment-366638179)

**Comment by peppy** [comment]
It should be implemented at an osu-web level, where the disclaimer is translated as its own string
