### ISSUE TITLE
Better system for reviews

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1601]
Specifically *formatting* reviews, the one's I often do and never complete in a single review (multiple [infinite] reviews).

Can we PR into someone's branch? It'll make things easier and idk if people know how to do it or are willing to.

**Comment by cl8n** [comment]
for a project like this, it's probably safe to assume people only have minimal knowledge of git--- but it doesn't hurt to try, if you don't mind giving them a quick explanation of what to do if they ask about it

**Comment by Joehuu** [comment]
People can purely use the GitHub Web Interface and it should be easy to use.

**Comment by Joehuu** [comment]
Closing.
