### ISSUE TITLE
Copied and pasted official tournament ruleset is hard to maintain

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1611]
I know nothing about the official tournaments, but it seems some or maybe most of the rules apply every year (and every game mode?), but they have been slighted worded/formatted differently.

It is hard to maintain (grammar, consistency, etc.) and I think it should have a page of it's own?

Stuff in the wiki shouldn't be copied and pasted anyway. The same information can be referenced and be put on another page with all the common rules. All rules that are exclusive in that tournament can directly be on the said tournament article.

**Comment by TPGPL** [comment]
i would copy all rulesets from the original forum posts

**Comment by Joehuu** [comment]
Alright will do on TWC#3, but it'll be a consistency problem in terms of wording and format.

Also mentioning #1520, the ruleset should be past tense too.

**Comment by cl8n** [comment]
this ended up being a large part of the discussion in #7564 so let's just use that issue instead to track
