### ISSUE TITLE
Make index pages for every folder

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#1658]
Enforcing https://osu.ppy.sh/help/wiki/Article_Styling_Criteria#index-articles. Even if they just link to articles below it, better than 404

related to discussion in https://github.com/ppy/osu-web/pull/3595

**Comment by Repflez** [comment]
I see. If possible, can we search for more cases like this? If anything to give closure to the root issue :stuck_out_tongue:

**Comment by Joehuu** [comment]
AFAIK it is only on tournaments.
