### ISSUE TITLE
File format docs refer to "aforementioned" objects which are described after, not before

### ISSUE THREAD

**Issue by christopher-dG** [ppy/osu-wiki#1679]
https://www.merriam-webster.com/dictionary/aforementioned

I think it only happens [here](https://osu.ppy.sh/help/wiki/osu!_File_Formats/Db_(file_format)), everywhere it's used except for Int-Double pairs and timing points.

**Comment by cl8n** [comment]
can be closed now, every usage of "aforementioned x" is preceded by "number of x"
