### ISSUE TITLE
Which OSU graphics tablet should I get?

### ISSUE THREAD

**Issue by wushan67** [ppy/osu-wiki#1686]
Hey! I'm an new Osu! player. I'm looking forward to buy a graphics tablet on my budget. I have found 2 of them, but I don't know which one is good. Here they are

($27.99) XP-Pen G430S 4" x 3" OSU Tablet Ultrathin Graphic Tablet : https://www.xp-pen.com/goods/show/id/302.html .

($49.99) XP-Pen G640S 6 x 3.75 Inches OSU Tablet Graphics Drawing Pen Tablet : https://www.xp-pen.com/goods/show/id/371.html .

Thank you! I'm looking forward to a reply on which is great, since the osu! tablet is offsale.

**Comment by WalterToro** [comment]
This is not the place to look for this *kind* of help, you should ask on other parts (like the [osu! Forums](https://osu.ppy.sh/community/forums) for example).
