### ISSUE TITLE
[Proposal] Enforce "One-commit" PRs

### ISSUE THREAD

**Issue by sr229** [ppy/osu-wiki#1751]
The main objective of this issue is to promote a more cleaner Git History for osu-wiki, as employed by other GitHub repositories.

### Rationale

While Pull Requests has a squash and merge option, we should keep in mind that the maintainers use the Merge button on its standard strategy. Git History seems to be cluttered too much with minor fixes.

### One-Commit Strategy

The main strategy here is to use a "Squash-and-Force Push" flow. Where as:

- Pull Requestee Makes minor changes for compliancy.

- Pull Requestee then squashes it on the "root" before their own changes.

- Pull Requestee then submits the updated changes on GitHub using a force-push.

### Advantages

This would relatively clean the Git History and would focus on one commit that focuses on the major changes. While this won't cover the Pull Requests before, this should cover future Pull Requests.

**Comment by sr229** [comment]
Its relatively easy to do commit squashing during your PR.

- Open `git log` and find the change before your own unmerged changes.
- Commit all changes to prevent work loss.
- Then run the following :  
    ```
     git reset --soft <commit_hash_before_your_changes>
     git commit -am "your commit message here" -s 
     git push origin +<pr-branch>
   ````

**Comment by kj415j45** [comment]
It would be easier if we use squash merge :/

**Comment by sr229** [comment]
@kj415j45 Sadly this isn't the default on this PR for the merge strategy. But it is more recommended for ease of use, but this is more cleaner IMHO since you can use merge strategy and keep your name on a seperate changeset, as opposed to Squash which will append your name along with the merger

**Comment by MegaApplePi** [comment]
This would be problematic for those only using the GitHub web interface or Desktop. Although this is might a small portion of us, those are still methods to contribute. If you wanted a list of changes in general, the merge log should be enough (`git log --merges`).

But, even if we did the one commit per pull request, there still would be two commits per pull request since there is one from the author and one from the merger which should reference the pull request.

**Comment by sr229** [comment]
That's intended from the merge strategy @MegaApplePi. However I do see squash as a viable option by default as a alternative for merging for a cleaner Git History, because right now the Git History shouldn't be riddled too much with minor fixes and only the main changes.

**Comment by Repflez** [comment]
While the benefits make it a viable option, it would raise the bar more than is needed to be for newcomers that want to contribute to the wiki.

**Comment by sr229** [comment]
I think we can close this in favor of making Squash and Merge as our default merge strategy for PR merges in wiki.
