### ISSUE TITLE
Enforce including the Article Name and Language in every commit

### ISSUE THREAD

**Issue by Repflez** [ppy/osu-wiki#1756]
Currently there's an enforced guideline [to use meaningful commit descriptions](https://osu.ppy.sh/help/wiki/osu!_wiki_Contribution_Guide/Common_Issues#someone-told-me-to-use-meaningful-commit-messages!) for every PR. While this makes commits readable, it makes hard to understand what article is actually being edited in the commit.

My proposal is to change the standard for commit names for every commit to include the article and language that's edited to the following:

```
[Main Page/en] Change description
```

This would also enforce a "One file per commit" guideline, to avoid cluttering the short description with article names.

Comments are appreciated.

**Comment by kj415j45** [comment]
```
[zh] Tournament/CMT: Apply reviews


Co-authored-by: somebody <somebody@users.noreplay.github.com>
```

I suggest to use this format. (and add reviewer to co-author)

**Comment by cl8n** [comment]
sounds like it might over-complicate things. there are plenty of ways to browse git history effectively without writing tags into commit messages

this is like prefixing commits to a codebase with [Module name] or something. it's pretty redundant when you can easily check what the commit changes

**Comment by cl8n** [comment]
closing this and #1761, it's been almost a year since these were opened and we've had no problems with our lax guidelines about commit messages
