### ISSUE TITLE
Spanish Wiki Completion

### ISSUE THREAD

**Issue by axterix123** [ppy/osu-wiki#176]
# Wiki Completion
### Getting Started
- [x] Registration
- [x] Installation
- [x] Newbie's Guide
- [x] Game's Interface
- [x] Options
- [x] Hit Objects
- [x] Rules
- [ ] Rules (simplified)
- [ ] Glossary
- [x] Shortcut Key Reference
- [ ] osu! Program Files
- [ ] osu! File Formats
- [ ] BBCode
- [x] List of Guides
- [x] Help Center

### osu! Game Styles
- [x] Basic explantation
- [ ] Multi-play
- [ ] Standard
- [x] Taiko
- [x] Mania
- [x] Catch the Beat
- [ ] osu!stream
- [ ] osu!droid
- [ ] opsu!
- [ ] osu!wp
- [ ] T-Aiko
- [ ] Beats
- [ ] osu!MapDownloader

### Beatmap Editor
- [x] Beatmap Editor
- [x] Compose
- [ ] Design
- [x] Timing
- [ ] Song Setup
- [ ] Storyboard Scripting
- [x] Beatmapping
- [ ] Beat Snap Divisor
- [ ] Distance Snap
- [ ] Custom Sample Overrides
- [ ] Kiai Time
- [ ] Mapping Techniques
- [ ] Skinning
- [ ] Skin.ini
- [ ] Storyboarding
- [ ] Difficulty appropriate gameplay elements

### Online Editing and Ranking
- [ ] Beatmap Forum
- [ ] Submission
- [ ] Beatmap Approval
- [ ] How to Get Your Map Ranked
- [x] Modding
- [ ] Getting Your Map Modded
- [ ] Kudosu
- [ ] Star Priority
- [ ] Music Theory
- [ ] Audio Editing
- [x] Ranking Criteria
- [ ] Ranking Criteria: Standard
- [ ] Ranking Criteria: Catch The Beat
- [x] Ranking Criteria: Taiko
- [x] Ranking Criteria: Mania

 ### World of osu!
- [ ] Announcements Archive
- [x] Beatmaps
- [ ] Game Modifiers
- [x] Achievements
- [x] Performance Points
- [x] Play Styles
- [ ] Score
- [x] Accuracy
- [ ] Chat Console
- [x] BanchoBot
- [ ] Mascots
- [ ] Livestreaming osu!
- [ ] osu!tourney
- [ ] Internet Relay Chat
- [ ] Tournaments
- [ ] Showcases
- [ ] Contests
- [ ] osu!academy
- [ ] osu!talk
- [x] osu!supporter
- [ ] osu!store

### People
- [x] The Team
- [x] Administrators/Global Moderation Team
- [x] Quality Assurance Team
- [x] Beatmap Nomination Group
- [x] Language Moderators
- [x] osu! Alumni
- [x] Support Team 
- [ ] Community Contributors

### Guides
- [ ] How to Run osu! on Your Mac without using Boot Camp
- [ ] GL Support Issues
- [ ] How to not Embarrass Yourself in the Modding Queues Subforum
- [ ] How to not Embarrass Yourself in the Projects Subforum
- [ ] Changing Title Text
- [ ] Starting a Beatmap Project
- [ ] Setting the Offset on the Correct Beat
- [ ] Collab Information
- [ ] Changing the Map's Artist or Title
- [ ] Making nice recording for Youtube
- [ ] Videos from YouTube
- [ ] Compressing Videos
- [ ] Getting songs from Video Games
- [ ] Basic MP3 modifications
- [ ] Reducing SB Load
- [ ] SGL Tool
- [ ] Adding custom hitsounds
- [ ] Custom Hitsound Library
- [ ] Making Properly Centered Spinners
- [ ] Cropping with Simple Backgrounds
- [ ] Cropping with Complex Backgrounds
- [ ] How to do 15° Patterns
- [ ] Making Good Sliders
- [ ] AIBat
- [ ] Fitting the Size-limit
- [ ] Mapping Taiko Difficulties
- [ ] How to time songs?
- [ ] How do beatmaps get ranked?
- [ ] Handling Cheating/Foul Play
- [ ] Tips and Tricks for osu!

### Skinning
- [ ] Tutorial:
- [ ] Tutorial: Interface
- [ ] Tutorial: Sounds
- [ ] Tutorial: Standard
- [ ] Tutorial: Catch the Beat
- [ ] Tutorial: Taiko
- [ ] Tutorial: Mania
- [ ] Elements: Interface
- [ ] Elements: Sounds
- [ ] Elements: Standard
- [ ] Elements: Catch the Beat
- [ ] Elements: Taiko
- [ ] Elements: Mania

### Storyboard Scripting
- [ ] Cheat Sheet
- [ ] General Rules
- [ ] Storyboard Objects
- [ ] Commands
- [ ] Compound Commands
- [ ] Miscellaneous
- [ ] Command Shorthand
- [ ] Storyboard Audio
- [ ] Storyboard Variables
- [ ] osu File Toggles

### Mapping Techniques
- [ ] Formations
- [ ] Rhythm Techniques
- [ ] Jumping Techniques
- [ ] Unrankable Techniques
- [ ] Hit Circle Techniques
- [ ] Slider Techniques
- [ ] Spinner Techniques
- [ ] Mapping Techniques/Basics

### World Cups
- [ ] OWC 2010
- [ ] OWC 2011
- [ ] OWC 2012
- [x] OWC 2013
- [x] OWC 2014
- [ ] OWC 2015
- [ ] TWC 2011
- [ ] TWC 2012
- [ ] TWC 2013
- [ ] TWC 2014
- [x] TWC 2015
- [ ] TWC 2016
- [ ] CWC 2012
- [ ] CWC 2013
- [x] CWC 2014
- [ ] CWC 2015
- [ ] CWC 2016
- [x] MWC 2014 (4K/7K)
- [ ] MWC 2015 (4K)
- [ ] MWC 2016 (7K)

### Making Good Sliders
- [ ] Arcs
- [ ] Waves
- [ ] Beat Blankets
- [ ] Circles
- [ ] Elbows
- [ ] Hearts
- [ ] Wiggles
- [ ] Loops

### History of osu!
- [x] '07/'08
- [ ] '09/'10
- [ ] '11/'12
- [ ] '13/'14
- [ ] '15/'16

### osu! File Formats
- [ ] .osk
- [ ] .osz
- [ ] .osu
- [ ] .osr
- [ ] .osb
- [ ] .db

### Difficulties
- [x] Easy
- [x] Normal
- [x] Hard
- [x] Insane
- [x] Expert
- [ ] Kantan
- [ ] Futsuu
- [ ] Muzukashii
- [ ] Oni
- [ ] Ura Oni
- [ ] Cup
- [ ] Sallad
- [ ] Platter
- [ ] Rain
- [ ] Overdose
- [ ] Basic
- [ ] Novice
- [ ] Advanced
- [ ] Exhaust
- [ ] Maximum

### Osu! namespace
- [x] About
- [ ] Copyrights
- [ ] Article Style Guide
- [ ] Current events
- [ ] Autoconfirmed users
- [ ] How you can help!

### Disambiguation (article choice)
- [ ] Bancho
- [ ] Easy
- [ ] Mod

### Miscellaneous
- [ ] Code of Conduct
- [ ] T-Aiko v1.0
- [ ] Timelines
- [ ] Beatmap Editor/Menu
- [ ] AIMod
- [ ] Best of 2012
- [ ] Project: akrolsmir
- [ ] Qianese
- [ ] Report System
- [ ] Tablet purchase
- [ ] Slider
- [ ] User configuration file
- [ ] Universal Offset

**Comment by Dakken** [comment]
¿Puedo ayudar?

**Comment by Repflez** [comment]
@Dakken Nadie te está impidiendo. Solo hazlo y dejanos una muy buena traducción (o lo que puedas).

![](https://cloud.githubusercontent.com/assets/659133/26228741/658f2900-3bf9-11e7-8b50-6c0789d225cd.jpg)

btw, si tienes dudas ve al [servidor de discord](https://discord.gg/ppy) y pregunta en el canal `#osu-wiki`; solo que el canal es en inglés.

**Comment by Byza** [comment]
¡Buenas!

Acabo de empezar así que perdón de antemano si no debo escribir aquí...
¿Esto está actualizado? Entiendo que es una página de seguimiento del proceso de traducción pero voy a uno en concreto, por ejemplo "Playstyles", que se supone que está traducido... y no hay es.md 

¿O me estoy equivocando muchísimo?

**Comment by Raidencio** [comment]
Guía para el BBCode traducida al español. Actualmente en PR y necesita reviews.
