### ISSUE TITLE
[Proposal] Enforce Semantic Commit Messages

### ISSUE THREAD

**Issue by sr229** [ppy/osu-wiki#1761]
Related Literature: https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716

## Rationale

Prior to our establishment of standardization of osu!wiki's contribution schema, we have seen countless contributions (which is good) - however, there was an issue tracking commit details properly due to the scale of the repository, and the amount of minor fix commits.

## Semantic Commits

A Semantic Commit is structured to following:

```
chore(Wiki/OWCG): add hat wobble
^--^  ^-------^  ^------------^
|            |             |
|            |             +-> Summary in present tense.
|            |
|            + -> Category and area that is changed.
|
+-------> Type: chore, docs, feat, fix, refactor, style, or test.
```

Accepted Commit types might be : 

| **TYPE**  | **DESCRIPTION**   |
|---|---|
| `chore`  |  General repository clean-up or maintenance tasks.  |
| `fix`  | Article fixes for a specific category.  |
| `add` | Addition of a new article to a wiki. |

Accepted Prefixes might be:

| **TYPE**  | **DESCRIPTION**   |
|---|---|
| `(Wiki/<Article>)`  |  Wiki Article targets.  |
| `(News/<Article>)`  | News Article targets.  |

### Advantages

This would allow us to know precisely which commits has changed a specific part of the wiki - without opening the whole change set.

**Comment by cl8n** [comment]
like #1756 , I think this is overkill and beyond

why would I need to know, on short hand, exactly the type and scope of changes of one commit anyway

**Comment by sr229** [comment]
@cl8n for larger change sets, this would allow us to see a summary f the change without opening the whole changelist. 

And for newer contributors, this would prevent occurences of using the GitHub web's default commit messages used for edits.

**Comment by cl8n** [comment]
isn't there already a rule in ASC or something that says to use meaningful commit messages?

**Comment by sr229** [comment]
@cl8n This further augments ASC conventions since there is still some degree of minor fixes not being pinpointed which article was fixed.

There are two cases why we need this:

- Better pinpointing - If we know which category and article target is changed by a minor commit, we won't need to see the changelist to pinpoint exactly which was fixed.

- Tracking Chores - We can segregate new article task commits or fix commits from chore commits with Semantic Commit Messages.
