### ISSUE TITLE
[Proposal] Squash and Merge as default Merge strategy for Repository

### ISSUE THREAD

**Issue by sr229** [ppy/osu-wiki#1762]
## Rationale 

based on what @cl8n and I discussed- #1761 and #1756  might be too much for new contributors.

This proposal will overturn both referenced proposals as it would effectively eliminate non-adhering commits.

## Squash and Merge

As its name implies, we squash the commits as one and merges it as a commit on the tree. It presents advantages like:
 - Easier tracking - we track a specific merge commit that would immediately narrow down to a PR.
 - Relaxed commit message conventions - we can use our current ASC Commit conventions - given that the squash merge message is also adherent to the conventions.

**Comment by Joehuu** [comment]
Closing, peppy disabled this.
