### ISSUE TITLE
Modding page needs updates

### ISSUE THREAD

**Issue by osuChaos** [ppy/osu-wiki#1767]
https://osu.ppy.sh/help/wiki/Modding/

Lots of information about modding that is written for the now largely defunct forum based modding system. Needs updating for new beatmap discussion system, especially the `Getting Started` section.

**Comment by sr229** [comment]
Would you kindly provide new Literature so we can update the article? AFAIK we only based this from the Mediawiki version.

**Comment by cl8n** [comment]
#2615
