### ISSUE TITLE
[Request] Wanted wiki features

### ISSUE THREAD

**Issue by RaikireHiuduo** [ppy/osu-wiki#182]
# [Request] Wanted wiki features

Features wanted for wiki writing ~~and screw up the design by inventing internal zany designs~~ but vanilla GitHub Markdown does not support it.

### Redirect

Implemented by MegaApplePi with nanaya guidance.

To add a redirect, see: https://github.com/ppy/osu-wiki/blob/master/wiki/redirect.yaml

### Image size enforcement

Might be awkward to do in Markdown.

MediaWiki has their own syntax which is ``[[File:imagename|attr1|attr2|attr3|...]]``.

Something like below (throwing idea here)?

```
Inline style:-
![alt-text](./img/banana.jpg @69x69 !right "A picture of banana")

Reference style:-
![alt-text][BANANA]
[BANANA]: ./img/banana.jpg @69x69 !right "A picture of banana"
```

#### Enabling Markdown support inside GFM table.

A external Markdown parser within GFM table content.

@TPGPL :-

```
| header | header |
| ------- | ------- |
| [!CONTENT_NAME!] | text |

(...)

[!CONTENT_NAME!]:
{
<content>
}
```

Usage example:-

```
| Item | Description |
| ------- | ------- |
| osu!supporter | [!Supporter!] |

(...)

[!Supporter!]:
{
Many advantages like:
- ok
- rip money
- nice nickname colour
- some direct
- menu bg!!!
}
```

#### Table attribute support

Table attributes like `rowspan`, `colspan`, and `width` support please while at it.

### Page content callout display

MediaWiki: ``{{:Options/Key Bindings}}`` (see the colon at the start?)

When I do this, just blindly display the file content of the file I point to.

Probably pointless (eats up some seconds to process), uses more folders, and annoying to do using current osu-web wiki design (which is using locales unless letting us directly call the `.md` file when doing this).

Was thinking of this while writing Game_Modes, Accuracy, Play_Styles, and Score where some information are fixed (like ScoreV1/ScoreV2, Accuracy formula, and Play Styles).

### Templates

Template support plox.

MediaWiki uses ``{{templatename|var1=orange|var2=lemon|whatisityoucalllove=?}}`` to callout whatever wiki magic you put inside that templatename file and the variable you give to.

Will definitely contribute to server load but ease the real pain in dealing with ``People`` section (have fun C&P to all the language files the table itself when there is a change)

### Gallery

See History of osu!: https://osu.ppy.sh/wiki/History_of_osu!.

Example of usage done in MediaWiki:-

```
<gallery caption="[[Game Modifiers]]." perrow="2" heights="69px" widths="65px">
File:No_Video.png  | [[No Video]] mod
File:Hidden_v1.png | [[Hidden]] mod
</gallery>
```

Specifically, the game modifier icons would be nice to be put in a line rather than chaining them like totem pole like what was done on Accuracy for the screenshots: https://new.ppy.sh/wiki/Accuracy.

_Probably could use a GFM table and ignore @MegaApplePi and the ASG about no images in the table. The Achievements page on new.ppy.sh is doing that (granted, it was before ASG was formulated at all)._

**Comment by MegaApplePi** [comment]
ignore what part of the ASG?

**Comment by RaikireHiuduo** [comment]
@MegaApplePi https://new.ppy.sh/wiki/Article_Style_Guide/#tables

`Never place images inside tables.`

**Comment by sr229** [comment]
this would require using Regular Expressions in the MD engine to add such case matching for Markdown.

Link shortening would be entirely up to osu!web Developers but I have a better suggestion

considering everyone in osu uses ``[[pagename]]``, we can then at least use ``[[wiki:page_name_]]``

**Comment by MegaApplePi** [comment]
(just for documenting purposes, tho you already saw it) https://github.com/ppy/osu-web/pull/1125 adds image captions, but no gallery as of now.

---

I'm working on redirects, but I doubt that we can do anything for the **image size enforcement**, **image gallery**, and **extra table syntax** unless we want to rewrite the entire markdown engine ([parsedown](https://github.com/erusev/parsedown)) that osu-web uses or use really strange markup for the markdown :/

---

Templates support... idk... yet... I'll try to look into it soon (in next 2 months or so~) if no one else takes it on

**Comment by cl8n** [comment]
I could imagine user/beatmap/beatmapset links being a relatively simple and useful thing to create templates for, if we want to start on that soon

**Comment by Joehuu** [comment]
This should go to osu-web to better expose what we want.

**Comment by cl8n** [comment]
- redirect - done
- image size - seems unnecessary in recent times
- blocks in table cell - should be avoided for layout reasons (I would be surprised if just about any table doing this looks sane on mobile)
- content callout - same thing as templates (zero parameter template)
- templates - tracked at https://github.com/ppy/osu-web/issues/2764 -- kind of -- this issue doesn't really describe what "templates" are supposed to be at all...
- gallery - if you find yourself in a situation where this would be a significant benefit, there was probably a better way to layout things in the first place. today, I think a common solution here would be putting multiple block images in an Infobox
