### ISSUE TITLE
Shortened links not repo friendly

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1889]
When I check prs, I can't check the shortened links easily. I have to add `https://osu.ppy.sh` prefix and remove the github url. Probably an ASC change.

**Comment by cl8n** [comment]
the specific case of linking images can help with previewing on GitHub since the top-level `/wiki` is the same. are you trying to check articles on the live site ?

**Comment by Joehuu** [comment]
Oh whoops, I am talking about other links like users and forums that are not repo related.

**Comment by cl8n** [comment]
then i think you didn't mean to include "/help" in the OP ;)

yeah, it seems like a lot of articles already use the hostname so we can just add it back for the rest
