### ISSUE TITLE
Requirements in README

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-wiki#1938]
Looking over at the README, requirements 1 and 3 doesn't make much sense. As people without a "general understanding of the feature-branch workflow" can still make a pull request with their master branch and may get it approved and merged. Having the "ability to write in English, preferably British English" only affects English articles (this is already noted in the ASC)--assuming that it was talking about writing articles, not communication. If it were about communication, then English should be be enough, that is, if the discussion was regarding an English article.

I'm thinking that requirements 1 and 3 should be removed, or remove 1 and reword 3 to be more specific, or just remove/reword 3 if 1 is still wanted.

**Comment by sr229** [comment]
There's a reason we made 1 and 3 as a requirement. For most seasoned Git users (who are mostly, developers, after all, this is *Git*Hub), its fair we have such rules well placed. It's also a learning experience for wiki contributors since:

- You can dispose the brances if you feel like there's no need for it, rather than just deleting the whole repo.

- It's all about making the proper changes, making sure master is in sync with upstream so when you make a new feature branch for a next iteration of a contribution, its more up to date.

**Comment by MegaApplePi** [comment]
I may have worded the beginning sentence a bit weirdly, I meant, "I think requirements 1 and 3 aren't being enforced." And being requirements, if they aren't enforced to be required, then they should either be removed or updated to keep them enforceable.

@sr229 Your argument for requirement 1--as you said--works well for those who already know how to use Git/GitHub, which would make sense. I do agree with what you said in the discord; master should be left alone for incoming changes and experiment with new branches. It's that enforcing this requirement would mean that the mergers should not merge pull requests that are using a master branch, which would be one pull request here-and-there-every-once-in-a-long-while. We could keep it, it's just that the mergers would then have to not merge pull requests that use the master branch. As for requirement 3, I'm not sure what your argument/suggestion is for it.

**Comment by Joehuu** [comment]
Can we move the ASC from the `helpful links` to the `requirements` as it is enforced, and we can remove the third requirement as it is self explanatory (it is written in English/no new person writes a whole new article). As for the other part (British English), it is also on the ASC.

**Comment by MegaApplePi** [comment]
@ticotaco72 Other people who only know one language--that is, not English--can still contribute by proof reading articles in their languages, or write new ones even if an English version doesn't exist (though, I would imagine that this is rare nowadays). If the person were to only do proof reading and add their corrections, do they really need to know English to do so? I wouldn't think so, but since commit messages must be in English, requirement 3 should be reworded to state that instead.
