### ISSUE TITLE
Multi-flag icons should be removed

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1948]
As countries gather, we need to make a new whole flag by editing which is hard. Also this instance... we can't divide a flag into three. Best to just add flags side by side. Need an opinion, and will make a PR nuking the images and changing their references.
![](https://puu.sh/CsJCS/315a280bb6.jpg)

**Comment by WalterToro** [comment]
I dont recall an actual new combined flag, i remember two of those on old tournament articles but nothing more, still i agree that we can do like that and just put flags side by side.
