### ISSUE TITLE
Combine/rewrite articles that describe the modding and ranking process

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#1977]
- https://osu.ppy.sh/help/wiki/Submission#the-beatmap-modding-process
- https://osu.ppy.sh/help/wiki/Submission/Beatmap_Ranking_Procedure
- https://osu.ppy.sh/help/wiki/Guides/How_To_Get_Your_Map_Ranked

should chronologically outline how a new mapper would go about the process. I think our goal should be to give a mapper all the resources they need to rank their maps (besides the actual mapping knowledge) assuming that they have no prior social connections within the community

**Comment by sr229** [comment]
+1 since they're literally the same article

**Comment by cl8n** [comment]
@pishifat is doing some of this

**Comment by cl8n** [comment]
#2615
