### ISSUE TITLE
[Proposal] Cite GitHub Learning Labs on some parts of OWCG

### ISSUE THREAD

**Issue by sr229** [ppy/osu-wiki#1988]
To better educate new contributors on the flow in GitHub, I think we can mention some courses in [GitHub Learning Labs](https://lab.github.com/) created by the GitHub team themselves.

They usually cover in detail a lot of things we also cover such as merge conflicts, a introductionary to the GitHub interface, along with the basic fundamentals of Git.

**Comment by PythonTryHard** [comment]
OWCG as in "**o**su! **W**iki **C**ontribution **G**uide" or what because we have "OWC" as "**o**su! **W**orld **C**up"

**Comment by sr229** [comment]
@PythonTryHard we have opted not to teach everything, so anything that needs to be taught in detail has to be linked from a refutable source instead. Seeing this came from GitHub themselves, its worth the citation.

**Comment by TicClick** [comment]
closing in favour of #2780
