### ISSUE TITLE
Image file name spacing should have a preferred character

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#1996]
I prefer the hyphen(`-`), since article titles already have the underscore(`_`).
![](https://puu.sh/CCJlQ/78070025f4.png)

**Comment by cl8n** [comment]
every automatically generated image in this repo uses hyphens too

might not matter though. idk

**Comment by Joehuu** [comment]
It's just for consistency.

**Comment by cl8n** [comment]
going to replace all strings of `?!|*+=<>:;"_ &^%$#{}[](),.` in filenames with hyphens (with the exception of dots for the file extension), any I should add or remove from that?

for the `__.gif` flag I will either keep that or replace with `XX.gif`

[here are results](https://gist.github.com/cl8n/bac286aa98b0d24da1e4a7d4b582829b) from `find . -name '*[\?!|\*+=<>:;"_ &^%$#\{\}\[\](),.]*.*' ! -name '*.md' -print`

**Comment by Joehuu** [comment]
Might want to change underscores first as that is the most dominant.

The flag can be kept as is, since the underscores are represented as empty characters.

**Comment by sr229** [comment]
For those who are willing to do this, you'll need Visual Studio Code's or Theia's Search and Replace

Here's a proposal regex 

```regex
[a-zA0-9]+_[a-zA0-9]+\.(gif|jpg|png|jpeg)
```

**Comment by sr229** [comment]
Following Regex is tested to work [here](https://regex101.com/r/8kBAvc/3/).

**Comment by sr229** [comment]
But yeah for consistency I suggest underscores for all files since that's how majority are formatted anyways.
