### ISSUE TITLE
Some FA tracks have a bitrate of 320kbps (unrankable)

### ISSUE THREAD

**Issue by Raidencio** [ppy/osu-wiki#2008]
As per RC, the maximum allowed bitrate is 192kbps. An example is VINXIS - Facade

**Comment by cl8n** [comment]
if the file size isn't an issue then I don't think this is a problem; it's licensed music after all

probably doesn't need an RC change either since it is content officially provided for beatmapping (?)

**Comment by Raidencio** [comment]
it still leads to unnecessary confusion among mappers and nominators, so there should be something set in stone at the end

**Comment by cl8n** [comment]
true

then @Ephemeralis , is it intentional that it is 320kbps? if so, just add a line to RC saying 320 is okay for FA tracks

**Comment by peppy** [comment]
what?

**Comment by peppy** [comment]
please fix these instead of making excuses.

**Comment by Joehuu** [comment]
@peppy can you move this to osu-web?
