### ISSUE TITLE
Missing beatmaps on the HyuN Beatmap Pack (from HyuN's FA Announcement page)

### ISSUE THREAD

**Issue by Nivalyx** [ppy/osu-wiki#2024]
When I downloaded the HyuN beatmap pack from the file linked in the FA announcement page, I realized that there are two beatmaps featured in the image but were missing from/not yet included in the pack :

- HyuN feat. JeeE - Fallen Angel (https://osu.ppy.sh/beatmapsets/891335#osu/1863209)
- HyuN - Tokyo's Starlight (https://osu.ppy.sh/beatmapsets/891712#osu/1864175)

---

Screenshot : 

![image](https://user-images.githubusercontent.com/36564236/52330044-f0e25780-2a26-11e9-91a4-6ea0cbbdfde4.png)

**Comment by Ephemeralis** [comment]
This is now about as fixed as I can get it - Starlight isn't qualified/ranked for whatever reason despite it being present in the image, so I can't really do a whole lot about that. Fallen Angel is now in both the pack and the set download.
