### ISSUE TITLE
Links in File Formats are broken

### ISSUE THREAD

**Issue by Puggingtons** [ppy/osu-wiki#2092]
In here [osu! File Formats](https://osu.ppy.sh/help/wiki/osu%21_File_Formats) the links to .osz, .osk, .osu and .osb are broken. .osr works fine though. Sites were accessed with english language selected.
Also noteworthy: .osz is accessible in the german language, but not in the english language

**Comment by notbakaneko** [comment]
pages should start reappearing (and not vanish) once they get refreshed https://github.com/ppy/osu-web/pull/4224
