### ISSUE TITLE
osu! Mapping World Cup #1 Wiki page did disappear

### ISSUE THREAD

**Issue by Imakuri** [ppy/osu-wiki#2093]
Hello I would just like to know why the wiki page of my contest did completly disappear, thanks a lot for your help !
![ss 2019-02-28 at 10 27 35](https://user-images.githubusercontent.com/46400190/53599696-1686fa80-3ba8-11e9-8b66-9fd175205de4.jpg)

**Comment by cl8n** [comment]
this is the case for a lot of pages at the moment and we're looking into the problem

**Comment by notbakaneko** [comment]
pages should start reappearing (and not vanish) once they get refreshed https://github.com/ppy/osu-web/pull/4224
