### ISSUE TITLE
Mania ranking critera rephrase because of new difficulty icons

### ISSUE THREAD

**Issue by tailsdk** [ppy/osu-wiki#2109]
So with the new icon changes a part of the ranking criteria that affects mania has become very confusing. Speceficly here "...lower than 3:30, the lowest difficulty of each included game mode cannot be harder than a Normal. Because osu!mania does not have a difficulty-specific Ranking Criteria yet, an osu!mania beatmapset's Normal difficulty is defined as a difficulty below 2.00 stars." The reason this is confusing is because mania's normal icon is no longer below 2 stars, and with the new icons that is an easy.
My suggestion for a quick fix would be to rephrase the whole sentence to "...lower than 3:30, the lowest difficulty of each included game mode (except osu!mania) cannot be harder than a Normal. Because osu!mania does not have a difficulty-specific Ranking Criteria yet, an osu!mania beatmapset's lowest difficulty must be an easy difficulty."

**Comment by Joehuu** [comment]
Can be closed if invalid.

**Comment by Joehuu** [comment]
Resolved in #2243.

**Comment by Joehuu** [comment]
Closing as resolved.
