### ISSUE TITLE
Some tag keywords on tournaments are already in the article

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#2140]
On future tournament articles, this should be applied.

**Comment by Joehuu** [comment]
@fajar13k can you apply this on your open prs?

(i.e. if `TWC 2018` is on the article, remove the tag)

You can keep tags that have no spaces (`TWC2018`) as it isn't on the article.

**Comment by fajar13k** [comment]
Will do.

**Comment by Joehuu** [comment]
Guess this issue wasn't an issue.
