### ISSUE TITLE
Create a Featured Artists article

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-wiki#2203]
should include:
- general description
- artists list
- short descriptions for artists
- official songs

**Comment by Joehuu** [comment]
https://osu.ppy.sh/beatmaps/artists already does the stuff listed. I don't get why we want to duplicate information when we already have a dedicated `osu-web` page.

**Comment by cl8n** [comment]
I don't think listing the artists/songs is necessary as they'll be changing pretty often and it's more convenient to view them on the webpage anyway

the article is useful though so you can find info about it, wiki is just a hub for anything about osu. makes it appear in site search results as well

**Comment by Joehuu** [comment]
If we're just doing `general description` now, it's best to start with it as a glossary term.

**Comment by cl8n** [comment]
sure. I think the actual article could additionally include some history and details about how people can make use of it (via Mapper's Guild)

**Comment by sr229** [comment]
I'm against this proposal since we already have a Artists page for this, and this only increases maintenance debt.

**Comment by TPGPL** [comment]
think adding Official Song and Featured Artist to Glossary should be enough
