### ISSUE TITLE
Include more information about Project Loved and the Loved category

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2209]
there are a lot of common misconceptions to make because the category has been used for 3 different things now, the last of which being Project Loved

"Loved" can probably get its own article (under Beatmaps?) with this info and then the Project Loved article in https://github.com/ppy/osu-wiki/pull/2205 should be updated as needed

**Comment by sr229** [comment]
I think we can close this off considering GH-2205 is now merged?

**Comment by cl8n** [comment]
this was opened after 2205 because I want to expand on it, 2205 only includes some basic info about project loved

**Comment by sr229** [comment]
We might dig some articles about the initial announcement of Loved soon if we want to extend more about it.
