### ISSUE TITLE
Template formatting

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2216]
when we add template support it'll have to be compatible with markdown somehow. to keep it recognizable I think we should format them similar to HTML tags, but using PHP data types

for example, a User template could be `<User id=1541323 flag=true>`. or maybe if we want to use positional arguments instead of named in some cases, something like `<Beatmapset 376878>` could work too

longer example could be something like
```
<Mappool
    nomod=[
        1933583,
        129891,
        ...
    ]
    hidden=[
        151229,
        ...
    ]
    ...
>
```

leave any suggestions here cuz I want to test some things in the near future

**Comment by cl8n** [comment]
an unrelated but probably necessary step here is the ability to easily preview these things while editing and reviewing. an instance of osu-web running with each open PR from osu-wiki should be fine, and I can set that up after getting basic template support in

**Comment by sr229** [comment]
We can probably have a auto-preview service that replicates the osu-wiki environment and gets data from a repository+branch

**Comment by cl8n** [comment]
I'll try to do that as best as I can provide, but for now don't expect anything too fancy

I'm working with the format mentioned in OP since nobody commented on it, but after some thought I realised there are going to need to be at least two main types of templates: the first being simple markdown includes/replacements, so that wiki editors can keep complicated or repetitive formatting consistent, and the second being extensions for the renderer on osu-web (what I originally opened this issue for)

I'm not sure how soon I'll be able to get either of these things working (not a very high priority for me rn) but I'll open another issue or post on discord if I have any updates
