### ISSUE TITLE
People shouldn't exist

### ISSUE THREAD

**Issue by peppy** [ppy/osu-wiki#2220]
Not sure why https://osu.ppy.sh/help/wiki/People/ exists when it's just The_team minus some.

Just redirect to The_team and call it a day?

Also consider moving inactive below user groups

**Comment by cl8n** [comment]
it's just acting as an index page for articles under People/, it shouldn't be linked to from anywhere

also I don't think it's a given that The Team includes the same listing, it just happens to be that right now all of the People are part of The Team (maybe not Community Contributors? not sure if they count)

**Comment by peppy** [comment]
At very least it shouldn't contain duplicate listing of user groups.

**Comment by cl8n** [comment]
I pointed out a nesting problem with this possible solution https://github.com/ppy/osu-wiki/pull/2481#issuecomment-529069445 earlier, but thinking about it again I'm not sure how important that is. if nobody else is bothered by it then that's probably the best way to close this issue

**Comment by MegaApplePi** [comment]
```
People
├── Community_Contributors
└── ... (other people/groups *not* part of the team)
Staff_Log
├── 2014
└── ... (other people/groups *not* part of the team)
The_Team
├── Beatmap_Nominators
└── ... (other groups that are part of the team)
```

This would be my proposal on doing it, the two index pages (People and The_Team) would link to each other. Staff_Log should be its own thing too (linked from The_Team), unless we want it to stay in People or The_Team.

**Comment by cl8n** [comment]
staff log would be separate ye

i dont think it makes sense to have two different top categories if they're obviously related, though. everything in and under the_team is about people, right?
