### ISSUE TITLE
Implementation of grouping news posts

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#2247]
Might be a way to shorten the [news directory](https://github.com/ppy/osu-wiki/tree/master/news) significantly as not many diverse news posts have been made yet.

The news directory will have folders for the type of news:
```
/news
	/osu!weekly
		/2017-06-07-osu-weekly-106.md
	/Project_Loved
		/2019-05-06-project-loved-week-of-may-5th.md
```
There can be links to previous and next iterations like osu!weekly had done, but it is done automatically.

**Comment by cl8n** [comment]
I feel like having the order of these posts implicitly defined by their file name isn't the best option... but for all the news posts currently I think it'd work. so idk . I will try this in a few weeks

**Comment by sr229** [comment]
Categorization may help us in the near future as well, so I think this directory layout may be a good start for a cleaner news layout.

**Comment by cl8n** [comment]
will add an `order` attribute to each post to help with sorting. it could also be a doubly-linked list but that's probably kinda annoying for news post writers since they have to update the last post when they make a new one

**Comment by cl8n** [comment]
ok I think I'm dumb I can just use the date for sorting. I can't imagine a case where the "next" post would be posted before the current one 🤔

**Comment by cl8n** [comment]
something to note, osu!weekly news posts have tables linking to previous/next posts within the articles that should be removed when this is done

**Comment by peppy** [comment]
The osu-web design has categorisation done via tags. Adding support will require some degree of implementation at osu-web.

**Comment by TicClick** [comment]
update: after https://github.com/ppy/osu-web/pull/9280 is merged, news posts will be grouped by years -- https://github.com/ppy/osu-wiki/pull/8027

**Comment by Joehuu** [comment]
Closing as the original issue was resolved by https://github.com/ppy/osu-wiki/pull/8027. Having the directories by year was way better than series as posts from a series can realistically reach 1000+.

I guess the series grouping can be done via tags, will track that in the search implementation: https://github.com/ppy/osu-web/issues/2305.
