### ISSUE TITLE
Compressing Files is outdated

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2268]
seems like it might be in the wrong place too, it's not clear that this is for beatmap submission

**Comment by sr229** [comment]
Just to be clear it is in its own article?

**Comment by cl8n** [comment]
this one https://osu.ppy.sh/help/wiki/Guides/Compressing_Files - reading it again I think most of it is useless today, the only important part is videos and that should be its own beatmapping guide if it's not already. there are a lot of in-depth video encoding guides on forum

**Comment by cl8n** [comment]
closing because it's now marked as outdated
