### ISSUE TITLE
State the submission size limit

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-wiki#2323]
Karoo on Discord:

pishi's recent pull request https://github.com/ppy/osu-wiki/pull/2320/files inspired me to check whether this is true, and it seems that stable allows you to upload 5MB + 9.54MB per minute. 
should this be considered the rankable limit, ie if ingame BSS submits it, it is small enough? if so, document it please, as the current ranking criteria doesn't give specific numbers.

also that number 9.54MB is due to the number being calculated with 10^6 rather than 1024^2, i would change it to 1024^2/6 = 174763 to give 5MB + 10MB per minute.

---

possibly related: #2320 #2268

**Comment by lunafreya** [comment]
I'm confused. Is the "5MB" in "5MB + 9.54MB/10MB per minute" meaning "5MB per minute for audio", or "5MB hard maximum for audio"?

**Comment by peppy** [comment]
Total filesize can be `5 + 10 * length_in_minutes`. Audio has nothing to do with it.

**Comment by lunafreya** [comment]
@peppy Or you meant to say `( 5 + 10 ) * m` where _m_ is how many minutes (PEMDAS).

**Comment by peppy** [comment]
no. i meant to say what i said.
