### ISSUE TITLE
Oversized file

### ISSUE THREAD

**Issue by nanaya** [ppy/osu-wiki#2326]
At least [this file](https://github.com/ppy/osu-wiki/blob/master/wiki/Tournaments/CIC/2018/img/podium.png) is too big. Please limit file size to less than 1MB. Maybe mention it in the README or something.

**Comment by Joehuu** [comment]
Guess this will change in the ASC. https://osu.ppy.sh/help/wiki/Article_Styling_Criteria#images
![image](https://user-images.githubusercontent.com/35318437/60233929-26ad9e80-9857-11e9-8212-9a394e24d825.png)

**Comment by nanaya** [comment]
Yeah, it should be updated to 1MB.
