### ISSUE TITLE
Score deletion/Outdated replay???

### ISSUE THREAD

**Issue by TheCoralFeef** [ppy/osu-wiki#233]
I completed a map yesterday, and the score uploaded as usual. I saved the replay to my library. Shortly after, the map requested me to update it to the latest version of itself, and after I did so, my score disappeared, and when I tried to watch the replay, i would get a notification saying something along the lines of "You do not have the beatmap this replay was made for!". I don't know how to fix this, hoping to get some help with it qwq
![2017-05-03 8](https://cloud.githubusercontent.com/assets/28401618/25716255/6ff8c7bc-30cc-11e7-848c-0e47c968fe66.png)
![2017-05-04 4](https://cloud.githubusercontent.com/assets/28401618/25716268/7d22e13e-30cc-11e7-93c5-8d970b2185cc.png)

**Comment by TPGPL** [comment]
what the fuck

**Comment by TPGPL** [comment]
use forum maybe?

**Comment by Repflez** [comment]
This is not a support forum, please use [the appropriate places for that.](https://osu.ppy.sh/forum/5)
