### ISSUE TITLE
Main Page is outdated

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2362]
there's no way to mark them as outdated so I'm opening an issue instead. at the very least, QAT needs to change to NAT, and the Project Loved team isn't listed yet

**Comment by sr229** [comment]
Was this the only missing entries?

**Comment by cl8n** [comment]
I haven't checked yet

**Comment by sr229** [comment]
I'll give this PR a shot since it might need minor updates like so, but I need to know which entries it lacks because we're trying to record quite a moving target.

**Comment by cl8n** [comment]
well that's why I opened an issue, if I knew which entries were missing at the time I would've fixed it then. I checked now and a lot of this seems unuseful since we need to reorganize a lot of articles still (mostly to do with beatmapping and modding)

for now I just fixed the things in OP
