### ISSUE TITLE
Try Crowdin on osu-wiki

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-wiki#2368]
Seems to work on this *unofficial* one: https://crowdin.com/project/osu-wiki (should be removed).

This could fix the ongoing formatting issues on translations.

**Comment by sr229** [comment]
I don't think we need Crowdin for a wiki. This is a documentation and a knowledgebase repository, not a web application repository.

**Comment by peppy** [comment]
I'm pretty sure this won't work. Crowdin is made for localising short strings, not full documents.

**Comment by sr229** [comment]
Proposing a close on this proposal. We should never revisit this because Crowdin translations is not effective for large knowledgebases like this repository, because even the Kubernetes docs do it in-GitHub for translations, not in here.
