### ISSUE TITLE
Formatting of .osu file format is not consistent

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2485]
all of the properties should be formatted like the most recent update to the article

**Comment by Joehuu** [comment]
Not consistent?

**Comment by cl8n** [comment]
yeah that's what I said

/runs

**Comment by Coppertine** [comment]
is there a list of issues that contradict from the wiki to the actual format?

**Comment by cl8n** [comment]
the problems are mostly (all?) just in the styling of the page. the information looks correct to me
