### ISSUE TITLE
List of outdated articles and missing translations

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2486]
select your language on **[the osu-wiki-status website](https://clayton.cc/osu-wiki-status/en)**, it tells you articles marked with `outdated` or `needs_cleanup`, and missing translations

some English articles *shouldn't* be translated, and need to be updated in English first:

- Articles marked with `outdated` (this is just for en.md, if the translation has `outdated` that's okay)
- Articles marked with `needs_cleanup`
- Articles that seem to be written poorly or contain misleading info. Message in `#osu-wiki` if you aren't sure about this one

the "Missing articles" sections on osu-wiki-status also omit contests, tournaments, and staff log. you can translate them if you want but they're very low priority. staff log is also set to be deleted, as it'll be replaced with an equivalent feature on the osu! website. there may be some other articles omitted by me, I'm not keeping this issue up-to-date.

**Comment by Akylzhan** [comment]
@cl8n Can I translate Missing Translations to Russian?

**Comment by cl8n** [comment]
go for it, just try to avoid articles that haven't been updated in a long time because we might revise the English versions soon

**Comment by GalaxyOsu** [comment]
@cl8n I would like to contribute to the wiki, editing images, changing some info and translating pages

**Comment by TPGPL** [comment]
@GalaxyOsu You are free to start contributing whenever you want. Here's the [contribution guide](https://osu.ppy.sh/help/wiki/osu%21_wiki_Contribution_Guide) if you need more information on how to contribute.

**Comment by DoryanR** [comment]
@cl8n I was wondering if it was possible to have a specific category for articles that have the `no_native_review` tag, as this would be useful to know which ones have not had any reviews, and to look at them for potential mistakes.

**Comment by cl8n** [comment]
added

**Comment by Soetch** [comment]
I'll translate the french missing translations.

**Comment by cl8n** [comment]
some outdated info here and we've since added links to this website elsewhere, going to close and unpin this.
