### ISSUE TITLE
Add a list of users with titles (that aren't part of major groups)

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2523]
@dorothy3242 said she wants to make a wiki version of the "Title List" dropdown [here](https://osu.ppy.sh/community/forums/topics/897590)

**Comment by cl8n** [comment]
@peppy can we get a db dump for this, `user_id` & `rank_title` for users with a `rank_special`!=0 rank

**Comment by peppy** [comment]
https://gist.github.com/peppy/e20b4c50b28867399c28effd8f32c70e

**Comment by cl8n** [comment]
perfect, thanks! :tada:
