### ISSUE TITLE
[Proposal] Shared images needs to be a submodule

### ISSUE THREAD

**Issue by sr229** [ppy/osu-wiki#255]
The main reason for this proposal is because the images are too large for those who have very low data cap. Submoduling allows the repo's size to be reduced

**Comment by kj415j45** [comment]
A possible folder struct: (I guess)
```
/                               # osu-wiki repo
--wiki/
----articles/
------*.md
--img/                      # use submodule(osu-wiki_img(?)) 
----articles/              # use the same folder name with /wiki/atricles
------*.jpg
--CONTRIBUTING.md
--LICENSE.md
--README.md
```

**Comment by TPGPL** [comment]
We wouldnt have to sort images then, right?

**Comment by sr229** [comment]
@TPGPL yes, at this point.

**Comment by sr229** [comment]
Resource about Git Submodules 
[Article](https://www.atlassian.com/blog/git/git-submodules-workflows-tips)

**Comment by peppy** [comment]
Submodules are a pain to deal with and also increase the bar of entry for editing the wiki. We may want to consider other options.

**Comment by sr229** [comment]
@peppy if you got any other solutions, please bring it up on the table :wink:

**Comment by Repflez** [comment]
Is [Git LFS](https://git-lfs.github.com/) an option to look at?

**Comment by sr229** [comment]
@Repflez seems like it since we're about to hit the maximum size limit for a repository

**Comment by sr229** [comment]
closing since we're gonna consider more options other than submoduling.
