### ISSUE TITLE
Difficulties/ pages are probably not useful

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2579]
at least in their current state. they're basically mapping guides and the same info can be found in RC (but it's more updated/accurate there)

**Comment by cl8n** [comment]
the Difficulties article itself may still be useful, but every article under that is just different wording of the RCs. is anyone against deleting those? the main difficulties page would have some references to RC & difficulty naming in their place

**Comment by dorothy3242** [comment]
I agree with this, the sub pages used to be useful before the ranking criteria fleshed out difficulty guidelines, but now it's redundant and outdated.
