### ISSUE TITLE
Use sentence case for article titles and directory names

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2580]
that'd make more sense since the other headers already do this

**Comment by Joehuu** [comment]
ASC (typo lol):
> Titles headings must use title case and must not contain formatting, links, or images.

Are you suggesting to change this?

**Comment by cl8n** [comment]
if "Titles headings" means h1, yeah

**Comment by cl8n** [comment]
@Joehuu @MegaApplePi what are your opinions on this, I don't want to waste time on it if u dont agree

**Comment by Joehuu** [comment]
Yeah, I agree to it. It'll separate the proper nouns from the common nouns (which may be hard when editing as I saw (ex. `Featured Artist` and `Featured artist`) being used in both ways). Wikipedia also does this.

**Comment by MegaApplePi** [comment]
Huh, I didn't realize that Wikipedia used sentence case for their titles. I think it will be fine to switch over to sentence case.

**Comment by MegaApplePi** [comment]
@cl8n Are you going to update the ASC on this? I could make the change in #2799, but wasn't sure if this issue was covering the updating of the ASC and actually making the fixes.

**Comment by cl8n** [comment]
the part I've assigned to myself is applying the change, you can do ASC part if you want

**Comment by cl8n** [comment]
moved to #2275
