### ISSUE TITLE
Promote Mappers' Guild contents on the osu! website newspost

### ISSUE THREAD

**Issue by Pachiru** [ppy/osu-wiki#2592]
By that, I mean when a mappers' guild quest (i.e James Landino mini-pack) is done. 

I think it could be a good way to promote mappers guild work and motivate mappers to make more official osu! content, cause actually no one is informed when X quest is finish and all the sets are ranked. I also think that some artists would be happy to know that their content have been used to produce more in-game content, which newspost could be a good way to inform them too.
 
Also, I think it would give more diversity in newspost content, since actually it's mostly just "Project Loved, new Featured Artist, sometimes arts contests/World Cups".

_(I posted it here since that's where newspost PR are made, sorry if it's in the wrong place)_

**Comment by cl8n** [comment]
[7:32 AM] JBHyperion: even if there was a newspost once a month or so announcing "hey these new packs are available: x y z, go check them out, here is a quick summary/sample of what's available"
[7:32 AM] JBHyperion: that would be pretty neat

seems like a better idea. posts for every quest would clutter the news listing and not serve much of a purpose
