### ISSUE TITLE
Update Welcome and Main Page

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2606]
the main page is live with the new format, and most of Welcome can be replaced by it. the main page just needs a small introduction to osu! and descriptions for each major category, then we can redirect welcome --> main_page

**Comment by peppy** [comment]
Here's what the welcome page on the old site used to include. Note that a lot of these are outdated, but the general feel of them still stands. It should be aimed at new players to help them jump into playing the game

https://gist.github.com/peppy/a387c8fc05da0188fd5d57e757298c01

**Comment by sr229** [comment]
How do we go around re-implementing this? Sounds like web have to do some parts as well.

**Comment by cl8n** [comment]
if it's just text at the beginning and within each box, it looks like it'll work as-is. whoever closes this issue should be testing (or asking someone to test for them) just in case, though.

**Comment by sr229** [comment]
I'll put it at my todo for Monday, I can port what was in the snapshot HTML peppy sent.

**Comment by sr229** [comment]
My strategy is to condense `welcome.md` into something similar to @peppy's gist. This should remove `welcome.md`. Might need to redirect to index.
