### ISSUE TITLE
Creating directory for Beginners Taiko Tournament

### ISSUE THREAD

**Issue by FlamingRok** [ppy/osu-wiki#261]
For the ease of locating the Beginners Taiko Tournament on a separate page for the future, similar to the osu! Tag Team Tournament, I request making a directory for this tournament. Inside the directory at the moment will simply be the images needed for the tournament and the actual contents of the page itself through the Markdown file. For the future, I wish to document the future years of the Beginners Taiko Tournament, similar to how the world cup series is documented, but if this isn't ideal, I completely understand the possible reasons as to why.

Thank you,
FlamingRok

**Comment by RaikireHiuduo** [comment]
sure.

**Comment by WalterToro** [comment]
Closing issue, looking at dates this is related to the time that badge approved tournaments were the only ones to get an article, now we dont have this issue so anyone can create that file/folder.
