### ISSUE TITLE
Should article titles depend on their subtitle?

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2617]
random example: /wiki/Ranking_Criteria/osu!catch
should this article's title be "osu!catch" or "osu!catch Ranking Criteria"?

subtitles (aka parent articles' titles) are shown on the website, so in this case it doesn't make much of a difference. but the subtitle doesn't help identify the article if the tree is a bit taller (consider /wiki/Ranking_Criteria/osu!/Scaling_BPM). imo it just feels weird regardless for an article title to not be able to stand on its own

**Comment by Joehuu** [comment]
Can we use breadcrumbs to resolve that?
i.e.
![](https://puu.sh/Em8V5/b9786dcd86.png)

We can remove `on the Ranking Criteria` with this.

**Comment by cl8n** [comment]
that would address the taller trees thing, not the general concern tho 

(and yes I will do that on osu web regardless of this issue cuz it'd be nice )

**Comment by cl8n** [comment]
the website design has since changed so we should look into this again. I still think a title should be able to stand on its own, and it'd make more sense following https://github.com/ppy/osu-web/issues/5529

if I'm understanding this correctly it seems like search/autocomplete results would be easier to differentiate as well https://discordapp.com/channels/188630481301012481/218677502141399041/672749739959123988

**Comment by peppy** [comment]
titles should definitely stand on their own. in the example case, including Ranking Criteria is preferred.
