### ISSUE TITLE
RFC: Enforce mandatory parity with English articles for localisations

### ISSUE THREAD

**Issue by sr229** [ppy/osu-wiki#2634]
Prior to GH-2626, there has been conflict about content parity with some localized articles within this PR. So I'm proposing in the ASC to add a "Mandatory content parity" clause to prevent localization teams and contributors to deviate from the base article (English articles are the *de facto* base articles).

Reasons for this is because we want to enforce better consistency in translations, at the sacrifice of lesser flexibility.

**Comment by cl8n** [comment]
it shouldn't "sacrifice flexibility", just let translators know that if they need to change the info presented in the article they should do one of
- ask someone first if they aren't sure
- change en.md as well
- leave a comment on the PR about it so someone else can review and/or update en.md

IMO any changes in tone/style/language are okay, even moving around sentences/paragraphs where necessary, as long as it's the translator's best effort and they think it works well. the reality is we don't have the resources to get more strict than that anyway (except for maybe French/Russian rn, but that's still up to each set of reviewers and not rly enforceable)

**Comment by sr229** [comment]
I think as long as we can mandate it, the reviewers should be aware and notified of the new changes.

**Comment by peppy** [comment]
It should be as close as possible, agree.

**Comment by sr229** [comment]
Putting this as my TODO since I want this RFC to be in the constitution to prevent further inconsistencies, the less time we get this sorted the better since the wiki is a large project by its own.
