### ISSUE TITLE
Article Style Guide link in CONTRIBUTING.md leads to a blank page

### ISSUE THREAD

**Issue by Shadowtail117** [ppy/osu-wiki#267]
The link is supposed to take you to https://new.ppy.sh/wiki/Article_Style_Guide, but it redirects instead to the old https://osu.ppy.sh/wiki/Article_Style_Guide, which has no text. In fact, any links to https://new.ppy.sh redirect to their old counterparts. 
I'm pretty sure that the new website had the style guide somewhere, so if it's still accessible, then we can port it over to its redirect, or we could make it not redirect (though there's probably a reason I'm not aware of as to why it does), or we could re-create the style guide.

**Comment by EpicSupermind** [comment]
i think the new address is https://osu.ppy.sh/help/wiki/Article_Style_Guide
Probably an error with the addressed by merging the websites.
Anyway, most links aren't supposed to link to new.ppy.sh, as it's just for testing designs on the old website.
