### ISSUE TITLE
Mark outdated, incomplete, unnecessary, etc. English articles

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2681]
it's well-known to people familiar with the wiki that half of it is in need of updates, but we still haven't properly marked which articles those are. at some point we should make a full pass with the `outdated` tag and open more specific follow-up issues that we can milestone

https://github.com/cl8n/osu-wiki-log-outdated should be updated to ignore outdated articles in the "missing translations" section too

**Comment by sr229** [comment]
I'm making a educated guess about 30% of the translations might be outdated since the English versions have more churn vs these translations.

**Comment by cl8n** [comment]
high priority because translators need to know if articles are worth their time to translate

**Comment by cl8n** [comment]
for reference there is now a `needs_cleanup` attribute available that displays a message like `outdated` does:

> This page does not meet the standards of the osu! wiki and needs to be cleaned up or rewritten. If you are able to help out, please consider updating the article!
