### ISSUE TITLE
Change the date and time format

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-wiki#2708]
ISO 8601 is the current standard but may be difficult to read at first glance. Unless someone else has a better format, we can follow what Wikipedia does:

> Full dates are formatted 10 June 1921 or June 10, 1921; or where the year is omitted, use 10 June or June 10.

<https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style#Dates>

other references for how Wikipedia does its time and dates:

- <https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Dates_and_numbers#Dates,_months,_and_years>
- <https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Dates_and_numbers#Time_of_day>
- <https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Dates_and_numbers#timezones>

**Comment by cl8n** [comment]
all of the points there seem fine to me

**Comment by cl8n** [comment]
> dates in the *text* of any one article [...]

fwiw our definition of "text" should be anywhere with full phrases or sentences, because things like tournament schedules seem to be fine with ISO 8601. for this PR just change ASC, we can start following the new rule as we go
