### ISSUE TITLE
Rephrase the use of inline and reference style links in the ASC

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-wiki#2715]
TPGPL wants to limit the use of reference-style links for links and images that are not used multiple times throughout an article and flags.

---

For links, the ASC says:

> Links may use either the reference or inline style. Use either appropriately.

And for images:
> Like the links, use either the reference or inline style. Use either appropriately.

---

We can change it to say something like:

`Links must use the inline style. However, if it is being linked to more than 2 times, the link may use reference style.`

`Images must use the inline style. However, if it is being linked to more than 2 times, the link may use reference style. Except for flags, which must use reference style.`

Any thoughts on this?

**Comment by sr229** [comment]
I think its a rather good change considering redundancy can reduce code view clarity.

**Comment by cl8n** [comment]
flags don't have any reason for a special exception
it'd make more sense if you covered all inline images/icons, but I don't think that's necessary either

"Links/Images should use the inline style if they are only referenced once." ? also explain what inline style / reference style means if that's not done already
