### ISSUE TITLE
Skinning Elements Page does not have HD Sizes

### ISSUE THREAD

**Issue by circleen** [ppy/osu-wiki#2756]
most osu! players have an HD resolution, and most skinners use both HD and SD files.

**Comment by cl8n** [comment]
if they're all exactly twice the size then say that instead of listing them all

**Comment by MegaApplePi** [comment]
HD sizes are SD doubled. This is noted in the [Skinning FAQ](https://osu.ppy.sh/help/wiki/Skinning/FAQ#hd-images). The additional information will be redundant so just note the exceptions instead.
