### ISSUE TITLE
Figure out a way to redirect sections

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2757]
if we rename a header from "Section" to "New Section", we'd want the URL fragment #section to "redirect" to #new-section

this means for every page & locale, there needs to be a list of anchor changes

**Comment by MegaApplePi** [comment]
I [opened an issue on osu-web](https://github.com/ppy/osu-web/issues/1566) 2 years ago relating to this issue. My proposal would be to add additional markup for the headers so we can assign an ID to them so they can always be linked to consistently for each locale.

**Comment by cl8n** [comment]
would also solve the anchor problem on headers with the same name

**Comment by TicClick** [comment]
now that custom identifiers are added and we have initial regulations around it (#5987), should we require a custom identifier for every heading? that sounds like the only way to keep links alive

**Comment by TicClick** [comment]
on a second thought, this is likely a non-issue and may be closed. within a single article, headers rarely, if ever, change, and even if they do, it's still possible to figure out where you should have been redirected to (provided that the party that gave you the link included at least some context for it)

all in all, we have a tool for taming the obnoxiously long headers, and I think that should suffice. please reopen if you disagree -- I may be wrong
