### ISSUE TITLE
French Wiki Completion

### ISSUE THREAD

**Issue by RedNesto** [ppy/osu-wiki#279]
# Wiki Completion
## Articles
- [x] About
- [ ] Accuracy -- Waiting Merge
- [ ] ~~_Achievements_~~ Medals -- Waiting Review
   - [x] Beatmap Packs
- [ ] Announcements -- WIP by @RedNesto
   - [ ] Archive -- WIP by @RedNesto
   - [ ] Contests -- WIP by @RedNesto
      - [ ] Monthly_Fanart_Contest -- WIP by @RedNesto
   - [ ] Showcases -- WIP by @RedNesto
   - [x] osu!academy
   - [x] osu!talk
- [ ] Article Style Guide -- WIP by @tom-arrow 
- [ ] BBCode
- [ ] BanchoBot -- Must be redone -- WIP (RedNesto)
- [ ] Beatmap Editor -- Must be completed
   - [ ] AiMod
   - [ ] Beat Snap Divisor --Must be redone
   - [ ] Compose
   - [ ] Design -- Must be redone
   - [ ] Distance Snap -- Must be redone
   - [ ] Kiai Time -- Must be reviewed
   - [ ] Menu
   - [ ] SB Load
   - [ ] Slider
   - [ ] Song Setup -- Must be reviewed
   - [ ] Timelines
   - [ ] Timing -- Must be redone
- [ ] Beatmap Editor Guides
   - [ ] Adding Custom Hit Sounds
   - [ ] Audio Editing -- Must be redone
   - [ ] Basic MP3 Modifications
   - [ ] Changing Title Text
   - [ ] Changing the Map's Artist or Title
   - [ ] Compressing Beatmap Files
   - [ ] Compressing Videos
   - [ ] Cropping with Complex Backgrounds
   - [ ] Cropping with Simple Backgrounds
   - [ ] Custom Hit Sound Library
   - [ ] Custom Sample Overrides -- Must be redone
   - [ ] Getting Songs frosm Video Games
   - [ ] How to time songs
   - [ ] Making Properly Centered Spinners
   - [ ] Music Theory
   - [ ] Setting the Offset on the Correct Beat
   - [ ] Videos from Youtube
   - [ ] osu!mania Mapping Guide
- [ ] Beatmap Forum
- [ ] Beatmapping -- Must be redone when english is finished
- [ ] Beatmaps -- Must be redone when english is finished
- [ ] Beginner
- [ ] Best Of
   - [ ] 2012
- [ ] Chat Console -- Must be reviewed
- [ ] Difficulties 
   - [ ] osu!
      - [ ] Easy -- Must be completed
      - [ ] Normal -- Must be redone
      - [ ] Hard -- Must be completed
      - [ ] Insane -- Must be completed
      - [x] Expert
   - [ ] osu!taiko
      - [ ] Kantan
      - [ ] Futsuu
      - [ ] Muzukashii
      - [ ] Oni
      - [ ] Ura Oni
- [ ] Do you really want to ask peppy -- Waiting for review
- [ ] Game Modes -- Waiting for Review
   - [ ] osu!
      - [ ] v1
   - [ ] osu!catch
      - [ ] v1
   - [ ] osu!taiko
      - [ ] v1
   - [ ] osu!mania -- Waiting for Review
      - [ ] v1
   - [ ] External Ports
      - [ ] opsu!
      - [ ] osu!droid
      - [ ] osu!stream
      - [ ] osu!wp
      - [ ] T-Aiko!
         - [ ] Interface
         - [ ] v1
- [ ] FAQ -- Must be completed
- [ ] Game Modifiers -- Must be redone when english is finished
   - [ ] Summary -- Must be redone when english is finished
- [ ] Glossary
- [ ] Help Center -- WIP by @RedNesto
- [ ] History of osu!
   - [ ] 1 -- Must be redone when english is finished
   - [ ] 2
   - [ ] 3
   - [ ] 4
   - [ ] 5
   - [ ] 6
   - [ ] The Future
   - [ ] osu!wiki
   - [ ] Release b335
- [ ] Hit Objects -- Must be reviewed
- [ ] How You Can Help!
- [ ] Installation -- Must be redone
- [ ] Interface -- Must be redone when english is finished
- [ ] Internet Relay Chat -- Must be redone when english is finished
- [ ] Legal
   - [ ] TOS
   - [ ] Copyright
- [ ] List of Guides -- Must be completed
   - [ ] GL Support Issues -- Must be redone
   - [ ] General tips and tricks on skill improvement
   - [ ] How to Play Mania
   - [ ] How to Run osu! on Your Mac without using Boot Camp
   - [ ] How to use the Offset Wizard
   - [ ] Recording osu!
   - [ ] Searching and Downloading Beatmaps
   - [ ] Tablet purchase
- [ ] Live streaming osu!
- [ ] Mapping Techniques
   - [ ] Basics
   - [ ] Formations
   - [ ] Jumps
   - [ ] Making Good Sliders
   - [ ] Rhythm
   - [ ] Sliders
   - [ ] Spinners
   - [ ] Unrankable
- [x] Mascots
   - [x] Gallery
- [ ] Modding -- Must be redone when english is finished
- [ ] Modding Guides
   - [ ] Collab Information
   - [ ] Getting Your Map Modded -- Must be redone
   - [ ] How To Get Your Map Ranked -- Must be completed
   - [ ] How to not Embarrass Yourself in the Modding Queues Subforum
   - [ ] How to not Embarrass Yourself in the Projects Subforum
   - [ ] Modding and Mapping
   - [ ] Starting a Beatmap Project
- [ ] Multi
- [ ] Official Songs
- [ ] Options -- Must be redone
   - [ ] Keyboard Bindings -- Must be redone
   - [ ] Offset Wizard
- [x] osu! File Formats
   - [ ] Db
   - [ ] Osb -- Must be redone
   - [ ] Osk -- Must be redone
   - [ ] Osr -- Must be completed
   - [ ] Osu -- Must be completed
   - [ ] Osz -- Must be redone
- [ ] osu! Program Files -- Must be completed
   - [ ] User_configuration_file -- Must be redone when english is finished
- [ ] osu!store -- Must be redone when english is finished
- [ ] osu!supporter -- Must be redone when english is finished
- [ ] osu!tourney -- Must be completed
- [ ] osu!wiki contribution guide -- WIP by @RedNesto
- [ ] People
   - [ ] Beatmap Nomination Group -- Must be completed
   - [ ] Community Contributors -- Must be completed
   - [ ] Global Moderation Team -- Must be reviewed
   - [x] Language Moderators
   - [ ] Osu!_Alumni -- Must be completed
   - [x] Quality Assurance Team
   - [x] Support Team
   - [x] The Team
- [ ] Performance Points -- Must be redone when english is finished
   - [ ] ppv1 -- Must be redone when english is finished
- [ ] Play Styles -- Must be completed
- [ ] Ranking Criteria
   - [ ] osu! -- Must be completed
   - [ ] osu!catch -- Must be redone
   - [ ] osu!mania -- Must be redone
   - [ ] osu!taiko -- Must be redone
- [ ] Registration -- Must be redone when english is finished
- [ ] Replay
- [ ] Reporting Bad Behaviour
   - [ ] Handling Cheating -- Must be redone when english is finished
- [ ] Rules -- Waiting Merge
  - [x] Short
- [ ] Score
   - [ ] ScoreV1
- [ ] Shortcut Key Reference -- Must be redone when english is finished
- [ ] Skinning
   - [ ] Interface
   - [ ] Skin.ini
   - [ ] Sounds
   - [ ] Tutorial
      - [ ] Interface
      - [ ] Sounds
      - [ ] osu!
      - [ ] osu!catch
      - [ ] osu!mania
      - [ ] osu!taiko
   - [ ] osu!
   - [ ] osu!catch
   - [ ] osu!mania
   - [ ] osu!taiko
- [ ] Storyboard Scripting
   - [ ] Audio
   - [ ] Cheat Sheet
   - [ ] Commands
   - [ ] Compound Commands
   - [ ] General Rules
   - [ ] Miscellaneous
   - [ ] Objects
   - [ ] Shorthand
   - [ ] Variables
   - [ ] osu! File Toggles
- [ ] Storyboarding
- [x] Storyboards
   - [ ] Maps
- [ ] Submission
   - [ ] Beatmap Ranking Procedure -- Must be completed
- [ ] Tools
   - [ ] AiBat
   - [ ] SGL Tool
   - [ ] osu!MapDownloader
- [ ] Tournament Drawings
- [ ] Tournaments
   - [ ] OWC
      - [ ] 1
      - [ ] 2
      - [x] 2013
      - [x] 2014
      - [ ] 2015
   - [ ] CWC
      - [ ] 2014
      - [ ] 2015
      - [ ] 2016
      - [ ] 2017
   - [ ] MWC
      - [ ] 2014
      - [ ] 2015
      - [ ] 2016
         - [ ] 4K
         - [ ] 7K
   - [ ] TWC
      - [ ] 2011
      - [ ] 2014
      - [ ] 2015
      - [ ] 2016
      - [ ] 2017
   - [ ] Countries that participated in osu! tournaments
   - [ ] osu! Tag Team Multiplayer Tournament
- [ ] Twitter -- Waiting merge
- [x] Welcome -- Rework waiting merge

**Comment by tom-arrow** [comment]
I'm going to do the _Article Style Guide_
