### ISSUE TITLE
Expand the `Community/Forum/Off-Topic` stub

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#2804]
they're pretty unique among the forums and have interesting history worth writing about. if anyone would be willing to put a lot of effort into it, (most of) the article could be written as if it were in-universe with the story posts

from https://github.com/ppy/osu-wiki/pull/2655#issuecomment-539066342

**Comment by Gamingzone123** [comment]
Stub written in #6454

**Comment by Walavouchey** [comment]
@TicClick should this be closed or is this still an @abraker95 waiting room?

**Comment by TicClick** [comment]
as of right now, it's a stub which still needs to be expanded. I prefer keeping the issue open

**Comment by abraker95** [comment]
> @TicClick should this be closed or is this still an @abraker95 waiting room?

Still a waiting room. Will take care of it sometime February.
