### ISSUE TITLE
Incorrect OD values in overall difficulty chart

### ISSUE THREAD

**Issue by sometimeszzzzzzz** [ppy/osu-wiki#2908]
On the OD chart in https://osu.ppy.sh/help/wiki/Beatmap_Editor/Song_Setup#overall-difficulty, DT (and probably HT too) OD values are incorrect.
I tested some maps using osutools performance calculator and the values were different.
<img width="344" alt="od incorrect" src="https://user-images.githubusercontent.com/52870410/70368440-66ea6180-1878-11ea-92e8-740a0bb39ea4.PNG">
It appears that the wrong/old? formula was used to calculate OD for the chart.

edit: it appears that chart is starting with incorrect hit window for OD 0, it should be 80 not 79.5

**Comment by cl8n** [comment]
the table's time values are based on what osu-stable shows, which are 0.5 less than the actual OD spec (probably to account for the game rounding to the nearest ms)

Song Setup refers to the stable client so this will stay for now
