### ISSUE TITLE
Merge request dump point

### ISSUE THREAD

**Issue by RaikireHiuduo** [ppy/osu-wiki#301]
Dump your merge requests here as comment.
After it is merged, please delete the PR numbers.

#297 (External_Ports index directory fix)

**Comment by kj415j45** [comment]
I think we can let every contributors leave their working PR here.so you don't need to list and check them all
just use `GFM Tasks`:
Unchecked when working
Checked when finished
Delete them when merged

Here's my PR lists:
- [x] #282 Minor fix for zh-*
- [x] #304 [CMT_4K][2017] Update

**Comment by Shadowtail117** [comment]
Here's mine: 

- [ ] #294

**Comment by RaikireHiuduo** [comment]
Closing since agreement has been made in Discord.
