### ISSUE TITLE
Old syntax for images

### ISSUE THREAD

**Issue by DoryanR** [ppy/osu-wiki#3124]
On some articles, I've noticed that there is what looks like old syntax to display images, it looks like this most of the time: 

`<img src="Hitcircles.jpg" title="Hitcircles.jpg" alt="Hitcircles.jpg" width="400" height="300" />`

The problem is that some images are invalid and therefore not displayed, in my editor and in the website.

I wish I could fix that, but I don't really know much about this.

**Comment by cl8n** [comment]
will take a look into this later today
