### ISSUE TITLE
new BN page documenting evaluations of BNs

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-wiki#3135]
information about evaluations of current beatmap nominators, not application evaluations.

- how evaluations are done
- activity guidelines that are looked at to determine if a member's activity is acceptable or needs a warning **FELLOW NATS WE NEED THIS INFORMATION TO EXIST**
- rough guidelines of what nat consider in doing evaluations
- outcomes of different issues: what nat do if activity is poor, proficiency is poor, or attitude is poor. etc.
- how evaluating new members on probation is different from any other member (activity requirement is generally higher in this case to get enough information to make an informed decision)

I originally tried shoving this in the general info for BNs article, but then realized it probably should be its own article. 

I'm working on this

**Comment by cl8n** [comment]
@dorothy3242

**Comment by cl8n** [comment]
@dorothy3242 @dorothy3242 @dorothy3242 (should I ask other ppl to help here )

**Comment by TicClick** [comment]
passi**n**g a w**o**rd: the article is written **f**or the most part (but not **f**inished **y**et)
