### ISSUE TITLE
semi-regular news posts about NAT meetings and possibly other mapping world happenings

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#3138]
would be a very good complement to #2981 , as discussed in `#modding`

so... basically something like the QAT Gazette but more focused on the decisions made in meetings

**Comment by JBHyperion** [comment]
In the earlier days of the tumblr blog, the QAT Gazette was roughly equal parts "what happened in meetings and what are we (the then-QAT) going to do going forward", and a variety of informational / opinion pieces from members on a topic of interest, e.g. "How to make cool Easy difficulties" or "Observations from the Best of 201X / Community Choice." I think these all got ported to the wiki over time, but in case they didn't, the site still exists here: https://osuqat.tumblr.com/archive

I think here you're more specifically trying to drill down into the NAT meeting developments, but I noticed https://github.com/ppy/osu-wiki/issues/2433 whilst flicking through the list of open Issues and felt like some of the old QAT Gazette ideas (and by extension, some of the stuff you want to do here) might also tick that box.
