### ISSUE TITLE
Add Article Stubs (Gameplay)

### ISSUE THREAD

**Issue by Loctav** [ppy/osu-wiki#3149]
See the main issue https://github.com/ppy/osu-wiki/issues/3143
See the project: https://github.com/ppy/osu-wiki/projects/3

Here you find all article stubs that need to be created. Some articles might already exist. Some articles can be deemed unnecessary as singular article and be summed up into a bigger article. 

Many of these singular topics are included as subset in some articles already or information is scattered around multiple articles. These articles might need to be split up into multiple ones and information must be pulled together into one common article then (e.g. https://github.com/ppy/osu-wiki/tree/master/wiki/Glossary)

Each article should only contain information of one topic. 

You can claim articles beforehand. Just comment here.

--- 
- [x] Accuracy #3153
- [x] Drain TIme #3153
- [x] Play Time #3153
- [x] Spectating #3153
---
- [x] Notelock
- [x] Double tapping #3713
- [x] Slider break #3868
- (other community terms that are commonly used)
  - [x] Alternating #3713
  - [x] Hybrid #3713
  - [x] Single Tapping #3713
  - [x] Tapx #3713
  - [x] Drag #3765
  - [x] Hover #3765
--- 
- [x] **Game Mode**
- [x] osu!
- [x] osu!taiko
- [x] osu!catch
- [x] osu!mania
---
- [x] **Input Device** #3411
- [x] Mouse #3411
- [x] Keyboard #3411
- [x] Touch Device #3411
- [x] Graphic Tablet #3411
  - [x] Tablet Cover #3868
- [x] ~~Kinect~~ (see https://github.com/ppy/osu-wiki/issues/3149#issuecomment-653372100)
- [x] Wiimote #3411
- [x] Drum Controller #3411
- [x] Dance Pad #3411
- [x] Bemani Controller #3411
---
- [x] **Multiplayer** https://osu.ppy.sh/wiki/en/Gameplay/Multiplayer
- [x] Lobby https://osu.ppy.sh/wiki/en/Gameplay/Multiplayer
- [x] Match History https://osu.ppy.sh/wiki/en/Gameplay/Multiplayer
- [x] Multiplayer Matches https://osu.ppy.sh/wiki/en/Gameplay/Multiplayer
---
- [x] Mind block #3868
- [x] Fingerlock #3868

**Comment by Pennek** [comment]
I'll start with a few: Accuracy, Drain Time, Play Time, Spectating

**Comment by Endaris** [comment]
I'm going for all articles in the Multiplayer section.

**Comment by paper-toaster** [comment]
I can create stubs for Double Tapping, Single-Tapping, Alternating, and Tapx

**Comment by paper-toaster** [comment]
I'm currently working on Game Modifiers it's /Summary which includes creating stubs for all the seperate mods.

**Comment by penguin2233** [comment]
input device is done but no kinect because it is not viable in osu also no information on it

**Comment by paper-toaster** [comment]
I'm pretty sure that the game modes stubs have already been created. They just need cleanup afaik.

I'll prob get around to cleaning them up soon

**Comment by paper-toaster** [comment]
I'm also planning on creating a few more:
- Notelock
- Slider break
- FreeMod (which is being done in #3809 
- Tablet cover
- Fingerlock

**Comment by Gamingzone123** [comment]
multiplayer has a stub called "multi", needs to be updated though

**Comment by Walavouchey** [comment]
The remaining multiplayer points are covered by https://github.com/ppy/osu-wiki/blob/master/wiki/Game_modifier/en.md

I noticed that FreeMod didn't get a stub or explanation in the linked pr, but shouldn't it rather be explained in `Game_modifier` or be in a separate place that also explains other tournament terms?

**Comment by cl8n** [comment]
both sound good, freemod is definitely more about multiplayer and tournament play, but a quick mention in game modifier wouldn't hurt

**Comment by Walavouchey** [comment]
will split into a separate issue

closing since all tasks are complete
