### ISSUE TITLE
Add Article Stubs (Community)

### ISSUE THREAD

**Issue by Loctav** [ppy/osu-wiki#3150]
See the main issue https://github.com/ppy/osu-wiki/issues/3143
See the project: https://github.com/ppy/osu-wiki/projects/3

Here you find all article stubs that need to be created. Some articles might already exist. Some articles can be deemed unnecessary as singular article and be summed up into a bigger article. 

Many of these singular topics are included as subset in some articles already or information is scattered around multiple articles. These articles might need to be split up into multiple ones and information must be pulled together into one common article then (e.g. https://github.com/ppy/osu-wiki/tree/master/wiki/Glossary)

Each article should only contain information of one topic. 

You can claim articles beforehand. Just comment here.

- [x] osu!api
- [x] osu!dev Discord #3400
- [x] osu!team
- [x] Global Moderation Team
- [x] ~~ChatOps~~ ↓
- [x] Language Surveillance Division https://github.com/ppy/osu-wiki/pull/6059
- [x] osu! Alumni
- [x] Live Streaming
- [x] User Titles
- [x] Community Contributors
---
- [x] **Chat** https://osu.ppy.sh/wiki/en/Client/Interface/Chat_console
- [x] Internet Relay Chat
---
- [x] **osu! forums** #6454
- [x] Forum Thread ^
- [x] Forum Post ^

**Comment by Parapass** [comment]
Can I claim the Live Streaming stub?

**Comment by Walavouchey** [comment]
chat is covered by [`Client/Chat_console`](https://osu.ppy.sh/wiki/en/Client/Interface/Chat_console)

**Comment by Walavouchey** [comment]
closing because all tasks are completed
