### ISSUE TITLE
Screenshot of Achieving a Medal

### ISSUE THREAD

**Issue by Shadowtail117** [ppy/osu-wiki#318]
Once the animation finishes, take a screenshot; don't click as it will end the animation.
This is needed for the Interface article (and perhaps some others, you never know).

**Comment by RaikireHiuduo** [comment]
This?

![screenshot991](https://cloud.githubusercontent.com/assets/24448073/26774753/595d25ba-4a04-11e7-8883-1c9e4653245d.jpg)

**Comment by Shadowtail117** [comment]
Yeah, that'll work! Thank you!
