### ISSUE TITLE
Add new crown icons

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-wiki#3189]
![image](https://user-images.githubusercontent.com/19843905/74090284-b718b680-4aa9-11ea-9592-c289b7462940.png)

Current crown icons look outdated on the new site and should be updated to a new fresh look.

**Comment by cl8n** [comment]
![Untitled-1](https://user-images.githubusercontent.com/9954349/74183437-cdce2300-4bf9-11ea-9e96-31b9ddc670c9.png)
FA icons look okay to me
