### ISSUE TITLE
Ranked score definition Wrong 

### ISSUE THREAD

**Issue by xasuma** [ppy/osu-wiki#3260]
Add a sentence or two describing the issue (or leave empty if the title is self-explanatory).

Right here, https://osu.ppy.sh/help/wiki/Score/#other-scores , the definition and example for Ranked score is incorrect. It used to be this way a long time ago, but not anymore. Now ranked score is given for the best score in all beatmaps , not just the best per beatmap**set**. 

Please note that this is to be used for issues regarding the osu! wiki only. If you are seeking general osu! help, visit the [Help forum](https://osu.ppy.sh/community/forums/5) or the #help channel in-game instead.

**Comment by paper-toaster** [comment]
Am currently working on cleanup for `/wiki/Score`; will resolve this in that pr
