### ISSUE TITLE
Featured artist: Sound Souler Mp3 has ~25s of unused audio in it's mp3 file. 

### ISSUE THREAD

**Issue by PsychoStatic** [ppy/osu-wiki#3276]
On [Sound Soulers](https://osu.ppy.sh/beatmaps/artists/70) FA page the mp3 that can be downloaded for "Sound Souler - Broken Stars" has ~25s of unused audio. Cutting it down could save file size. Cutting it down in audacity saves 0.7MB not sure if you'd consider it worth it, but the rule "If you do not map the last 20% of your beatmapset's audio file, it must be cut. The intro time is not included. This does not apply if more than 20% of the outro is occupied by a storyboard/video." depending on where someone finishes mapping, could lead to some issues in modding/ranking.

**Comment by Coppertine** [comment]
On [Billain](https://osu.ppy.sh/beatmaps/artists/46)'s FA page, the mp3 that can be downloaded for "Billian - The Nomad's Revenge" has ~4 minutes of unused audio. Cutting it down could save file size.

**Comment by Coppertine** [comment]
These don't really matter as both the FA team and RC/BN teams are completely different.

**Comment by PsychoStatic** [comment]
But at least the billain track actually has audio, that, although hard, could still be mapped to. Sound Soulers track literally has no audio. making it absolutely obsolete

**Comment by Nivalyx** [comment]
@Coppertine are you sure about Nomad's Revenge though? if you're referring to the part from where the beat ends (around 05:53) to the end of the song (10:02) it is... well, although it's technically close to unmappable but it's still the actual part of the entire song

**Comment by Coppertine** [comment]
At first, I didn't look into Broken Star's mp3 or something and thought it would be simular to Nomad's Revenge, where it's possible with 4 minute slider art.. or something.

**Comment by Coppertine** [comment]
Okay.. I *think* there could be a reason for it.. but it's nice for that 25 second long thing (from 82.6% of the song) to be noticed.. It could get fixed.

**Comment by Nivalyx** [comment]
regarding Nomad's Revenge i suppose that's how the song is licensed in the first place though (as in Billain provides the full song instead of a special "osu! edit" version for use in osu!). also mappers who are interested to map Nomad's Revenge are already free to cut the song (to a reasonable extent) in order to fit the mapping needs iirc, as stated in the Mappers' Guild's FAQ page (http://mappersguild.com/faq) :

> Can I cut songs?
> Yes, so long as it is still a reasonable length (so like, avoid anything below 1:30).

the 25 seconds of silence in Broken Stars seem like an actual valid issue though in the other hand

**Comment by Ephemeralis** [comment]
This is now fixed and the osz has been updated to factor in the new audio/timing adjustment requires.

The only time an FA track will be altered w/o an official artist edit from our side is when as in this issue, it has objective issues with prolonged silence resulting from export errors.

We don't really make cropping edits to actual aural content. That's up to the mapper to decide.
