### ISSUE TITLE
Ranking Criteria article has an incorrectly used word

### ISSUE THREAD

**Issue by PsychoStatic** [ppy/osu-wiki#3277]
In [the article](https://osu.ppy.sh/help/wiki/Ranking_Criteria/osu!), one of the rules, specifically this one -> "If you do not beatmap the last 20% of your beatmapset's audio file, it must be cut. The intro time is not included. This does not apply if more than 20% of the outro is occupied by a storyboard/video." has an incorrectly used word. The first use of "beatmap" should be instead changed to just "map".

**Comment by cl8n** [comment]
it seems intentional, the writers of RC like to use full terms and this is used like a verb elsewhere
