### ISSUE TITLE
Add criteria for external link formatting

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-wiki#3285]
Currently external links are styled in different ways across the wiki. I suggest setting the format to the criteria below:

- Always use `https://` over `http://` unless site doesn't have a valid certificate (if site doesn't have a certificate, should it be linked at wiki?)
- Never use `www.` unless site doesn't work as intended without it
- Never add trailing slashes at the end of URLs

**Comment by cl8n** [comment]
I don't understand the point of the last 2, what difference does this make to anything

first one is already in ASC

**Comment by TPGPL** [comment]
They are there to unify the formatting style. If links work fine without those things, what is the point of keeping them, then?

**Comment by cl8n** [comment]
discussed in some other pr, tl;dr do what the site recommends
