### ISSUE TITLE
Fix 2013 news article dates

### ISSUE THREAD

**Issue by peppy** [ppy/osu-wiki#3346]
We need to find historical archives and correctly date all news posts with the same date

2013-07-31-clicking-styles.md
2013-07-31-commentating-circle-clicking-competitions.md
2013-07-31-easy-mod-how-and-why.md
2013-07-31-highlights-of-july.md
2013-07-31-interview-with-ephemeral.md
2013-07-31-maras-gaming-corner-july.md
2013-07-31-the-revival.md

**Comment by TicClick** [comment]
I've done some digging yesterday, all to no avail. I've been to:
- https://osunews.tumblr.com/archive: as peppy said (tumblr, not Twitter), all posts are dated 2013-07-31, but time stamps are different, I looked them up via tumblr api v1:
  - 2013-07-31 04:39:00 GMT (the revival)
  - 2013-07-31 05:38:00 GMT (interview with Ephemeral)
  - 2013-07-31 05:50:00 GMT (easy mod: how and why)
  - 2013-07-31 05:52:00 GMT (Mara's gaming corner: July)
  - 2013-07-31 06:00:00 GMT (clicking styles)
  - 2013-07-31 06:05:00 GMT (commentating circle-clicking competitions)
  - 2013-07-31 18:58:00 GMT (highlights of July)
- https://www.facebook.com/osugame: no announcements for July
- https://osu.ppy.sh/community/forums/9: no announcements for July, and it is pretty coarse overall
- Disqus: it seems that it was integrated with osu!news way later than with the rest of the site (around 2015), as its [topic for, say, "Highlights of July"](https://disqus.com/home/discussion/osugame/highlights_of_july/) says "5 years ago" ([API response](https://gist.github.com/TicClick/5489f1c748630f94f6d4faca3b034aa0))

**Comment by TicClick** [comment]
yeah, and according to web.archive.org, osu! web didn't display the news on the main page in 2013: https://web.archive.org/web/20130806021234/http://osu.ppy.sh/
neither the news articles themselves hosted on tumblr had any date/time stamps: https://web.archive.org/web/20160823051838/https://osu.ppy.sh/news/56990275116

**Comment by TicClick** [comment]
other options:
- there may be subforums specific to the news group I have no access to;
- I've checked https://osu.ppy.sh/community/forums/3 for threads/posts made in July '13 (for example, chart assembly team's announcements were moved to AW), but found nothing; may happen if someone has left a reply later on and bumped the thread;
- ask Mr. Color/Mara as authors, dkun/deadbeat as news leads. granted, it's been 7 years, but their memory may hold intact!

**Comment by TicClick** [comment]
dkun has done me a favour of going through his GDrive full of drafts and says that all of these articles were compiled and proofread during July, and then posted in bulk on the same day, and yes, it is 2020-07-31 (drafts are dated 2020-07-30). this also confirms what MillhioreF has said, so we've got to work around that.

back to you, peppy

**Comment by peppy** [comment]
Thanks for doing the extra research here. I guess this can... just be closed as being *correct* then? Not sure we an do much better than what we already have.

**Comment by TicClick** [comment]
we can update their timestamps, because right now they are datestamps, with time being 00:00:00 +0000. hope that will bring in some order
