### ISSUE TITLE
Add full resolution yuzu catcher to osu!catch skinning section

### ISSUE THREAD

**Issue by chrsbell** [ppy/osu-wiki#3377]
It would be nice to have the full resolution catcher images available on the wiki for those that want to skin them, right now the images are tiny (153x160) compared to the in-game resolution (305x324)

**Comment by cl8n** [comment]
here are the files [catcher.zip](https://github.com/ppy/osu-wiki/files/4392702/catcher.zip) -- they're supposed to be in a default skin template, not embedded on the wiki. but the only default template I can find is out of date and doesn't include these

@peppy is there a more updated version of https://osu.ppy.sh/community/forums/topics/129191 ? we have links to this in a few places

**Comment by peppy** [comment]
There is not, but if someone attaches an updated version I can update that thread.
