### ISSUE TITLE
Can i build a local server which just used by myself and my friend which in the same network?

### ISSUE THREAD

**Issue by ZhiShengYuan** [ppy/osu-wiki#3397]
for some reason,we can not connect the server ,expect we use vpn---but it is easy to be block by the GreatFriewall,so want set a server by myself,can i do it?

**Comment by mcendu** [comment]
> for some reason,we can not connect the server ,expect we use vpn---but it is easy to be block by the GreatFriewall,so want set a server by myself,can i do it?

To allow us to access GitHub don't spell these words out loud

**Comment by peppy** [comment]
wrong repository, and not yet possible using official means. but we hope to support such use cases going forward via lazer.
