### ISSUE TITLE
Resources needs to be updated with new resources from osu-web

### ISSUE THREAD

**Issue by sr229** [ppy/osu-wiki#345]
currently, some parts of the wiki still uses old resources from the old website.

To be in line with the new site merge, all resources must be updated to their new counterparts.

**Comment by kj415j45** [comment]
links should use new style, too.

**Comment by TPGPL** [comment]
@flyte?

**Comment by Joehuu** [comment]
> links should use new style, too.

Is this already implemented? Original issue is resolved, I think.

**Comment by sr229** [comment]
Can I get confirmation this has been resolved now?

**Comment by Joehuu** [comment]
Can be closed now.
