### ISSUE TITLE
Broken Ouendan gameplay image on FAQ page

### ISSUE THREAD

**Issue by andyglover** [ppy/osu-wiki#3477]
The first image under the Introduction section of the [FAQ](https://osu.ppy.sh/help/wiki/FAQ) contains a broken image labelled "Gameplay example of Osu! Tatakae! Ouendan in Nintendo DS"

![broken1](https://user-images.githubusercontent.com/13704069/80061491-4993f800-84e6-11ea-9d28-1a725227a1f9.png)

![broken2](https://user-images.githubusercontent.com/13704069/80061493-4bf65200-84e6-11ea-971e-c1015a98494f.png)

**Comment by cl8n** [comment]
some kind of caching issue, the link does go to an image on the wiki

**Comment by cl8n** [comment]
this one fixed itself over time, opened https://github.com/ppy/osu-web/issues/5990 for another case of the same thing
