### ISSUE TITLE
Remove all puush mentions

### ISSUE THREAD

**Issue by lmnyx** [ppy/osu-wiki#3629]
Since puush isn't maintained anymore there is no reason why mentions should stay

**Comment by peppy** [comment]
Care to link where it is mentioned?

**Comment by TPGPL** [comment]
It's mentioned a few times in [BBCode](https://osu.ppy.sh/help/wiki/BBCode) article, [Glossary](https://osu.ppy.sh/help/wiki/Glossary) as a seperate term and [Skinning/FAQ](https://osu.ppy.sh/help/wiki/Skinning/FAQ) as a tool

**Comment by peppy** [comment]
Could consider replacing with upppy, which is still "maintained" (not that puush isn't, but the fact you can't make an account makes it less useful to most people).

**Comment by TPGPL** [comment]
imo it would be more reasonable to remove puush completely instead of replacing it with upppy, as it requires Flash to upload, which is currently blocked by most browsers
