### ISSUE TITLE
osu!wiki Contribution Guide

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-wiki#372]
Current OWCG elaborately explains *every* aspect of GitHub. It makes it very *long* and cluttered with useless information. It doesn't engage new contributors, but scare them off.

OWCG should be:
- simple
- short
- easy to understand
- preferably in image form
- contain extra resources for inquisitive contributors

**ppy** said:
>well i mean
>it should be something linke
>- login to github
>- click edit button
>- make changes
>- submit pull request
>all using the web interface

**Comment by kj415j45** [comment]
https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project
it's enough
💡 
🤔

**Comment by RaikireHiuduo** [comment]
#333 : https://github.com/RaikireHiuduo/osu-wiki/blob/contribute/wiki/osu!wiki_contribution_guide/test.md

Proposal for owcg v2. Incomplete and I need suggestions.

**Comment by sr229** [comment]
#513

**Comment by sr229** [comment]
I think i got another proposal

Maybe we can simplify and split the Desktop changes guide and the Web Guides into two seperate articles

**Comment by sr229** [comment]
so here's my porposal for the new OWCG format

### Proposed Directory Structure

```
wiki/osu!wiki_contribution_guide
|
|______img
|       |
|       |____desktop
|       |____web
|
|_____desktop
|        |
|        | ____en.md
|_____web
|      |
|      |____en.md
|
|___ en.md (index)
````

**Comment by sr229** [comment]
Reiterating my directory structuring since this is on my agile TODO lists
```
```
wiki/osu!wiki_contribution_guide
|
|______img
|       |
|       |____desktop
|       |____web
|
|_____desktop
|        |
|        | ____en.md
|_____web
|      |
|      |____en.md
|
|___ redirect.yml (web reads this to redir to desktop/en.md by default_
````
