### ISSUE TITLE
Clarify Bot Account Article Public Rate-limits

### ISSUE THREAD

**Issue by ThePooN** [ppy/osu-wiki#3731]
On the new [Bot Account](https://osu.ppy.sh/help/wiki/Help_Centre/Bot_Account) page, it is noted:

> **The bot must not send any messages in non-multiplayer public channels.** All bot interaction must be done in private messages.

Yet, there are limits specified for both public & private channels. The quoted sentence hints that multiplayer are public channels and the only kind of non-PM channel allowed for bot usage.

I remember when osu_SQL was set up, multiplayer channels were considered private channels, in regards to the rate limits. ([bancho.js](https://bancho.js.org) considers multiplayer channels private at this time, and this behavior was verified.)

I think it should be stated in this issue whether this behavior has changed. If yes, the article should address "public rate limits" as "public & multiplayer channels rate limits" instead. Otherwise, it should be specified that "private messages" limits also include multiplayer channels.

**Comment by cl8n** [comment]
not sure which one is intended 
@peppy  ?

**Comment by peppy** [comment]
both multiplayer and spectator chat count as private.

**Comment by cl8n** [comment]
in that case listing a public rate limit seems kinda pointless if you're telling people to never use it

**Comment by peppy** [comment]
Yeah, I think we should just remove it completely from the document and not advertise it.
