### ISSUE TITLE
Article Styling Criteria needs more sections/info

### ISSUE THREAD

**Issue by paper-toaster** [ppy/osu-wiki#3810]
Being a lowly wiki janitor and stub writer, I tend to refer to the ASC quite a bit when conflicts arise. And I've noticed that there are some things that should be elaborated upon/given a specific criteria. The following are some of my suggestions:

## Suggestions
- **Add a section specifying which style numbers should be written in.** Whenever I stumble upon an article that has a number in it, it's wildly inconsistent whether or not they will use their symbol or their written-out counterparts. And being that different writing styles (e.g., MLA, Harvard, Chicago Manual, etc.) use symbols vs. words for numbers in different situations, it's hard to have a concrete reference. So the wiki needs some sort of section that explains which style to use. *As ApplePi suggested, Wikpedia's MoS should be fine for this.*
- **Add a section for "Not to be confused with" hatnotes.** This one isn't much of a problem, but it would still be nice to have an explanation for people who don't edit the wiki frequently.
- **Bold the "All headers must use sentence case.** I hadn't noticed this sentence in the ASC when reading it; so having this be in bold would help it stand out better.
- **Add spellings "Sign out" and "Sign in" to Terminology list** In the "Terminology" section, there's a part that *implies* that you should spell it as "sign out" but the actual terminology list doesn't specify the spelling. Adding some "official" confirmation would be nice for editors new to the wiki.
- **The "Point of View" section should specify that there are exceptions to the rule.** Specifying that FAQ sections and articles like the Help Centre are supposed to be written from the perspective of a osu! support team member would prevent cleanup PRs from trying to change the POV.

## Stuff worth mentioning

[Ephemeral's review](https://github.com/ppy/osu-wiki/pull/3680#pullrequestreview-442735893) on #3680 references some things that may be useful to include in the ASC, as pointed out by peppy.

---

*Edit 1: removed suggestion for adding a "how to" section for refs and icons due to inappropriate placement of such a guide.*

*Edit 2: added the "Stuff worth mentioning" section*

**Comment by sr229** [comment]
> The "Point of View" section should specify that there are exceptions to the rule. Specifying that articles like the Help Centre are supposed to be written from the perspective of a osu! support team member.

I disagree with this notion. We've established standards that all articles are written with neutrality in mind, this defeats that rule.

**Comment by Ephemeralis** [comment]
The Help Centre articles are basically a different thing entirely from much of the wiki, since they're official "customer support" material designed to be easy for people to parse, search and digest. They're written in a register specific purely to that singular article and should not be replicated elsewhere.

I don't think there's much need to say there's exceptions to this, because there generally isn't any other use case outside of the Help Centre scenario where a different register would be permitted for general use. If there is, I can't think of one at least.

**Comment by sr229** [comment]
> Specify whether "sign-out" should use a hyphen or not. In the "Terminology" section, there's a part that vaguely implies that you should spell it as "sign out" but the actual terminology list doesn't specify the spelling.

This is already standardized AFAIK, whatever we use in Terminology should be followed (Terminology is our source of truth IIRC).

**Comment by paper-toaster** [comment]
> The Help Centre article is basically a different thing entirely from much of the wiki, since it is an official "customer support" material designed to be easy for people to parse, search and digest, especially if they are not familiar with more encyclopedic, academic or neutral forms of writing. It is written in a register specific purely to that singular article and said register should not be replicated elsewhere.
> 
> I don't think there's much need to say there's exceptions to this, because there generally isn't any other use case outside of the Help Centre scenario where a different register would be permitted for general use. If there is, I can't think of one at least.

Yeah but the Help Centre article doesn't really have anything that visually separates it from the wiki. Users who are new to the wiki may make the same mistake.

Also, iirc, FAQ sections are typically written in the same perspective as the Help Centre article. Not sure if that should actually be that way tho.

**Comment by paper-toaster** [comment]
> > Specify whether "sign-out" should use a hyphen or not. In the "Terminology" section, there's a part that vaguely implies that you should spell it as "sign out" but the actual terminology list doesn't specify the spelling.
> 
> This is already standardized AFAIK, whatever we use in Terminology should be followed (Terminology is our source of truth IIRC).

Yeah, but some *more* official confirmation would be nice

**Comment by MegaApplePi** [comment]
> Add a section specifying which style numbers should be written in.[...]

Sure, I think [Wikipedia's MoS for writing numbers](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style#Numbers) should be good enough for this. Maybe?

> Add a section for "Not to be confused with" hatnotes.[...]

I added this in #3734

> Add a section explaining how to write headers.[...]

In the [Headings section](https://osu.ppy.sh/help/wiki/Article_Styling_Criteria#headings) the first sentence reads, "All headings must use sentence case." Does this clear up this point or were you looking for something else?

> Add a section that explains how to use icons and refs.[...]

I believe you are talking about the [Images section](https://osu.ppy.sh/help/wiki/Article_Styling_Criteria#images). However, if you are looking for how-to tutorial, you will need to look it up yourself. The ASC isn't supposed to be a Markdown tutorial.

> Specify whether "sign-out" should use a hyphen or not.

No hyphen. In that section, the spelling is supposed to be copied as it appears in the code.

> The "Point of View" section should specify that there are exceptions to the rule.

Sure, I'll look into adding some exceptions.

**Comment by paper-toaster** [comment]
> > Add a section explaining how to write headers.[...]
> 
> In the [Headings section](https://osu.ppy.sh/help/wiki/Article_Styling_Criteria#headings) the first sentence reads, "All headings must use sentence case." Does this clear up this point or were you looking for something else?

I must've not noticed this. I think a simple bolding of that sentence would make it stand out more.

**Comment by paper-toaster** [comment]
> > Add a section for "Not to be confused with" hatnotes.[...]
> 
> I added this in #3734.

Just checked the pr and the actual article; there doesn't seem to be any specified spelling or formatting for "Not to be confused with*
