### ISSUE TITLE
Usage of beatmap/beatmapset is ambiguous

### ISSUE THREAD

**Issue by Pennek** [ppy/osu-wiki#3857]
Older articles refer to a collection of levels for a song as a `beatmapset`  and a specific level as a `beatmap`. This usage is different to the current widely used terms within the community. Nowadays `beatmapset` (usually simplifed to `mapset`) and `beatmap` both refer to a collection of levels for a song, whereas `difficulty` is used to refer to a specific level.

This ambiguity is confusing to potential readers and doesn't make sense within the wiki. I believe we should aim for internal consistency between these terms. We can do this in one of two ways:

- Follow the historically correct terms
  - This will align terms with their usage in osu-related files (skinning files, .osu file, .osz file, etc) but will be more confusing for a majority of readers as terms don't align with their common usage within the community.
- Follow the widely adopted terms used by the community
  - This will make sense for a majority of readers but will cause confusion around ambiguous terms used in osu-related fileformats. (this could potentially be fixed from a developer standpoint)

**Comment by Pennek** [comment]
This could be detailed within the Disambiguation article

**Comment by cl8n** [comment]
not sure where you got the impression that beatmapset/beatmap are "old" terms, they're just long, so ppl dont type it in casual messages. also the context of any of these words usually resolves any ambiguity so you can write "map" and it makes sense, that's nothing new

with no context:
set, mapset, beatmapset => definitely a beatmapset
map, beatmap => either a beatmap or a beatmapset
difficulty => any one of like 5 different things

so I think what's best for wiki is to stick with the first two sets of terms, avoid using "map" or "beatmap" to describe a set, and explain the situation in the few places it matters

**Comment by peppy** [comment]
Our thinking was going forward we should maybe move towards "beatmap" and "beatmap difficulty"/"difficulty", but I'm not sure how this will play out if/when we decouple the concept of "sets". So I think "beatmap set" and "beatmap"/"beatmap difficulty" may be best?

**Comment by TicClick** [comment]
closing this in favor of the last step of #4723 because of https://github.com/ppy/osu-wiki/pull/4711#discussion_r550846047

> a beatmap contains difficulties, a "beatmapset" is a legacy internal term we use to collect difficulties of a beatmap. it has no place in casual discussion. use the terms "beatmap" and "difficulties" like we do everywhere on osu-web.
