### ISSUE TITLE
Figure out which articles' translations aren't the same content as English

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#3865]
the way we outdate translations now ignores that some articles don't really need to follow English, for example ASC and anything under Disambiguation. idk if there are more or special cases

we probably want to tag them in such a way that `outdated_since` isn't misleading and the translations can mark "outdated" on themselves without implying that it's because they don't match english.

**Comment by TicClick** [comment]
would this be partially resolved with https://github.com/ppy/osu-wiki/issues/7383?

**Comment by cl8n** [comment]
kinda. the case I mentioned in OP would now just use `outdated` tag. some other features of the wiki are built with the assumption that articles have similar contents across languages, but this is prob too niche of a case to be concerned about
