### ISSUE TITLE
Skinning

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-wiki#387]
## Skinning

All skinning elements should be divided into proper articles and described. Skin.ini features ought to be explained. Skinning Tutorials are needed as well.

### List:
- [x] Skinning
  - [x] Interface
  - [ ] osu!
  - [ ] osu!catch
  - [ ] osu!mania
  - [ ] osu!taiko
  - [ ] skin.ini
    - [ ] Blank
  - [ ]  Sounds
  - [ ] Tutorial
    - [ ] Interface
    - [ ] osu!
    - [ ] osu!catch
    - [ ] osu!mania
    - [ ] osu!taiko
    - [ ] Sounds

**Comment by MegaApplePi** [comment]
TODO

- [ ] add target practice elements (images and info)

**Comment by MegaApplePi** [comment]
Missing default elements:

- [ ] taiko-glow.png
- [ ] taiko-bar-left.png
- [ ] taiko-drum-inner.png
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by ImMock** [comment]
Requesting an update over here

**Comment by cl8n** [comment]
done
