### ISSUE TITLE
Modding/mapping scene unified timeline

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-wiki#3881]
osu!'s 10+ year history has lead to some pretty interesting developments. Most interesting of all for the lay-user is the intertwined paths of the modding/mapping scene, where most of osu!'s foundational changes in mapping meta and governance have originated from.

Recent discussions on Twitter surrounding ranked map quality got me thinking that an article (or series of articles) detailing the changes in leadership/policy/structure in the modding scene and the 'emergence' of maps/mappers considered notable to the mapping meta of their given eras (James et al) could be very useful information to have handy when informing changes for the future.

Much of this history is kept alive in snippets found hidden on the forums with the gaps filled in with testimony from people who were present - for the older years, these people are dwindling fewer and fewer as time passes.

Making this happen will require input from a few different people:

- Public collation via available forum threads (anyone can do this, promotions, dismissals, "official" threads detailing changes (things like the MAT announcements, etc)
- Private collation via Moderator Lounge threads (NAT/GMT/COP can do this, handles newBAT additions found in archived threads, community manager handovers, etc)
- Group discussion on establishing a handful of 'notable' or breakthrough mappers who pioneered new/highly popular styles that would later on go to lay the groundwork for future metas (James, DJPop, etc)

This would be a fairly big undertaking but an impossibly valuable one, in my view.

**Comment by JBHyperion** [comment]
I had a search around some aspects of this topic when working on MAT / BAT history for https://github.com/ppy/osu-wiki/pull/3173 which would be a good "objective" start regarding when teams were formed, when various leaders' tenures began and ended, etc.

Anything more subjective regarding who were the most notable, etc. mappers is probably out of my purview as I only joined the game in 2014, but as far as everything else goes I will gladly do some more digging for anything that may be relevant.

**Comment by Ephemeralis** [comment]
I've spent 5 hours today working out a SUPER rough timeline w/ forum thread/newspost links detailing everything I can currently find with help from JBH and the GMT that covers a lot of the structural changes.

There's things missing though, like much of the 2014-2015 minutiae which was lost when Trello ~fucking died~ was compromised. Any contributions on that front are very welcome. Hoping to have the sheet available publicly in the coming days.

**Comment by Ephemeralis** [comment]
This is progressing in full swing and the research/collation can be viewed here:

https://docs.google.com/spreadsheets/u/1/d/11mxtNSTBRaZh6Lzwa52cRp4opGGIxECAIlqfLeQEcls/edit#gid=0

Anyone interested in helping out/contributing can submit dates w/ posts via this issue, or contact me in-game as Ephemeral with their email address to be added to the editor list for the sheet above.
