### ISSUE TITLE
There's no information regarding how (or if) players can submit bug reports

### ISSUE THREAD

**Issue by paper-toaster** [ppy/osu-wiki#4144]
Noticed this when I actually had a bug (I think) that I needed to report, but didn't actually know how or where to submit bug reports. Even if there *is* somewhere in the wiki where it's described, it's not in any obvious place (like on the FAQ, Help Centre, or How you can help).

So I propose that there be some section in an article (preferably FAQ) that details how/where to report bugs. (And if there isn't a real way to report bugs, then we should probably explain that.)

**Comment by TicClick** [comment]
if this happens, this gem will finally be updated to link to the new article:
```
[21:49:44] <TicClick> !faq bug
[21:49:44] <BanchoBot> If you think you've found a bug, report it [https://osu.ppy.sh/forum/5 here]. Just make sure no one else posted your problem beforehand.
```

**Comment by paper-toaster** [comment]
Would prob also be a good idea to put the help forums under the help toolbar

**Comment by paper-toaster** [comment]
Will prob take this if no one else wants to
