### ISSUE TITLE
Developers page should be split into active/past

### ISSUE THREAD

**Issue by peppy** [ppy/osu-wiki#4302]
Most of the [developers listed](https://github.com/ppy/osu-wiki/blob/master/wiki/People/The_Team/Developers/en.md) are not active, while we have other (open source contributors) which have helped out far more.

Might be good to move all inactive developers to a section below the current list, and list as "past contributors" or similar.

I'm happy to update this if a structure can be decided upon, or I can provide the information on who is currently active if someone wants to take on this task.

**Comment by kj415j45** [comment]
Consider using the same structure like wiki/People/The_Team maybe?

```
## Active team members

## Open source contributors

## Inactives team members
```

**Comment by Joehuu** [comment]
The developers wiki page just lists the current [user group members](https://osu.ppy.sh/groups/11) and that is outdated. That should be updated first.

---

Honestly, the web's user group pages should be the one handling active users. Needs to revamped to support https://github.com/ppy/osu-web/issues/4398, so active users can be distinguished of the role they have. My long standing issue (https://github.com/ppy/osu-wiki/issues/2145) will also be resolved for all user groups wiki articles.

And for the inactive ones, that is what the wiki is for. We have the [osu! Alumni](https://osu.ppy.sh/help/wiki/People/The_Team/osu!_Alumni) if we are willing to move those users to that group and put "developer" or something more detailed as their past role.

**Comment by Ephemeralis** [comment]
Best approach with this would be what Joehuu's suggesting, and also splitting any sort of extra permission burden from the current osu!dev usergroup so it can be applied as a cosmetic marker for people actively working on the project - including established open source contributors.

**Comment by venix12** [comment]
I think it might make more sense to have different usergroup for open source contributors or some other thing (like user title for example), osu!dev usergroup likely associates with the headquarters of this game in many people's heads I guess?

**Comment by peppy** [comment]
we don't really do that though. regular open source contributors are considered equal.

**Comment by cl8n** [comment]
well at least on the osu-web side there already are no special permissions, just forced account verification & disabled password reset like other groups

**Comment by venix12** [comment]
guess it might have some permissions stuff on the legacy website

**Comment by cl8n** [comment]
since the extra usergroup info @Joehuu mentioned doesn't seem to be a priority on osu-web and (I'm assuming) the permission splitting @Ephemeralis mentioned isn't a high priority either, let's solve this issue without writing code for now

all of the group wiki pages are reflections of the web group listings, so I think it's best we keep "Team members" as-is and add an "Open-source contributors" section below it. inactive/past devs should be moved to Alumni like Joehuu said.

**Comment by cl8n** [comment]
if nobody thinks that's a bad idea^ then @peppy will have to provide list of ppl to add

**Comment by peppy** [comment]
For the open source contributors? I think the best way is to source top contributors from the github pages themselves. ie. set a cut-off for top x and then grab them from each project.

**Comment by sr229** [comment]
> For the open source contributors? I think the best way is to source top contributors from the github pages themselves. ie. set a cut-off for top x and then grab them from each project.

Plus with the ever changing landscape of the open source development, I don't think it would be wise for this to be a manually-audited task IMO, this should be automated instead on the web side.

**Comment by peppy** [comment]
Just link to the github pages then? Likely no reason to include the users locally.

**Comment by sr229** [comment]
> Just link to the github pages then? Likely no reason to include the users locally.

Better yet a redirect if that's the case and just have it in GitHub pages if we're going that route.

**Comment by peppy** [comment]
To get the ball rolling on this, or at least get the page into a sane state:

- the following members need to be removed: MillhioreF, Tom94, RBRat3.
- "server developers" makes no sense. changing the header to "Web front end / backend services" may work better.
- there should probably be a link to the github contributors page with some brief description of how a lot of the development these days is community driven by a team larger than just the core team. the best way to do this if probably adding an entry per section for each of the relevant projects (https://github.com/ppy/osu/graphs/contributors / https://github.com/ppy/osu-web/graphs/contributors)
