### ISSUE TITLE
Image Standards

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-wiki#434]
For historic reasons this short discussion took place
![discord_2017-07-04_12-46-55](https://user-images.githubusercontent.com/14264992/27839642-6941ce16-60b8-11e7-9eaf-b5260d406623.png)

**Comment by sr229** [comment]
probably CC flyte if we already have fixed standards and update this discussion if there any updates.

**Comment by MegaApplePi** [comment]
Screenshots of gameplay should:
- use the default skin, wherever possible
- have the fps counter disabled
- use the JPG file format

---

❓
- Images should not be wider than 680px?

**Comment by MegaApplePi** [comment]
❓ (questionable):
- Screenshots of gameplay should use the stable, fallback, or beta build to avoid the cuttingedge banner/version that appears at the bottom of the screen

**Comment by Repflez** [comment]
@MegaApplePi Every image should be done in the stable build, unless it's for a feature/change that appears in a different build, like target practice or stable fallback itself.

**Comment by MegaApplePi** [comment]
Screenshots of gameplay must be in 16:9 (widescreen) unless you have a good reason to use 4:3 (standard).

![discord_2017-08-11_19-56-22](https://user-images.githubusercontent.com/14264992/29236357-2ae860f0-7ecf-11e7-9ddd-b03a1d9c93d8.png)

**Comment by MegaApplePi** [comment]
If an image contains english text/annotation, it can and should be localized.

- localized image versions should be placed in the same directory as the original version (that is, the English version)
- the filename of a localized image version should start with the original version's name, followed by a hyphen, followed by the locale name (in caps)
  - e.g. `hardrock_mod_vs_easy_mod.jpg` (contains annotations in English)
  - e.g. `hardrock_mod_vs_easy_mod-DE.jpg` (contains annotations in German)
  - e.g. `hardrock_mod_vs_easy_mod-ZH-TW.jpg` (contains annotations in Traditional Chinese)

---

In addition to using the `Exo 2` Light font, all CJK characters should use the `Microsoft YaHei` font.
