### ISSUE TITLE
osu!mania ranking criteria's link is broken in the english general ranking criteria

### ISSUE THREAD

**Issue by pimpG** [ppy/osu-wiki#4384]
https://osu.ppy.sh/help/wiki/Ranking_Criteria

"For game mode-specific ranking criteria, see: osu!, osu!taiko, osu!catch, and osu!mania"

the link doesn't behave like the other three mode specific links, it only works if i hover the mouse around the botton right of the first letter of the link.

happens on chrome and edge, didn't tested on other browsers.

**Comment by zeusminus** [comment]
This should probably be addressed in [osu-web](https://github.com/ppy/osu-web) repo, as things seem to be functional wiki-side. Perhaps recently added drop-down list that contains available locales might be bugging the links within the same column?

**Comment by pimpG** [comment]
did
