### ISSUE TITLE
Beatmap Spotlights Summer 2020 leaderboard incorrect

### ISSUE THREAD

**Issue by willyosu** [ppy/osu-wiki#4386]
The leaderboard shown on the wiki seems to be an outdated one which is missing some players and misplaces others, and displays the badge assets one tier lower than they are in reality. Although image below is from standard this does occur on all mode leaderboards.

![Untitled](https://user-images.githubusercontent.com/11691902/97670751-482b2580-1a5d-11eb-9f55-7c41788303e3.png)

**Comment by cl8n** [comment]
images still need to be fixed
