### ISSUE TITLE
Slider `length` property is for the entire slider or just for a single slide?

### ISSUE THREAD

**Issue by negamartin** [ppy/osu-wiki#4430]
According to [`https://osu.ppy.sh/help/wiki/osu!_File_Formats/Osu_(file_format)#sliders`](https://osu.ppy.sh/help/wiki/osu!_File_Formats/Osu_(file_format)#sliders) (as of 2020-11-09), the `length` property of sliders applies to a single slide. However, in my tests it seems to be the length of the entire slider. Is this correct? Does it need to be changed?

Thanks.

**Comment by cl8n** [comment]
it's the visual length of the slider for one slide. adding more repeats doesn't change the length

what are you doing to test?

**Comment by peppy** [comment]
it's the length of the path. repeats are denoted separately.

**Comment by negamartin** [comment]
Nevermind, I was parsing beatmaps in a standalone app, and I saw sliders that clashed with other hitobjects in the wild and blamed it on slider repeat being wrong. Turned out I was rounding by beats wrong.

Sorry for the noise.
