### ISSUE TITLE
Score Multiplier stub contains incorrect scoring information

### ISSUE THREAD

**Issue by MilkyIQ** [ppy/osu-wiki#4448]
The formula used to calculate score integrates the score multiplier in a much different way than is described in the article. Relates to #2528. The article in-question can be found [here](https://osu.ppy.sh/help/wiki/Game_modifier/Score_multiplier).

**Comment by Sunnyboy971** [comment]
> The formula used to calculate score integrates the score multiplier in a much different way than is described in the article.

Sorry to trouble you. However I dont understand: Is there any possibility that the score multiplier in the wiki refers to the exact one shown in the mod selection screen(i.e. The Mod multiplier). And the issue refers to the one during gameplay(i.e. Combo Multiplier)?

If explained in this way, the issue mentioned above simply lies in the title, which causes misunderstanding.

**Comment by Walavouchey** [comment]
> Sorry to trouble you. However I dont understand: Is there any possibility that the score multiplier in the wiki refers to the exact one shown in the mod selection screen(i.e. The Mod multiplier). And the issue refers to the one during gameplay(i.e. Combo Multiplier)?

no. it refers to the fact that this description in https://osu.ppy.sh/wiki/en/Gameplay/Game_modifier/Score_multiplier

> For example, if a player plays an osu! [beatmap](/wiki/Beatmap) with no mods enabled, and gains a final score of 100,000, then the final score will be 100,000. However, if that same player achieved the *exact same play* on the *exact same beatmap*, with the [Hard Rock](/wiki/Gameplay/Game_modifier/Hard_Rock) mod enabled, then the final score would be 106,000 because the Hard Rock mod's Score Multiplier value is 1.06x. During a play, the score multiplier value is multiplied with the current score in real-time, although it is possible to calculate the final score after-the-fact by simply multiplying the two values together: `finalScore * scoreMultiplier`.

is wrong. you can't simply multiply a score by 1.06 to get the score you would get if you picked hard rock. this is because the score calculations aren't that simple (read https://osu.ppy.sh/wiki/en/Gameplay/Score/ScoreV1/osu!)
