### ISSUE TITLE
Helpdesk article changes

### ISSUE THREAD

**Issue by osuShiro** [ppy/osu-wiki#459]
**The flag on my account profile is wrong!**
`A picture of any sufficient 100 points of ID (passport, driver's license) representing this alongside a slip of paper with your osu! username written on it is required for us to even consider your request.`
This has been changed to a picture of the ID with the user's account logged in to **the client** in the background.

**Can I change my account's username?**
Add something about requesting reverts. It should read like this:
```If you regret a change you've made, contact support to ask it reverted. We will only change your username back to **your direct previous name** (if you've made several changes, we only revert the latest one) and **we will only do so once per account**.```

**osu! freezes when I click a link or multiplayer map!**
`propreties` -> properties (this typo appears twice)
Remove the entire first paragraph, as it's redundant and the other two are more detailed.

**Comment by Ephemeralis** [comment]
No longer relevant.
