### ISSUE TITLE
add articles for each "support team"

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#4620]
similar problem as #1698 where one term refers to different people, in this case we should probably explain them separately too.

- the forum & bug tester support team ([has a wiki page](https://osu.ppy.sh/wiki/en/People/The_Team/Support_Team))
  - is this the same team that manages support@ppy.sh ?
- the account support team at accounts@ppy.sh

**Comment by peppy** [comment]
support@ and accounts@ is managed by myself and other internal team members. we don't really list the members of this team anywhere, intentionally.

**Comment by TicClick** [comment]
we don't plan to disclose its members at all. the purpose of the article is:

1) underline the difference between the team behind these two addresses and https://osu.ppy.sh/wiki/en/People/The_Team/Support_Team to avoid situations like that in c1175ba788c488eb294b1b04c55a6dee798009de, and
2) give a quick overview of what this team should be contacted for, in addition to https://osu.ppy.sh/wiki/en/Help_Centre/Account_Restrictions

**Comment by peppy** [comment]
Sounds fine, but I've disclosed all the information that should be required for such a stub to be made above.
