### ISSUE TITLE
Look into better ways to ensure content parity

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#4622]
[the content parity rule for translations](https://osu.ppy.sh/wiki/en/Article_Styling_Criteria#content-parity) is written with the right idea in mind, but in practice it gets messy when the original English article isn't fully up-to-date or written well. translators (rightly) choose to correct the mistakes and deviate from English a bit, leading to [situations the rule was designed to prevent](https://discord.com/channels/188630481301012481/218677502141399041/788156447375622216) if they don't also update the English article.

imo it's a problem that:

- we are effectively making translators responsible for maintaining English articles, which at best is not what they want to spend their time doing, and at worst is impossible because they may not have the required English writing skills
- deviations from English can easily go unnoticed, since many languages have little to no reviewers that are experienced with osu-wiki
- following English as close as possible (according to the rule) means translations adopt plenty of bad writing, structure, and formatting from English, basically just putting off work for far-future contributors to deal with

I don't know if there's any good way to prevent these problems, just opening this issue for now to see if anyone else has had thoughts about this

**Comment by TicClick** [comment]
one of ideas I have is to encourage creating new issues for minor things. this way, if a contributor feels the original article they are translating isn't well-written, they can do either of the two:

- open an issue for it and continue with the translation on their own terms, or
- open an issue for it and block until it's resolved

in both cases, the issue may be picked up either by us (preferable if faster), or by someone who's confident enough.

---

another resolution may be just proofreading all the article base and correcting things on the fly, or outdating the whole pages themselves, but that's a far less realistic goal, and even if it is, I can't say it's the nearest one.

**Comment by TicClick** [comment]
alternatively, we could add a pull request template, which would ask one to explicitly verify there are no differences from the original article, apart from these that could be considered language- or subcommunity-specific.

for example, I've recently sent a [one-character PR to discord.py](https://github.com/Rapptz/discord.py/pull/6153), and I was asked to verify I had run tests prior to that

**Comment by cl8n** [comment]
this issue is more broad than the PR that closed it, so leaving it open

**Comment by TicClick** [comment]
the checklist, along with presence of the `outdated_since` tag and https://osu.wiki, provide at least some coverage for this. I don't think we can do much more, so [closing](https://discord.com/channels/188630481301012481/218677502141399041/1213922699781603449)
