### ISSUE TITLE
Osu taiko scores big note hits as normal note hits most of the time.

### ISSUE THREAD

**Issue by Pursuit-W** [ppy/osu-wiki#4671]
I hit either both dons or both kats at the same time, but it almost never counts it as a big note hit for some reason, it just counts it as a normal note hit, I don't know why it happens.

**Comment by Joehuu** [comment]
Wrong place. I'm assuming this is for lazer?

**Comment by bdach** [comment]
Way way off-topic but this should actually be fixed in lazer. As far as I know, you need a frame-perfect double hit in stable for a big explosion to be shown.

**Comment by TPGPL** [comment]
Closing as off-topic. If you want to report the problem for osu!stable [create an issue in the osu-stable-issues repository](https://github.com/ppy/osu-stable-issues/issues/new) or [create a post in the Help forum](https://osu.ppy.sh/community/forums/topics/create?forum_id=5)
