### ISSUE TITLE
Add an article for osu!lazer

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-wiki#4686]
while the history is being written right now, we may lose it at some point. until the transition to osu!lazer is complete, we need at least a small article going over its origins, purpose, main advantages and features, which can be referred to from other osu! wiki pages

**Comment by paper-toaster** [comment]
I would totally be down to write this article myself, but considering the last article i attempted to write abt dev-related stuff was a flaming ball of garbage, I think it'd be better for someone who's actually working on lazer to write the article. Or, at the very least, have devs comment on and describe the intricacies they think would be worth putting in the article (like with the tech maps stub). But that's just my two cents

**Comment by PercyDan54** [comment]
I think most of the things is in [lazer's README.md](https://github.com/ppy/osu/blob/master/README.md) and [peppy's blog](https://blog.ppy.sh/a-definitive-lazer-faq/)

**Comment by sr229** [comment]
Would be happy to tackle this, but may have to wait until Q3 for me since I have some changes on my todo planned.

**Comment by MilkyIQ** [comment]
> I think most of the things is in [lazer's README.md](https://github.com/ppy/osu/blob/master/README.md) and [peppy's blog](https://blog.ppy.sh/a-definitive-lazer-faq/)

[page 13 of peppy's blog](https://blog.ppy.sh/page/13/) is also good place to start research on this. I would also suggest commit history and the changelog, but neither have the option to look at them at their very beginning

**Comment by PercyDan54** [comment]
> > I think most of the things is in [lazer's README.md](https://github.com/ppy/osu/blob/master/README.md) and [peppy's blog](https://blog.ppy.sh/a-definitive-lazer-faq/)
> 
> [page 13 of peppy's blog](https://blog.ppy.sh/page/13/) specifically is also good place to start research on this. I would also suggest commit history and the changelog, but neither have the option to look at them at their very beginning
> 
> It also seems that [EVAST](https://www.youtube.com/channel/UCsCQJoEZ6AWWdIu6qC6b8Mw) has been creating videos for osu!lazer since around 2017

Also some first releases: https://github.com/ppy/osu/releases?after=v2017.218.0

**Comment by Gamingzone123** [comment]
I would give it a go, but similar to Milky's earlier comment, the last article I tried to write was hot garbage. That said, this article is starting to be needed more, as the community meetings and such are becoming more populated, and more attention is drawn to lazer, people need a centralized place to read up on it rather than bouncing around peppy's blog, the changelog, the lazer README and wherever else information is located.

**Comment by peppy** [comment]
Going to mention that I've started a template for documenting gameplay changes between lazer and stable. It's something I'd eventually see ending up on osu!wiki (either mirroring or replacing the one I've made): https://github.com/ppy/osu/wiki/Gameplay-differences-from-osu!stable
