### ISSUE TITLE
osu!tourney wiki page broke

### ISSUE THREAD

**Issue by C0NS03L** [ppy/osu-wiki#4702]
The osu! tourney wiki page (https://osu.ppy.sh/wiki/en/osu%21tourney) 
Related Article Sections would redirect the user to "Requested page not found" Page
![image](https://user-images.githubusercontent.com/58496201/103263821-83a18c00-49db-11eb-8a1a-b4addbe6c4e9.png)

![image](https://user-images.githubusercontent.com/58496201/103263830-8c925d80-49db-11eb-9cc5-6eb6a7ef1d1f.png)
![image](https://user-images.githubusercontent.com/58496201/103263883-a6cc3b80-49db-11eb-822f-7ecd5dda9773.png)

**Comment by zeusminus** [comment]
This is rather an osu-web issue, likely due to percent encoding. I've already created an issue there as well: https://github.com/ppy/osu-web/issues/7029

**Comment by C0NS03L** [comment]
Okie I will close this issue then.
