### ISSUE TITLE
Rewrite "osu! program files"

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-wiki#4753]
- lots of incomplete sentences and conflicting formatting;
- does not conform to the writing style described in article styling criteria;
- needs fact checking and major update -- some things must have been changed over the time;

**Comment by mcendu** [comment]
From what I know, a few dependencies of the current client is in hidden files, including OpenTK and FFmpeg.

**Comment by MishterKirby** [comment]
Should we add info about lazer's file structure?

**Comment by peppy** [comment]
This is the kind of thing that should be added to lazer's wiki, since it is for development purposes.

**Comment by MishterKirby** [comment]
PR #4878 should take care of this.
