### ISSUE TITLE
Miss penalty in latest Performance Points Updates Post is confusing

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-wiki#4783]
Hi. This chart used in [the new Performance Points Updates Post](https://osu.ppy.sh/home/news/2021-01-14-performance-points-updates) is really confusing in my eyes (and to the few others I talked to about it).
![image](https://user-images.githubusercontent.com/34715248/104819127-bfd24a80-582b-11eb-90ee-64150aa09929.png)
It is labeled with "Miss penalty" but seems to show the actual multiplier applied to the aim and speed pp. 
If it would be the penalty in my eyes it should start at 0 and go up (as the penalty grows with each miss), not like it's now, which starts at 1 and goes down. 

The chart also starts at 0 misses and shows 0.97 for the new algo even though there (I hope at least) isn't a penalty from not missing at all. It should really be starting at 1 miss or show a 1x multi for misses<1. 

I would pr a updated version but I don't have the tools that was used to make this chart

**Comment by bdach** [comment]
Is this better?

![miss-penalty-curve](https://user-images.githubusercontent.com/20418176/104819541-70414e00-582e-11eb-8ff4-b43f4aeb517d.png)

**Comment by InvisibleSymbol** [comment]
Left chart still talks about some penalty being applied to the aim and speed pp (which would imply that a bigger value means more removed). Kind of also not agree with calling it "Miss multiplier", maybe go with "Multiplier based on Miss Count"?

The Scatter plot looks way better btw!

**Comment by bdach** [comment]
I'll do "Miss count-based multiplier for aim and speed" which should be similar enough.
