### ISSUE TITLE
Country code redirect in Banchobot article is outdated

### ISSUE THREAD

**Issue by C0NS03L** [ppy/osu-wiki#4790]
![image](https://user-images.githubusercontent.com/58496201/104836443-a2ab8380-58e0-11eb-90cc-d2da9660e9d6.png)

This will redirect to 
![image](https://user-images.githubusercontent.com/58496201/104836451-af2fdc00-58e0-11eb-9964-c8a3e979163f.png)
Which contains no country code.

I think the link needs to be changed to https://osu.ppy.sh/wiki/th/Article_styling_criteria/Formatting#locales

**Comment by TicClick** [comment]
that's right
