### ISSUE TITLE
Clean up references to Glossary

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-wiki#4804]
context: #3824

1. the glossary is still in place
2. a lot of redirects point to it
3. a lot of articles still point to the glossary

what needs to be done:
- [ ] redirects must point to the new articles;
- [x] direct links to the glossary must point to the new articles;
- [ ] the glossary needs to be an [index article](https://github.com/ppy/osu-wiki/blob/master/wiki/Article_styling_criteria/Formatting/en.md#index-articles)

_Originally posted by @TicClick in https://github.com/ppy/osu-wiki/issues/3824#issuecomment-762525385_

**Comment by DoryanR** [comment]
Is anyone on the job? If not, I can take care of it

**Comment by TicClick** [comment]
go for it. start with small, scoped changes, so that we can ensure your direction is correct

**Comment by DoryanR** [comment]
I have already started, I will post a PR to see if I can continue then
