### ISSUE TITLE
Getting started with translation

### ISSUE THREAD

**Issue by MaxTechnics** [ppy/osu-wiki#4875]
I'd like to translate (at least part of) the wiki to Dutch, but don't really see how to get started. Would just forking and adding nl.md to the articles be it? I don't understand the codebase entirely.
Thanks in advance!

**Comment by TicClick** [comment]
hi

yeah, that will mostly work, see here for details:

- https://github.com/ppy/osu-wiki/blob/master/wiki/osu!_wiki_Contribution_Guide/en.md
- https://github.com/ppy/osu-wiki/blob/master/wiki/Article_styling_criteria/en.md

and yes, we will eventually improve the contribution guide. if at any point you feel stuckbor clueless, please ask in Discord (https://discord.gg/ppy, `#osu-wiki` channel)

**Comment by MaxTechnics** [comment]
Thank you!, i am already in the server. I'll do the arrival request once i have a decent set of translated articles.
