### ISSUE TITLE
Make a shorter and usable version of article styling criteria

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-wiki#4888]
the formatting rules are ~700 lines long; the writing ones are around 300 lines. for me personally, it's hard to imagine everyone consulting with ASC (article styling criteria) before making a pull -- hell, I myself don't do that every so often.

one thing that would definitely help is having some sort of a contribution guide that would go over most points of the ASC and give a really short explanation, while referencing the relevant parts of ASC for those who need to see the reasoning, or examples of how things should be done.

this way, we'd have a checklist you can go over before submitting changes for review, and the criteria would only serve as a reference.

_Originally posted by @TicClick in https://github.com/ppy/osu-wiki/issues/4749#issuecomment-757092203_

**Comment by MilkyIQ** [comment]
This def isnt a bad idae, but i think it might be a better idea to have this sort of shortened ASC/checklist be incorporated into one of the "Getting Started" category of articles instead of its own thing, as most of the things the ASC covers is specific use cases like images or tables or markdown details

**Comment by sr229** [comment]
> This def isnt a bad idea, but i think it might be better to have this sort of shortened ASC/checklist be incorporated into one of the "Getting Started" category of articles instead of its own thing, as most of the things the ASC covers is specific use cases like images or tables or markdown details

I agree with this sentiment, this doesn't deserve it's own article from face value and should be integrated in our all-purpose Getting Started guide instead since we don't need to be concise for ASC. The ASC's intent is to make sure the criteria we have for including wiki articles here is met.

**Comment by MilkyIQ** [comment]
@TicClick Something like this maybe?

```markdown
## What is the ASC?

The ASC stands for "Article Styling Criteria" and it's meant to serve as the osu! wiki's styling standards to make sure all articles stay consistent throughout and clearly understandable.

## The ASC is so long! I just change this one little thing!

No one is expected to read through and understand the entirety of the ASC by heart before making a pull request, so it's okay if you don't. Whether you're a veteran wiki editor, or someone who's never written an article before, you can always go and look through the following checklist to make sure you're article is up to par:

- [ ] **Is your article written in a neutral/formal tone?** Aside from a few exceptions, all articles on the wiki should stray away from you/your/me/we/I and others, and [should try to stay as professional as possible](link).
- [ ] **Is the information in your article correct?** If you're adding or updating new information to an article, it's always best to make sure that you know that what you're saying is true.
- [ ] **Are your links, images, and tables formatted correctly?** These can be common culprits of big reviews! If you aren't sure on how to format anything, you can always check the ASC to find exactly what you're looking for!
- [ ] **Does your article have conflicts with remark?** Remark (on the wiki) is a special action that runs on every pull request to double check and make sure your article doesn't have any catastrophic formatting issues. To check this, you can navigate to the `Actions` tab on your pull request.
- [ ] **Are you absolutely sure that you don't have any typos?** One of the most common mistakes in any pull request would be typos or grammar issues. Reading through your article one last time and/or putting it through a spellchecker can save a lot of heartache!

Remember, it's okay if your pull request isn't perfect on the first try, that's why reviewers are here. Just make sure that you try your best to make your contribution as quality as you can; just going through this checklist can help everyone get contributions out the door quickly.
```

*I am aware that my description of remark is very oversimplified, it's intentional*

**Comment by TicClick** [comment]
yeah, something like that (soz for taking this long to comment), but I'd weed all exclamations out, there are too many of them.

**Comment by sr229** [comment]
A good reference to follow is the "How you can Help!" article, which was simple and straight to the point. You can cross-link if necessary.
