### ISSUE TITLE
Star priority wiki appears to be outdated

### ISSUE THREAD

**Issue by kolya5544** [ppy/osu-wiki#4946]
Star priority Wiki article seems to be outdated: https://github.com/ppy/osu-wiki/blob/master/wiki/Modding/Star_priority/en.md

It says: `Users that have supporter status active when voting will shoot a pink star (Kudosu) that increases Star Priority by 2 each, whilst a user without supporter will shoot a blue star (Star) that is worth only 1 each. Users may be able to shoot multiple stars depending on how many votes they have left.`, but other parts of a website say that only supporters are able to star features, and it doesn't show the colour of a star at all:
![image](https://user-images.githubusercontent.com/20096248/107486772-7c52ce00-6b96-11eb-80dc-f604d07b6abb.png)

**Comment by peppy** [comment]
Blue stars are no longer a thing, so it should probably be updated as such. That said, this system is a bit legacy these days, and we aren't actively working with the feature request forum (most of the development and feature request flow these days is on github).
