### ISSUE TITLE
Cleanup efforts

### ISSUE THREAD

**Issue by Repflez** [ppy/osu-wiki#5]
Articles have cruft from the pandoc convertion:
- Stray html from mediawiki quirks
- Malformed tables
- Missing references
- Etcetera

Cleaning them and making them presentable is a collaborative effort for everyone.

This issue will be used for discussion on the efforts, but joining the [discord chat](https://discord.gg/ppy) is a better option for a more timely answer.

**Comment by sr229** [comment]
The problem we have is some of these articles are really hard to reconvert to MD because of the quirky HTML (let's take for example, some of the HOO Articles)

**Comment by cl8n** [comment]
the major cases have been fixed and we have other formatting issues open that will address remaining problems

anything with these issues is likely super outdated and needs updates for other reasons anyway.
