### ISSUE TITLE
Monthly Beatmapping Contest newspost named incorrectly?

### ISSUE THREAD

**Issue by MilkyIQ** [ppy/osu-wiki#5002]
[This newspost](https://osu.ppy.sh/home/news/2014-04-28-monthly-beatmapping-contest-4-results) has its filename and content talking about the 4th monthly beatmapping contest, but the title in the article itself is "osu! Monthly Fanart Contest #2 - Vote for MFC#1 now!".

There's also a [duplicate newspost](https://osu.ppy.sh/home/news/2014-05-06-osu-monthly-fanart-contest-2-vote-for-mfc1) named the same thing but its contents seem to match the title

Its tumblr url also seems to point to the wrong article

**Comment by Joehuu** [comment]
Should be https://osunews.tumblr.com/post/84122008873/monthly-beatmapping-contest-4-results.

**Comment by MilkyIQ** [comment]
I'll start a pr then
