### ISSUE TITLE
Conflicting definitions of "Marathon" on wiki

### ISSUE THREAD

**Issue by tilda** [ppy/osu-wiki#5076]
[Beatmap / Marathon](https://osu.ppy.sh/wiki/en/Beatmap/Marathon):
> Marathon is a term used to describe beatmaps that are five minutes in length or longer.

[Glossary](https://osu.ppy.sh/wiki/en/Glossary#marathon):
> A type of beatmap that can only be approved.
>
> Marathon beatmaps are considered to be at least 6 minutes long and can only have one mapped difficulty. However, some marathon mapsets may contain a single osu!taiko variant as well.

Would like a clear definition on this term if possible. I'm assuming the former is the correct definition.

**Comment by peppy** [comment]
The top looks to be the most recent definition, although arguable 5 minutes is a pretty low cut-off for calling something a marathon.

**Comment by Nivalyx** [comment]
hmm, i don't think the term "marathon" is used that often anymore in the mapping scene nowadays but yeah i agree that the latter definition is very outdated and misleading at best.

will be pushing a pr for this in a bit as there's no harm in updating the outdated definition i guess 🧙

**Comment by tilda** [comment]
> The top looks to be the most recent definition, although arguable 5 minutes is a pretty low cut-off for calling something a marathon.

agreeable, though this topic might be a little out of scope for the issue

anyways, closing since #5081 got merged, ty niva~ (github didnt register the issue reference on that pr for some reason 🤷🏻 )
