### ISSUE TITLE
Fix general and osu! RC references + glossary

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-wiki#5248]
tracking what needs to be done for https://osu.ppy.sh/community/forums/topics/1294813 in this issue.

## summary of the situation
when the RC glossaries were refactored a long time ago, the terms were mostly converted into references to stub articles. some of the referenced articles either are *supposed* to be contained within RC for rulesetting purposes or had their contents updated (possibly incorrectly) in a way that makes the reference inside RC confusing. lack of maintanance on this front has caused at least a few misinterpretations of RC to crop up, as well as some nagivation issues, missing definitions, etc.

## solution
IMO the only realistic way to solve all the issues is a full comb through links in the general and osu! RCs. for each one:

if it's critical to rulesetting, and defined for that purpose (e.g. "reasonable spread"):
- add it to the RC's internal glossary, and change the link to point there
- if it doesn't mean anything useful beyond RC, delete the associated article or section

otherwise:
- check the contents of the article/section and make sure it's updated & correct
- consider duplicating it to the RC anyway if it's not a clearly defined game feature (e.g. "fully overlap"), since RC may occasionally want to manage these terms in a different way than the rest of the wiki

the goal is to make use of the now expansive set of articles to reference on the wiki while still containing everything important to rulesetting itself within RC. somewhere along the way it turned into a bit of a mess 🙃

**Comment by TicClick** [comment]
passing by to say that this may now be greatly simplified with [footnotes](https://github.com/ppy/osu-wiki/issues/7164). a short term definition, which is enough for the scope of the RC, may be given at the bottom of the article, along with the link to the full page if it's necessary/available:

```markdown
### Guidelines

**There should be no active sprites[^sprite-note] and commands after the end of the song.**

...

## Glossary

### Storyboarding

[^sprite-note]: [Sprite](/wiki/Storyboard/Sprite) is a colorless, lemon and lime-flavored soft drink created by The Coca-Cola Company.
```

**Comment by cl8n** [comment]
this is kind of just a "lack of maintenance" problem and should be fixed by the group that is essentially rewriting the entire RC rn so I'm closing this issue. if it's still a problem later then it is probably for new reasons.
