### ISSUE TITLE
Performance points page needs a full rewrite (priority)

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-wiki#533]
https://github.com/ppy/osu-wiki/blob/master/wiki/Performance_Points/en.md

https://osu.ppy.sh/wiki/Performance_Points

Much of the markdown is completely broken, missing icon links, broken headers, broken tables.

Marking this as an issue so we don't forget about it.

**Comment by TPGPL** [comment]
What about the ppv1 subfolder? Nuke 💣?

**Comment by RaikireHiuduo** [comment]
https://osu.ppy.sh/old-wiki/ZH:Performance_Points/v1

The only thing to keep for ppv1 is probably the image explanation only. Most of the explanation has been written in the current rewritten pp page.

Regarding the calculation table: I forgot where the calculation formula comes from.
