### ISSUE TITLE
Article Style Guide goes beyond it's defenition as a "Style guide"

### ISSUE THREAD

**Issue by sr229** [ppy/osu-wiki#535]
It's becoming more of a Code of Conduct for styling which introduces a standardized form of article-making throughout. We should consider renaming ASG to a more appropriate format.

**Comment by TPGPL** [comment]
Move to Ranking Criteria as Wiki Articles subfolder?

**Comment by sr229** [comment]
What is Ranking Criteria supposed to be? I think it's limited to beatmap ranking processing tbh, so it won't fit there.

**Comment by MegaApplePi** [comment]
If it really matters, then changing the word `Guide` to `Rules` or `Criteria` should suffice.

**Comment by sr229** [comment]
probably we should change the title as "osu!wiki Contributing Code of Conduct" or something related

would need more ideas on this

**Comment by sr229** [comment]
@MegaApplePi I'm still in partial of calling current ASG as ASC tbh, might be worth it.

I might make a PR to reflect this
