### ISSUE TITLE
Rewrite the "Getting your map modded" guide

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-wiki#5441]
https://github.com/ppy/osu-wiki/blob/master/wiki/Guides/Getting_Your_Map_Modded/en.md

at least the part about `#modreqs` doesn't look relevant anymore

**Comment by mousesalt** [comment]
I think referring to the forum [modding queue](https://osu.ppy.sh/community/forums/60) more relevant since the last time it got at the main forum. In short, this also seems like a procedure how to write a proper request beatmaps.

**Comment by THATotaku** [comment]
I'll give it a go if no one else has started yet, I have decent modding experience.
