### ISSUE TITLE
minor spelling error on agressor bunx's featured artist listing

### ISSUE THREAD

**Issue by mrowswares** [ppy/osu-wiki#5443]
![image](https://user-images.githubusercontent.com/83023433/118004301-3e09ae00-b341-11eb-8f34-a16e05b971f4.png)

this seemed like the best repo to report this

**Comment by TicClick** [comment]
https://osu.ppy.sh/beatmaps/artists/164
this is not stored on osu! wiki... @Ephemeralis?

**Comment by Ephemeralis** [comment]
fixed
