### ISSUE TITLE
Merge Song Content Rules and Explicit Content Guidelines

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-wiki#5527]
Currently we have the [song content rules](https://osu.ppy.sh/wiki/en/Rules/Song_Content_Rules) stating that:
- Heavily political
- Promoting racial tension or division
- Extremely and unbearably loud or excessively clipped
are not allowed, however the guidelines for [explicit content](https://osu.ppy.sh/wiki/en/Rules/Explicit_Content) do not state any of these and don't even leave a note. Very confusing, especially for when we moderators need to reference what is and what is not allowed.

Either properly cross reference these or somehow merge, dunno, the current state just seems very sub optimal

**Comment by TicClick** [comment]
crosslinking should do, I think
