### ISSUE TITLE
`hitcircleoverlay`'s documentation regarding `sliderstartcircleoverlay`/`sliderendcircleoverlay` usage is ambiguous

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-wiki#5546]
![CleanShot 2021-05-23 at 00 08 37](https://user-images.githubusercontent.com/22781491/119240823-0843a100-bb5b-11eb-8960-b037e84fd9bc.png)

On testing, `hitcircleoverlay` is never used for sliders unless the circle's texture itself (`sliderstartcircle`/`sliderendcircle`) isn't skinned, in which case `hitcircle` and `hitcircleoverlay` will be used for that circle instead.

**Comment by frenzibyte** [comment]
This have had hit me once again and I feel like the explanation above isn't quite understandable so I'm gonna reword it here:

The current documentation mentions "the `hitcircleoverlay` is also used for `sliderstartcircleoverlay`/`sliderendcircleoverlay` if not skinned", but from testing through this with osu!(stable) after stumbling around this:
 - if a `sliderstartcircle`/`sliderendcircle` exists but no `sliderstartcircleoverlay`/`sliderendcircleoverlay`, then no overlay will be shown, rather than using `hitcircleoverlay` which is what the documentation seems to indicate.
 - if no `sliderstartcircle`/`sliderendcircle` exists, then `hitcircle` will be used in place of them and `hitcircleoverlay` will be used as the overlay in that case.

**Comment by peppy** [comment]
Probably worth submitting a PR yourself given that no one else has taken this on.
