### ISSUE TITLE
Remove How to get songs from video games Article

### ISSUE THREAD

**Issue by THATotaku** [ppy/osu-wiki#5596]
Not that I am a legal expert or anything, but I'm not sure the osu! wiki should have a guide on how to rip music from video games for free, aka from an unofficial source for purchasing said music. If this is somehow not an issue, the article seems to be quite old, and mostly irrelevant in this day and age anyways. Apologies in advance if I'm being ignorant to something here.

Here is the article in question:
https://github.com/ppy/osu-wiki/blob/master/wiki/Guides/Getting_Songs_From_Video_Games/en.md

**Comment by peppy** [comment]
Agree that it should just be removed.
