### ISSUE TITLE
How can a page of another language be created?

### ISSUE THREAD

**Issue by user670** [ppy/osu-wiki#575]
Add a [language code].md in the same folder? (btw in what format should the language code be? What for zh-CN in particular? All caps? ISO standard?)

**Comment by kj415j45** [comment]
please check [ASG](osu.ppy.sh/wiki/asg), we pointed out all the available language code

***

basicly, we follow iso-639-1, but we make a bit change on it(added zh-tw, zh-hk, pt-br).

actually, we follow ppy/osu-web 's app/Libraries/LocaleMeta.php
