### ISSUE TITLE
Incorrect/outdated information in the "Users with unique titles" page

### ISSUE THREAD

**Issue by godoffours** [ppy/osu-wiki#5788]
Hello, was looking through the wiki and noticed some outdated information in this page, namely:
1. Mordred is listed as holding the Elite Nominator II title, however, that title has been removed from his userpage due to his resignation from his BN position as can be seen [here](https://osu.ppy.sh/users/7265097). This outdated title is listed both under the Elite Nominators section and in the By Name section
2. Spectator is listed as currently using the osu!catch Champion title in multiple places, however, he currently is using the Elite Mapper: Aspirant title as can be seen [here](https://osu.ppy.sh/users/702598). This should be noted in a footnote under the World Cup Winners section, the footnote regarding his titles under the Aspire Mapping Contest Winners section should be removed, and the By Name section should be updated.

**Comment by TPGPL** [comment]
resolved in #5820
