### ISSUE TITLE
Standardize Chinese translation for "Accuracy"

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu-wiki#5807]
Currently in the wiki Chinese translation for accuracy is a mess
There are ["准确率"](https://osu.ppy.sh/wiki/zh/Performance_points) [“准确度”](https://osu.ppy.sh/wiki/zh/FAQ#%E7%A7%AF%E5%88%86/%E5%87%86%E7%A1%AE%E5%BA%A6%E7%9A%84%E6%96%B9%E7%A8%8B%E5%BC%8F) [”精确度“](https://osu.ppy.sh/wiki/zh/Interface#%E6%88%90%E7%BB%A9%E7%95%8C%E9%9D%A2)

These translations are all correct, but it's better to make it standard.
If there is already a standard just tell me and close this issue.

**Comment by kj415j45** [comment]
“准确率”：Accuracy (percentage)
“准确度”：Accuracy (level)
“精确度”：Precision

"Accuracy" is closeness of the measurements to a specific value. While "precision" is the closeness of the measurements to each other.[1] For me, both “准确率” and “准确度” are ok depending on the context. But “精确度” should be corrected to one of them.

---
Reference:
[1] [Wikipedia contributors - Accuracy and precision](https://en.wikipedia.org/wiki/Accuracy_and_precision)
