### ISSUE TITLE
Use MediaWiki (again)

### ISSUE THREAD

**Issue by jxu** [ppy/osu-wiki#5899]
I know this is not helpful but some limitations of markdown (citing sources #4911, https://github.com/ppy/osu-web/issues/7031 and lack of templates) shows how we are pushing markdown way beyond its intended uses and where I believe proper mediawiki wiki is needed. A proper wiki does not preclude using a github issue tracker. I proposed in #4554 where Niva stated why the current project uses github, but I can dream anyway. I know the current system is established but I can help setup a mediawiki if needed. I am partial towards RemyWiki (and ArchWiki!) although it is by no means complete. 

(mainly copied from https://github.com/ppy/osu-wiki/issues/4911#issuecomment-887771107) 

I also think it would make contributing a lot more beginner-friendly as beginners do not need to know the ins and outs of Github and PRs, merely just making changes and waiting for them to be approved.

**Comment by TicClick** [comment]
while I wasn't around during the migration process, as well as the related discussion prior, I can see at least two points against mediawiki.

first of all, low entry barrier means vandalism and unverified/unchecked info. for one reason or another, we've had that both with the stable osu! client when its translation was publicly available and editable, and with the wiki itself (_especially_ the wiki, and especially during osu! world cups).

secondly, integration. the previous installation of mediawiki has regularly had issues with access (most frequently manifesting with people being unable to log in), and, from what I've seen, peppy had to give it a good prod quite often.

on top of that, you couldn't easily prevent silenced/banned users from making edits either, or at least this wasn't a priority, and I can speculate that any other modification would require more time and/or effort than if it was built from scratch, given that nowadays we use a very limited subset of what mediawiki offers.

granted, some features have to be reimplemented (#69, #182, #4911 and suchs), but, given the benefits, it may be a good tradeoff.

**Comment by peppy** [comment]
it's not happening and not even up for discussion. it would be impossible to implement in the client.
