### ISSUE TITLE
Add appeal-review@ppy.sh to account support team

### ISSUE THREAD

**Issue by axarille** [ppy/osu-wiki#5912]
I believe that with the (not so recent) introduction of the appeal-review email address, it should appear on this page of the wiki. Some restricted players who do wish for their appeal and such to be evaluated may not be aware of this, and may not go deeper into the wiki than this page when seeking answers.

https://github.com/ppy/osu-wiki/tree/master/wiki/People/The_Team/Account_support_team
https://osu.ppy.sh/wiki/en/People/The_Team/Account_support_team

**Comment by peppy** [comment]
it's already on the wiki. https://osu.ppy.sh/wiki/en/Help_Centre/Account_Restrictions
