### ISSUE TITLE
System file formats should not be documented on this wiki

### ISSUE THREAD

**Issue by peppy** [ppy/osu-wiki#6007]
Specifically, the https://osu.ppy.sh/wiki/en/osu%21_File_Formats/Db_%28file_format%29 page should be moved to the developer wiki, over at https://github.com/ppy/osu/wiki. Once it is added there, references should be removed from this wiki, apart from some text (maybe at the bottom of https://osu.ppy.sh/wiki/en/osu%21_File_Formats?) linking to the page for developers wanting information on system file types.

**Comment by cl8n** [comment]
why would a database format for stable go onto the lazer wiki? I don't think anyone would guess to look there, or know that it exists in the first place, if they aren't working on lazer.

**Comment by peppy** [comment]
That's the point. It should not be consumed for any other purpose. Documenting it on this wiki makes no sense as it is not supposed to be a publicly documented file nor something a user would be reading or writing.
