### ISSUE TITLE
Flags use old pastel designs with errors

### ISSUE THREAD

**Issue by Bazzadwarf** [ppy/osu-wiki#6017]
While osu-web has moved over to using twemoji for flags, the wiki still relies on using the old pastel designs. The problem here is that they still contain many of the mistakes that are mentioned in https://github.com/ppy/osu-web/issues/3760. While some of them are not easily spotted due to the small nature of the flags, there are still some obvious errors, as in the case of [Albania [`AL`]](https://github.com/ppy/osu-wiki/blob/master/wiki/shared/flag/AL.gif) [(correct design)](https://commons.wikimedia.org/wiki/File:Flag_of_Albania.svg) and [Trinidad and Tobago [`TT`]](https://github.com/ppy/osu-wiki/blob/master/wiki/shared/flag/TT.gif) [(correct design)](https://commons.wikimedia.org/wiki/File:Flag_of_Trinidad_and_Tobago.svg).

I'm not sure what the best solution to this problem would be, maybe there is some easy way to use with twemoji, but my familiarity with using it is next to nothing. Hopefully, it isn't as big of an issue to fix as I worry it could be.

**Comment by TicClick** [comment]
I think this is best supported at the osu-web's level, considering how ppy/osu-web#7875 handles flags. after that, perhaps we could use placeholders for quick linking (because there's no way in hell I'm using `https://osu.ppy.sh/assets/images/flags/1f1f9-1f1f7.svg` instead of `![][flag_TR]`)

**Comment by peppy** [comment]
ah, i see. didn't realise they already had a different sized edition. fine to keep them here too until a proper tag is added.
