### ISSUE TITLE
Translating Tournament wiki page?

### ISSUE THREAD

**Issue by NathanTurnYT** [ppy/osu-wiki#6153]
I am currently translating https://github.com/ppy/osu-wiki/blob/master/wiki/Tournaments/OWC/2021/en.md to french, but before continuing, I want to know if the efforts will be wasted or if I should continue.

**This is a question, not an actual issue**

**Comment by DoryanR** [comment]
Salut,

Honnêtement, ça n'a pas grande utilité car ce sont des articles avec un faible taux de vues (évoqué sur #2486).

Si tu souhaite aider la communauté française, je te dirait de piocher sur la liste sur le problème que je t'ai cité (lien qui renvoie sur une liste des articles sur lequel il faut ce concentrer, trié par langues), ce sera le mieux pour permettre de traduire des articles qui ont plus d'intérêt.

Merci d'avance pour ton aide dans la traduction, elle est toujours grandement apprécié.

**Comment by Nivalyx** [comment]
yeah feel free to go ahead if you're feeling like doing so (i mean there's nothing stopping you from doing so technically lol)

the osu! repositories are always open to quality contributions of all sorts, including article localizations.

**Comment by NathanTurnYT** [comment]
> Salut,
> 
> Honnêtement, ça n'a pas grande utilité car ce sont des articles avec un faible taux de vues (évoqué sur #2486).
> 
> Si tu souhaite aider la communauté française, je te dirait de piocher sur la liste sur le problème que je t'ai cité (lien qui renvoie sur une liste des articles sur lequel il faut ce concentrer, trié par langues), ce sera le mieux pour permettre de traduire des articles qui ont plus d'intérêt.
> 
> Merci d'avance pour ton aide dans la traduction, elle est toujours grandement apprécié.

Merci pour les détails!
