### ISSUE TITLE
Update Beatmapping - Star Rating Stub

### ISSUE THREAD

**Issue by THATotaku** [ppy/osu-wiki#6157]
Page in question: https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Star_rating/en.md

- [ ] Uses old star rating spectrum, I'm assuming you could just use the same image from: https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmap/Difficulty/en.md (image updated in https://github.com/ppy/osu-wiki/pull/6390)
- [ ] This: "On the website, beatmaps are automatically given a difficulty icon based on these star rating ranges:" is also outdated

I would do this myself but my fork and such is a mess idk how to fix it ;-;

**Comment by TicClick** [comment]
I vaguely recall we have a similar page, or a section, somewhere else, need to check if this one could be removed instead.

for the fork part, that's a perfect time to try the force sync github action for your `master` branch (https://osu.ppy.sh/wiki/en/osu%21_wiki/Contribution_guide/Common_Issues#my-branch-is-out-of-date!, part 2 `sync from osu! upstream`)

**Comment by THATotaku** [comment]
I had a look myself and could only find this: https://osu.ppy.sh/wiki/en/Ranking_Criteria/Difficulty_Naming which is fairly similar, but not quite the same.

Also thank you! I will give it a go soon.
