### ISSUE TITLE
Incorrect mp3 was used in "New Featured Artist: Lundy" news post.

### ISSUE THREAD

**Issue by Opposite34** [ppy/osu-wiki#6181]
In the news on announcement of new featured artist Lundy (found [here](https://osu.ppy.sh/home/news/2021-09-29-new-featured-artist-lundy)). The mp3 playback on the post, specific for the song "STOP?" was actually a wrong mp3 link. It instead previews the song "STOP." of the same artist, which is a different song.

**Comment by Opposite34** [comment]
Currently used link: https://assets.ppy.sh/artists/203/STOP/Lundy%20-%20STOP..mp3 (which is for the song "STOP." and not this one)

Link that should have been used: https://assets.ppy.sh/artists/203/Songs/Lundy%20-%20STOP.mp3 (which is for the song "STOP?")

**Comment by peppy** [comment]
Thanks for pointing this out!
