### ISSUE TITLE
Change tournament mappool list style 

### ISSUE THREAD

**Issue by Bazzadwarf** [ppy/osu-wiki#6207]
Currently, tournament articles use double bulleted lists for mappools. [MWC 4K 2021](https://osu.ppy.sh/wiki/en/Tournaments/MWC/2021_4K) used numbered lists for the maps in its mappool, and the feedback seemed to be positive as it better correlates to how players refer to map picks in practice, mod abbreviation + number `NM5`, `DT3`, `FM1`, etc.

Although I don't have any preference, it would be a worthwhile change if this better reflects how mappools are represented and used.

Relevant discussion: https://github.com/ppy/osu-wiki/pull/6206#discussion_r725505257

# Progress

Articles and other resources that need updating

- [X] Official tournaments https://github.com/ppy/osu-wiki/pull/6495
- [X] osu! (Community) https://github.com/ppy/osu-wiki/pull/6573
- [X] Taiko (Community) https://github.com/ppy/osu-wiki/pull/6573
- [X] Catch (Community) https://github.com/ppy/osu-wiki/pull/6573
- [X] Mania (Community) https://github.com/ppy/osu-wiki/pull/6573
- [X] Multimode (Community) https://github.com/ppy/osu-wiki/pull/6516
- [X] Tournament article template https://github.com/ppy/osu-wiki/pull/6496

# Current
```
- NoMod
  - [LiSA - Confidence Driver (Skyflame) \[Assurance\]](https://osu.ppy.sh/beatmapsets/1597778#osu/3263082)
  - [IRON ATTACK! - INEXPERIENCE (DeviousPanda) \[EXTRA STAGE\]](https://osu.ppy.sh/beatmapsets/1597785#osu/3263098)
  - [Mio Yamazaki - Byoushin Zenkai Girl (Deca) \[Collab Extra\]](https://osu.ppy.sh/beatmapsets/1597860#osu/3263248)
  - [Camellia - Heartless being (Mir) \[Expert\]](https://osu.ppy.sh/beatmapsets/1597801#osu/3263131)
- Hidden
  - [BUTAOTOME - Sharekoube (Moph) \[Extreme\]](https://osu.ppy.sh/beatmapsets/1597784#osu/3263097)
  - [ZUN - Primodrial Beat \~ Pristine Beat (Halfslashed) \[Extra Stage\]](https://osu.ppy.sh/beatmapsets/1597824#osu/3263174)
- HardRock
  - [Nakamura Meiko - Dispel (Yogurtt) \[Cataclysm\]](https://osu.ppy.sh/beatmapsets/1597607#osu/3262706)
  - [Lime - Ophelia (Kloyd) \[Hamlet\]](https://osu.ppy.sh/beatmapsets/1597825#osu/3263175)
- DoubleTime
  - [Ito Kanako - Koko ni Iru kara (ImpurePug) \[Insane\]](https://osu.ppy.sh/beatmapsets/1597789#osu/3263112)
  - [-45 - NyanNyatothep (Dada) \[Gothic Horror\]](https://osu.ppy.sh/beatmapsets/1597755#osu/3263028)
```
 
# Proposal

```
- NoMod
  1. [LiSA - Confidence Driver (Skyflame) \[Assurance\]](https://osu.ppy.sh/beatmapsets/1597778#osu/3263082)
  2. [IRON ATTACK! - INEXPERIENCE (DeviousPanda) \[EXTRA STAGE\]](https://osu.ppy.sh/beatmapsets/1597785#osu/3263098)
  3. [Mio Yamazaki - Byoushin Zenkai Girl (Deca) \[Collab Extra\]](https://osu.ppy.sh/beatmapsets/1597860#osu/3263248)
  4. [Camellia - Heartless being (Mir) \[Expert\]](https://osu.ppy.sh/beatmapsets/1597801#osu/3263131)
- Hidden
  1. [BUTAOTOME - Sharekoube (Moph) \[Extreme\]](https://osu.ppy.sh/beatmapsets/1597784#osu/3263097)
  2. [ZUN - Primodrial Beat \~ Pristine Beat (Halfslashed) \[Extra Stage\]](https://osu.ppy.sh/beatmapsets/1597824#osu/3263174)
- HardRock
  1. [Nakamura Meiko - Dispel (Yogurtt) \[Cataclysm\]](https://osu.ppy.sh/beatmapsets/1597607#osu/3262706)
  2. [Lime - Ophelia (Kloyd) \[Hamlet\]](https://osu.ppy.sh/beatmapsets/1597825#osu/3263175)
- DoubleTime
  1. [Ito Kanako - Koko ni Iru kara (ImpurePug) \[Insane\]](https://osu.ppy.sh/beatmapsets/1597789#osu/3263112)
  2. [-45 - NyanNyatothep (Dada) \[Gothic Horror\]](https://osu.ppy.sh/beatmapsets/1597755#osu/3263028)
```

**Comment by Walavouchey** [comment]
Are the maps in all tournament pages already listed in the correct order, meaning if you just automatically changed the lists to be numbered they would be correct?

**Comment by Bazzadwarf** [comment]
> Are the maps in all tournament pages already listed in the correct order, meaning if you just automatically changed the lists to be numbered they would be correct?

In all the pages I have done, yes. I would assume most other articles are too, but I would want to do a sanity check in case on some of the older articles.

**Comment by Bazzadwarf** [comment]
Unless any objections are raised I am going to start going through and updating the articles in batches.
