### ISSUE TITLE
Needed articles

### ISSUE THREAD

**Issue by Gamingzone123** [ppy/osu-wiki#6220]
overlaps and adds to Loctav's issues for stub addition
a lot of these could probably be disambiguation pages
need articles on:

- [x] modding queues, the current best we have is this forum post: https://osu.ppy.sh/community/forums/topics/726725
- [x] stack leniency https://github.com/ppy/osu-wiki/pull/9028
- [x] playfield (probably a short article)
- [x] hit circles (osu!taiko)
- [x] ~~dendens~~ TicClick: moved to https://github.com/ppy/osu-wiki/issues/3152 instead
- [x] profile badges https://github.com/ppy/osu-wiki/pull/7534
- [x] osu!lazer (covered by #4686)
- [x] ~~beatmap metadata (somewhat covered in https://osu.ppy.sh/wiki/en/Client/Beatmap_editor/Song_Setup )~~ TicClick: doesn't look useful (the RC covers it up to necessary points, and the song setup article has been trimmed down considerably in https://github.com/ppy/osu-wiki/pull/9884)

**Comment by Gamingzone123** [comment]
need articles for "forums", "forum topics" and "moderators"

**Comment by TicClick** [comment]
for moderators, we have `[[GMT]]`. for forums, see https://github.com/ppy/osu-wiki/issues/3150 (can ignore "posts/topics" part)
