### ISSUE TITLE
Automation/CI checks wanted

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-wiki#6233]
- [x] footnotes: https://github.com/ppy/osu-wiki/issues/6232
- [x] ~~use of redirects~~ no: https://github.com/ppy/osu-wiki/pull/6645#discussion_r777794205
- [x] broken wiki links https://github.com/ppy/osu-wiki/pull/6645
  - [x] including references to the translated subsections, and reference-style links https://github.com/ppy/osu-wiki/pull/7288
- [x] `outdated: true` and `outdated_since: ...` missing from the translations when the original articles are being updated ([via](https://discord.com/channels/188630481301012481/218677502141399041/888446144512921641); this one could be a bot instead): https://github.com/ppy/osu-wiki/pull/6428
- [x] `yamllint` on individual articles to avoid things like #6619: https://github.com/ppy/osu-wiki/pull/6629
- [ ] `outdated_since` hash validation to avoid things like #6747

**Comment by TicClick** [comment]
#3310 could be a source of ideas for the remark plugins

**Comment by cl8n** [comment]
moved to #2275
