### ISSUE TITLE
Document the new `github.dev` Web Editor

### ISSUE THREAD

**Issue by sr229** [ppy/osu-wiki#6270]
As discussed in Discord, just going to add this for documentation reasons:

This probably slipped by everyone's radars, [GitHub silently dropped a new Web-based editor](https://docs.github.com/en/codespaces/the-githubdev-web-based-editor), which deserves a spot in the wiki since we've historically covered how to do it within the GitHub UI (which results with new contributors having to do more stuff than what everyone would be doing in a few clicks with a local or cloud IDE). Documenting this would allow contributors who just wanna edit the osu-wiki within the GitHub namespace.

**Comment by TicClick** [comment]
tentatively assigning to myself, hoping to do this within next three weeks

**Comment by dumb-stuff** [comment]
if wanna translate how can I do it?

**Comment by TicClick** [comment]
> if wanna translate how can I do it?

this issue is about writing a new article. you can translate it once https://github.com/ppy/osu-wiki/pull/6437 is merged
