### ISSUE TITLE
[Discussion] Welcome Page Rewrite

### ISSUE THREAD

**Issue by sr229** [ppy/osu-wiki#662]
As we all know, according to @Ephemeralis stated in #94 
>Put plainly, the Welcome page currently isn't cutting it.
>
>It is currently far too verbose, spans across several topics which likely need their own dedicated pages and > essentially deluges the user in a wealth of information that they're probably not really ready for.

This Discussion Issue was created in response to that issue and to draft out some ideas around here, this is mostly more of a think-tank type of discussion as I want everyone to make their own renditions for Welcome and maybe we can make a unified idea out of those.

**Comment by sr229** [comment]
This is my own take

> # Welcome
> Welcome to osu!, a free rhythm game created by peppy.
> This wiki is created to give you some idea of what osu! is, how it works and what can you do to help out the team.
>### What is osu!?
> Like stated before, osu! is a rhythm game, meaning you need to click, hold (or even catch) a specific >element along with the beat of the song. If you want a brief experience on how it works, head over to >the [Tutorial](https://osu.ppy.sh/s/3756) song in the game, which would briefly give you an >introduction on how to play the game.
>
> ### Cool! But I want to make my own content
> There are tons of ways you can make content to make osu! truly yours, such as:
> - [Mapping your own song](https://osu.ppy.sh/help/wiki/Beatmapping)
> - [Making a cool skin](https://osu.ppy.sh/wiki/Skinning)
> These are just a number of examples, so head over and craft some masterpieces for us!
> ### I want to help on osu!
> We truly appreciate your kind spirit to volunteer, if you really want to help around to make osu! even > awesome, you can : 
> - [Help in osu!'s development](https://github.com/ppy/osu)
> - [Make the wiki even better for newer players](https://github.com/ppy/osu-web)
> and many more. [peppy even highlighted what can you do to help!](https://github.com/ppy/osu-wiki/blob/master/wiki/How_You_Can_Help!/en.md)
>[..]

I brainfarted at this point, forgive me

But yeah, this is one overview of what we want

**Comment by kj415j45** [comment]
i think it's ok :+1:

~~btw, you link `Make the wiki even better for newer players` to osu-web by mistake~~

**Comment by sr229** [comment]
~~heck i hecked up~~

**Comment by TPGPL** [comment]
@sr229 for sure you should link to the Index page

**Comment by sr229** [comment]
leaving this an agile TODO for @kj415j45
