### ISSUE TITLE
Two image links in a 2014 news post are broken because a file doesn't exist

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu-wiki#6647]
The short of it is that [two](https://github.com/ppy/osu-wiki/blob/master/news/2014-10-10-third-official-osu-fanart-contest-results.md?plain=1#L40) [links](https://github.com/ppy/osu-wiki/blob/master/news/2014-10-10-third-official-osu-fanart-contest-results.md?plain=1#L66) in a [2014 news post](https://osu.ppy.sh/home/news/2014-10-10-third-official-osu-fanart-contest-results) are broken.

As one may observe, the [image folder](https://github.com/ppy/osu-wiki/tree/master/wiki/shared/news/2014-10-10-third-official-osu-fanart-contest-results) for the news post contains 14 thumb-sized images and 13 full-sized images, with `full-36.jpg` missing.

**Comment by peppy** [comment]
I'll take a look into this. I believe I have these files archived somewhere deep.

**Comment by ZeroPyrozen** [comment]
I found the [original post](https://osu.ppy.sh/community/forums/topics/230225?n=64) and the submitted images.

![](https://up.ppy.sh/files/pippi-8.png "pippi-8")

![](https://up.ppy.sh/files/yuzu.png "yuzu")

**Comment by Walavouchey** [comment]
keep in mind that the `thumb-36.jpg` image combines the two and has a white background. it's best to dig up the original `full-36-jpg` or recreate it

![](https://raw.githubusercontent.com/ppy/osu-wiki/master/wiki/shared/news/2014-10-10-third-official-osu-fanart-contest-results/thumb-36.jpg)

**Comment by ZeroPyrozen** [comment]
If you want recreation version. I assumed it's dimension same as `full-25.jpg` which is 960 px x 565 px.

![](https://pyrozen.s-ul.eu/MCCbMctV)

**Comment by peppy** [comment]
Those look correct, thanks.

**Comment by Walavouchey** [comment]
I noticed the proportions were a bit off, so I've recreated it more accurately by overlaying `thumb-36.jpg` scaled to 960x565, and putting the full-sized submissions on top

https://user-images.githubusercontent.com/36758269/148118493-f35ad33a-0499-4f8f-a463-2bd9aa738c72.mp4

![full-36](https://user-images.githubusercontent.com/36758269/148118709-59ffd1b5-1d37-4a5d-9275-e446af872e5f.jpg)
