### ISSUE TITLE
Misleading locale guide in the main contribution guide

### ISSUE THREAD

**Issue by reverie-lu** [ppy/osu-wiki#669]
This is nitpicking, but in the main contribution guide [linked](https://github.com/ppy/osu-wiki) in the osu-wiki README, an example given for Japanese md files is shown as `jp.md`, when we're using `ja.md`.

![image](https://user-images.githubusercontent.com/6107544/30104109-8325c760-92a9-11e7-82b1-7772544e42e3.png)

**Comment by peppy** [comment]
the whole guide needs to be nuked; see https://github.com/ppy/osu-wiki/issues/372

**Comment by reverie-lu** [comment]
My bad. Thanks!
