### ISSUE TITLE
SO is allowed although it's not Difficulty reduction nor Difficulty increase

### ISSUE THREAD

**Issue by DeadBushSanpai** [ppy/osu-wiki#6763]
https://github.com/ppy/osu-wiki/blob/27c6afb8f71480cf76634660b7ad9e6bb7dfb4b8/wiki/Medals/en.md?plain=1#L9
[Here](https://osu.ppy.sh/ss/17470358/1fb8) is a example.
This issue may both affect to these point in the same page:
https://github.com/ppy/osu-wiki/blob/27c6afb8f71480cf76634660b7ad9e6bb7dfb4b8/wiki/Medals/en.md?plain=1#L41
https://github.com/ppy/osu-wiki/blob/27c6afb8f71480cf76634660b7ad9e6bb7dfb4b8/wiki/Medals/en.md?plain=1#L47
https://github.com/ppy/osu-wiki/blob/27c6afb8f71480cf76634660b7ad9e6bb7dfb4b8/wiki/Medals/en.md?plain=1#L53

**Comment by ZeroPyrozen** [comment]
I've started a [thread](https://discord.com/channels/639515567233171476/933941086198579200/933941090116059146) in osu! Medal Hunters community to check which [special mods](https://osu.ppy.sh/wiki/Game_modifier#special) are allowed to unlock Beatmap packs medal.
