### ISSUE TITLE
Update ASC to include clarifications about usage of italics

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu-wiki#6786]
I have made a [branch](https://github.com/Walavouchey/osu-wiki/tree/asc-clarifications) with the points I've presented in a [comment on the recent Loved news post pr](https://github.com/ppy/osu-wiki/pull/6771#issuecomment-1019001697), as well as doing some miscellaneous updates/clean-up in the asc.

In that branch, I still haven't taken into account the points raised about difficulty names. Any sort of opinion here would be appreciated. I'll leave a copy of the relevant points below:

> In collection sets like [dressurf's 7k practice charts](https://osu.ppy.sh/beatmapsets/1232389#mania/2562052), the song titles can appear in the difficulty names (`Rock It`, `Decipher.#300` and `Meikaruza` are mentioned in the [relevant description](https://github.com/ppy/osu-wiki/blob/372f1169954e44dae46364bdd99c84bc33e178ec/news/2022-01-22-project-loved-january-2022.md?plain=1#L399-L405)). Difficulty names are not italicised, but song titles usually are. Which should take precedence?
>
> Some have suggested using brackets (`[]`) to denote difficulty names in sentences (I've removed instances of this in this month's descriptions), which would help when they get long and have spaces, though that would also have to apply in the cases of [Normal] or [Hard] if we want to be consistent (and if not, the line to draw there is another discussion).

I'm making an issue instead of just opening a pr because the [asc said so](https://osu.ppy.sh/wiki/en/Article_styling_criteria)

## Summary of clarifications

- Things like `*artist - title*` are italicised
- `artist's *title*` or `*title* by artist` - only italicise the title
- `[artist - title](link)` - not italicised (already emphasised by link)
- `check out [this beatmap of *artist - title*](link)` or `[this *artist - title* beatmap](link) by [creator](link)` - italicised to prevent ambiguity (can get messy if used excessively in lists or tables)

### additional additions

- em dashes should be used instead of hyphens where applicable (was never mentioned anywhere)
- example of a blockquote
- information how to do stacked hatnotes (was never mentioned)

may also add a thing that explains that emphasis and link placement follow the same rules as logical quotations (i.e. `*This sentence is emphasised.*` and `Emphasis on *part of a sentence*.`)

**Comment by Walavouchey** [comment]
Editors may of course use what wording works best, but I believe it's best to have a guideline in place for the formatting part. The way I've done italicising when reviewing so far is intended to be most consistent with what we've already been doing, and having it written down would only make formatting style more consistent regardless of how anything is worded.

Spaces around em dashes has been style choice, that generally has only been used for news posts ([discussion in a news post pr](https://github.com/ppy/osu-wiki/pull/5382#discussion_r627885587), [remark on discord](https://discord.com/channels/188630481301012481/218677502141399041/836604322980298849)). This is for the article styling criteria though, so it would only really apply for regular articles. I'm fine with picking either style depending on some criterion (perhaps news posts vs articles as we've mainly done it, perhaps formal vs informal), but I wouldn't be so sure about picking any style randomly for a given article.

**Comment by Walavouchey** [comment]
The em dash with blockquote thing is only relevant when the person is mentioned below the quote. I'm proposing to just use em dashes instead of hyphens for consistency's sake.

```
> quote

⁠—person
```

There are of course many quoting styles, which is fine (although the asc does already mention that blockquotes are limited to quoting from "someone", i.e. a specific person, but I don't have an opinion on that)

```
osu! community rule no. 1 reads as follows:

> Each player may only have ONE account, ever. The first account you make during account registration is your one and only osu! account, from the moment of its creation and forevermore. This account is YOU. It is not anyone else - not your brother, your mother, your sister, your friend - it is YOU. Don't share your account with anyone else. You don't get to make a new one if you lose access to it. Keep it safe.
```

**Comment by cl8n** [comment]
for the italics part I don't agree about "formatting" being inherently separate from "wording", whether or not I want to italicize something may depend on the tone of the sentence/paragraph/article--- kinda beside the point though, I just feel that it adds bulk to ASC without carrying any weight in improving article quality. italics usage for songs/beatmaps/etc is already good(imo) in all but the most poorly written articles, and no style guide was needed

same for the em dash style. leaving choices to the current active editors isn't "picking any style randomly", and the only real consequence I can imagine from adding that to ASC is bloating ASC and making things appear more rigid than anyone really cares

hyphens shouldn't be used to attribute quotes but I'm not sure why that's more worthy of a mention than any other punctuation mix-up in English.

but should be noted (and u can prob just tell lol) that I think ASC is already too strict & causes pedantic discourse more often than it ends up significantly improving the quality or feel of the wiki, so I'm usually not in favor of adding more rules, esp. without a clear prompt

**Comment by Walavouchey** [comment]
> I just feel that it adds bulk to ASC without carrying any weight in improving article quality. italics usage for songs/beatmaps/etc is already good(imo) in all but the most poorly written articles, and no style guide was needed
>
> same for the em dash style. leaving choices to the current active editors isn't "picking any style randomly", and the only real consequence I can imagine from adding that to ASC is bloating ASC and making things appear more rigid than anyone really cares

The article styling criteria hasn't been followed everywhere, either due to disagreements with it or a particular article being too old. It doesn't need to be a cause for pointless discourse, rather it should be the consensus - we're literally writing it after all. If something in the asc is not something we want to follow, then those parts should simply be amended or removed.

In my mind, it's not about "being strict", but "having a standard to fall back to" when discourse happens, and having a goal of consistency to work towards. If I or any new writer finds something in a pr that seems questionable at first glance, it's way easier to reference the asc instead of looking through every article to see what kind of style people have used the most. That way, I can know what I should be paying attention to when writing or reviewing.

I would appreciate any suggestions on what aspects of the style I've outlined above need changes/additions/deletions or on how to best convey them. It's also possible that some of it is simply biased on my part and doesn't need standardisation, in which case I'll know what to not be picky about in future reviews, but please be specific on what parts apply in that case.

> for the italics part I don't agree about "formatting" being inherently separate from "wording", whether or not I want to italicize something may depend on the tone of the sentence/paragraph/article

Italicising based on tone is fine. You can usually tell when this happens in writing and I wouldn't bat an eye (and writers are free to refute my suggestion if I fail to realise something like this). This is simply about noting down one aspect of how we have commonly italicised song and beatmap references, and what I've been paying attention to when reviewing pulls thus far as a result. It's not outlined by the asc, but I haven't really received any opposition when I point this stuff out in reviews, which is why I made this issue.

> hyphens shouldn't be used to attribute quotes but I'm not sure why that's more worthy of a mention than any other punctuation mix-up in English.

If hyphens "shouldn't be used to attribute quotes", then what's wrong with adding an example to illustrate it? The reason for adding it is because I've pointed it out a during reviews and was on my mind when making the branch. More rules/guidelines on punctuation is fine with me - there are already some in asc/writing.

**Comment by TicClick** [comment]
my 2¢: while it may be beneficial to have formatting standards, this specific point doesn't sound significant. I'm ok with adding a few examples, but as clayton has already said, the asc is already too long

perhaps if we separated mandatory things (stuff will break if you don't do X / there should be only way to do X) from purely style-based rules and recommendations, life would be easier, but again, this is low priority

**Comment by Walavouchey** [comment]
[more discussion on discord](https://discord.com/channels/188630481301012481/218677502141399041/935603672396754975)
