### ISSUE TITLE
update checklist for stub addition

### ISSUE THREAD

**Issue by Gamingzone123** [ppy/osu-wiki#6788]
when the wiki maintainers have a free minute, I cant check the boxes myself, so I have gone through the pending stubs checklist on the reorganize and cross-connect the wiki project and have left comments on which stubs have been written since the checklist was last updated (the ones I could locate on the wiki at least (the search function doesn't always show all relevant articles, but that's for another issue))

https://github.com/ppy/osu-wiki/projects/3

#3149, https://github.com/ppy/osu-wiki/issues/3149#issuecomment-1018111057
#3151, https://github.com/ppy/osu-wiki/issues/3151#issuecomment-1018127374
#3152, https://github.com/ppy/osu-wiki/issues/3152#issuecomment-1018132080

**Comment by Walavouchey** [comment]
done
