### ISSUE TITLE
Rename and add disclaimers to the article styling criteria to be less intimidating for contributors

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu-wiki#6793]
Suggested [here](https://discord.com/channels/188630481301012481/218677502141399041/935608254665457673) ([whole discussion on discord](https://discord.com/channels/188630481301012481/218677502141399041/935603672396754975), related to conversation in https://github.com/ppy/osu-wiki/issues/6786)

The issue is that the article styling criteria can be a deterrent for people who want to edit or review the wiki due to being portrayed as a big long list of *criteria* that every pr should strive for.

As I've mentioned in the conversation, the asc is best used as a reference for reviewers and maintainers for the consensus of the writing and formatting styles we want to follow in the wiki. New contributors shouldn't be expected to read and learn the whole thing by heart, and it shouldn't be presented as a requirement for contribution.

The review process and ongoing clean-up tasks already serve the purpose of converging the wiki to a more consistent style, which means the burden of enforcing quality doesn't need to fall on a contributor trying to make a change. We already have a [contribution guide with a more simplified checklist](https://osu.ppy.sh/wiki/en/osu!_wiki/Contribution_guide#self-check) people can follow, and we already link to it in the pr template.

The idea here is therefore to reword references to the asc and add disclaimers to it mentioning that it's only a style reference, not a requirement.

This also means that the notion of "styling *criteria*" is part of the problem, and should be renamed. Some initial suggestions I can come up with are:

- **Article styling reference**

(that's it)

https://github.com/ppy/osu-wiki/pull/683 renamed it from "Article Style Guide" to "Article Styling Criteria", but given the arguments I've laid out, I believe another change is warranted.

**Just to be super clear**: the scope of the contents in the asc isn't the problem. It's a great reference for what it covers, preventing people from wasting time searching through articles to find out what style people have agreed upon.

**Comment by Walavouchey** [comment]
Does anyone have an opinion on whether the asc should be renamed? I realise it was a suggestion based on one comment from me, but i'm not sure what others think of it since I haven't seen any response on that point. Maybe renaming isn't as necessary, and the problem can better be fixed by restructuring the asc articles a bit, in which case this issue could potentially be closed as resolved.

**Comment by TicClick** [comment]
I personally think that your PR was enough, and renaming the asc or making other cosmetical fixes won't achieve anything

**Comment by peppy** [comment]
I honestly think it's fine as-is.

**Comment by TicClick** [comment]
then resolved it is
