### ISSUE TITLE
`Changelog` needs an update

### ISSUE THREAD

**Issue by Gamingzone123** [ppy/osu-wiki#7015]
The information on the page is mostly outdated, also needs to be moved from glossary

- [x] Move out of glossary
- [ ] Amend
- [ ] Update images
- [ ] maybe a way to view the change-log itself from the wiki page itself, like an embed or something

**Comment by TicClick** [comment]
when you say that a page is outdated, could you be more specific in what it is missing?

**Comment by Walavouchey** [comment]
i can mainly think of there being

1. no rss feed anymore
2. nothing about the new design and its new features
