### ISSUE TITLE
Adopt footnotes

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-wiki#7164]
- [x] depends on https://github.com/ppy/osu-wiki/issues/4911
- [x] depends on https://github.com/ppy/osu-wiki/issues/6232

after that, we can start dragging most of the external inline links to their dedicated sections. at the same time, a lot of things, not only links, may be -- and should be -- a reference.

usage guide: https://github.com/ppy/osu-web/pull/8125

- [ ] replace plain-link "references" with actual reference formatting

**Comment by cl8n** [comment]
can probably close? all that's left to do is use them more, but that's an always-ongoing thing

**Comment by Walavouchey** [comment]
this is also tracking replacing manual references with footnote references, mainly regarding the history articles

**Comment by cl8n** [comment]
ok, added to OP
