### ISSUE TITLE
Remove hitcircleoverlay being animatable

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-wiki#7246]
This used to be a thing, but recently got changed to no longer be possible. Animated elements should also get added to skinning/history.
There is no entry for this in the changelog, but seems to have happened around a month ago based on comments. I have tested it myself and it no longer works. Maybe @peppy wants to verify that this got removed

**Comment by peppy** [comment]
It's still possible to animate in the only place it was used (taiko skins).

No version history is required as it was not used by any skin we could find, nor was it useful due to the frame rate (which was set to a rate relative to the BPM to allow for taiko skin animations).

**Comment by RockRoller01** [comment]
So it was disabled for standard. Thanks for confirming.

There have been skins that used it, but very few as a gimmick only, since it was so limited. Besides a handful of skins nothing was lost here.
