### ISSUE TITLE
addition of a post involving the process of locking your account in the wiki

### ISSUE THREAD

**Issue by hyyhsuzy** [ppy/osu-wiki#7371]
I think having a post regarding locking your account, and how to go about it, what to expect from it, etc. would be useful to have in the osu! wiki, as not many people know about it. 

This could be helpful to players who may want to quit using unfair means, as they now have a legal, and hopefully more effective way to go about the process.

**Comment by Walavouchey** [comment]
I suppose such info would go in [`Help_centre/Account`](https://osu.ppy.sh/wiki/en/Help_centre/Account)

cc @Ephemeralis

**Comment by TicClick** [comment]
- https://osu.ppy.sh/wiki/en/Help_centre/Account#can-i-delete-my-account?
- https://osu.ppy.sh/legal/en/Privacy#your-rights-and-control p.3

**Comment by Walavouchey** [comment]
account deletion and locking aren't the same thing

**Comment by TicClick** [comment]
I was under the impression these two are the same, but apparently not. okay

**Comment by Blooshing** [comment]
Is this waiting for approval to be put into the wiki or is this approved just waiting to see what *should* go in the wiki about locking? Because I have a brief writeup (based on just what I can assume about "locking" an account, but no internal information on whether the information is correct.

**Comment by hyyhsuzy** [comment]
Waiting to see what should go into the wiki. I don't have a writeup so you could send yours, and hopefully someone could work on it based on what you wrote?
