### ISSUE TITLE
New Osu Installation Tutorial for Mac due to Lazer release

### ISSUE THREAD

**Issue by DarkIntaqt** [ppy/osu-wiki#7410]
in /wiki/Client/Installation/macOS is still the (I guess) old tutorial using wine, instead of just showing up the good working lazer client on top of the list.

**Comment by Blooshing** [comment]
Not really seeing the issue. Stable is still currently being downloaded on macOS systems so having the installation guide (with wine) is useful. 

It shows how to install osu!lazer at the bottom. Are you suggesting this should be reversed or the stable installation guide removed/edited?

**Comment by DarkIntaqt** [comment]
Yes. I thought reversed would be good since lazer is working way better than wine. But still it was just a thought and as you mentioned, the wine version is still useful too.

**Comment by TicClick** [comment]
the wiki is currently tailored to the stable build, so the guide is unlikely to change. during #7139, we may reorder it or find another way to prioritize the new release

**Comment by DarkIntaqt** [comment]
Ok, so I'll come back when the time comes :)
