### ISSUE TITLE
German wikipages are inaccessible

### ISSUE THREAD

**Issue by Endaris** [ppy/osu-wiki#748]
There is currently no way to reach german wikipages aside from this github.
URL-manipulation is obviously no longer possible with the new links and German is not an option for language selection on the page in general. All old links to german wikipages are obviously dead.

This is quite meh as the german translation has a decent amount of content covered already.

**Comment by MegaApplePi** [comment]
The way how locales are served is based on the currently selected language for the entire site; however, German isn't an option yet. If you want to try to open German articles, you can append `?locale=de` to the link.

**Comment by Endaris** [comment]
Okay, that gives me a temporary mean to link to german wiki pages, thank you for that.
If you think that this linking issue has to be solved through the osu!web-project, feel free to close this issue then.

**Comment by kj415j45** [comment]
however, the best solution is make German web translation, then wiki page will directly use German

**Comment by FreezyLemon** [comment]
This is now fixed since the web translation has been merged: ppy/osu-web#2240
