### ISSUE TITLE
The US flag is rendered differently for different players in the same list

### ISSUE THREAD

**Issue by substanc3-dev** [ppy/osu-wiki#7617]
On the "Roundtable 16 player battle royale" page (https://osu.ppy.sh/wiki/en/Tournaments/The_Roundtable/16_player_battle_royale)
it seems that the US flags render differently for different players, not sure why that would be the case.

![The issue](https://i.imgur.com/oslSeyF.png)

Inspect element suggests both renderings of the flag are the same (same "/assets/images/flags/1f1fa-1f1f8.svg" image, see no difference in the divs either, though maybe blind), so I'm not sure what the issue actually might be, and/or what could be done about it.

Browser: Firefox 102.0.1 (64-bit)
OS: Arch Linux (up-to-date), KDE Plasma 5.25.2

**Comment by Blooshing** [comment]
Renders fine for me on safari and chrome.

**Comment by substanc3-dev** [comment]
I have just tried on Windows 10, same issue on Firefox (claims 101.0.1 is up-to-date), Edge, Chrome and Opera render it fine though. Seems to be a Firefox-specific issue.

**Comment by Walavouchey** [comment]
this is an osu-web issue

**Comment by substanc3-dev** [comment]
Worth reopening in osu-web, or just considered firefox issue?

**Comment by peppy** [comment]
browser issue, report to firefox or read up on sub pixel sampling, basically a GPU issue.
