### ISSUE TITLE
Remove redirecting related to `Client/File_formats/Db_(file_format)`

### ISSUE THREAD

**Issue by libneko** [ppy/osu-wiki#7632]
Redirecting is still working, even though the article has been removed since https://github.com/ppy/osu-wiki/pull/6408.

**Comment by cl8n** [comment]
in hindsight I think this should have been replaced with a "this info is no longer on the wiki" page instead of deleted, I have to imagine it's been linked around a lot as reference

**Comment by Walavouchey** [comment]
unfortunately peppy [said no to something like that](https://github.com/ppy/osu-wiki/pull/6414#issuecomment-974803529), but at this point any interested parties should know where the documentation is located anyway
