### ISSUE TITLE
Update type argument for `[list]` section of BBCode page

### ISSUE THREAD

**Issue by yuzupon1133** [ppy/osu-wiki#7721]
*Notice: this was translated by DeepL*

I tried this: 
```
[list=a]
[*]li-1
[*]li-2
[/list]
```
But what was parsed is below: 
```
1. li-1
2. li-2
```
It shoud be parse: 
```
a. li-1
b. li-2
```
[parser code](https://github.com/ppy/osu-web/blob/3044c359ed487dac519b40062b05f09f800371e7/app/Libraries/BBCodeFromDB.php#L181) doesn't appear to have type recognition code written in it.

[wiki](https://osu.ppy.sh/wiki/en/BBCode#formatted-lists) says: 
```
Other list styles can be formatted by specifying the TYPE argument as 1, a, A, i, or I, which will format lists as numbered, lettered (lowercase), lettered (uppercase), roman numeral (lowercase), and roman numeral (uppercase) respectively.
```

Is this normal?

**Comment by nanaya** [comment]
For reference, only `[list]` (bullet) and `[list=anything]` (numbered) are supported... I think.

**Comment by yuzupon1133** [comment]
- Cannot specify list argument.
- There is an [email tag](https://github.com/ppy/osu-web/blob/3044c359ed487dac519b40062b05f09f800371e7/app/Libraries/BBCodeFromDB.php#L114).
- There is no explanation of [smiles](https://github.com/ppy/osu-web/blob/3044c359ed487dac519b40062b05f09f800371e7/app/Libraries/BBCodeFromDB.php#L236).

**Comment by yuzupon1133** [comment]
uh, should we have created the English article first?

**Comment by TicClick** [comment]
well, yes -- let's adhere to updating original articles first, everything else second
