### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-wiki#785]
<https://osu.ppy.sh/wiki/Interface> some images return a 403

**Comment by RaikireHiuduo** [comment]
and some images are old (like the osu! ranking screen;grade section, specifically the default skin used is indicative that it is out of date).

**Comment by MegaApplePi** [comment]
(just in case the person overlooks this)
![image](https://user-images.githubusercontent.com/14264992/31857058-f929ec44-b698-11e7-955d-b5de06d1ebf4.png)
probably should just remove the "object name" and just say that they just represent their game mode
