### ISSUE TITLE
Add article for all songs specifically written for osu! tournaments

### ISSUE THREAD

**Issue by iSimpFor** [ppy/osu-wiki#7921]
i think having a page just for songs written for osu!tournaments would be cool and would put compile all songs in that category into one easy accessible place 

each song listed should also contain the tournament beatmap made for the song(if uploaded)

**Comment by Ephemeralis** [comment]
Not a bad idea, though instead of just tournaments, we could write a general article for "osu! originals" and then list all of them including their first appearance in a tournament (where applicable).

**Comment by Coppertine** [comment]
I think iSimpFor is also clarifying that this could include songs that are created for Community tournaments (officially supported or not)

**Comment by Walavouchey** [comment]
are those then also called "osu! originals"? either way i think one article could definitely fit all of these

**Comment by Coppertine** [comment]
I would say no, there could be tournaments with custom songs but are not officially supported (or as we would call not Badged)

**Comment by iSimpFor** [comment]
an article for all original songs written for osu sounds fine but should be split between official tournament originals, unofficial tournament originals, and other originals

**Comment by 0x84f** [comment]
Original songs would include remixes from official competitions as well? An example would be [this](https://osu.ppy.sh/home/news/2016-08-29-osuremix-contest-1-results)

**Comment by iSimpFor** [comment]
think that would be fine as well, should only the winners be placed there or all participant songs?

**Comment by 0x84f** [comment]
I would assume only winners, because there have been a lot of people in the past (and recently) making music that they rank in the game so that would skew things a lot

**Comment by Coppertine** [comment]
I think all community votes submissions for contests would be better since there are some banger songs that didn't get a big lime light
