### ISSUE TITLE
`BeatDivisor` incorrectly listed as a `Decimal` value in `Client/File_formats/Osu_(file_format)`

### ISSUE THREAD

**Issue by yuzupon1133** [ppy/osu-wiki#7931]
https://github.com/ppy/osu-wiki/blob/master/wiki/Client/File_formats/Osu_(file_format)/en.md#Editor
`BeatDivisor` says that the value type is `Decimal`, but I have tested it and it is set to `1` for 1/1, `6` for 1/6, and `16` for 1/16, so I think the correct value type is `Integer`.
What do you think about it?

**Comment by peppy** [comment]
It should be `int`

https://github.com/ppy/osu/blob/11f38e539f6571ff1811db64883a219e2930f5c0/osu.Game/Beatmaps/BeatmapInfo.cs#L169
