### ISSUE TITLE
Wiki Completion Template

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-wiki#8]
# Wiki Completion
## Articles
- [ ] About
- [ ] Accuracy
- [ ] Achievements
   - [ ] Beatmap Packs
- [ ] Announcements
   - [ ] Archive
   - [ ] Contests
      - [ ] Monthly_Fanart_Contest
   - [ ] Showcases
   - [ ] osu!academy
   - [ ] osu!talk
- [ ] Article Style Guide
- [ ] BBCode
- [ ] BanchoBot
- [ ] Beatmap Editor
   - [ ] AiMod
   - [ ] Beat Snap Divisor
   - [ ] Compose
   - [ ] Design
   - [ ] Distance Snap
   - [ ] Kiai Time
   - [ ] Menu
   - [ ] SB Load
   - [ ] Slider
   - [ ] Song Setup
   - [ ] Timelines
   - [ ] Timing
- [ ] Beatmap Editor Guides
   - [ ] Adding Custom Hit Sounds
   - [ ] Audio Editing
   - [ ] Basic MP3 Modifications
   - [ ] Changing Title Text
   - [ ] Changing the Map's Artist or Title
   - [ ] Compressing Beatmap Files
   - [ ] Compressing Videos
   - [ ] Cropping with Complex Backgrounds
   - [ ] Cropping with Simple Backgrounds
   - [ ] Custom Hit Sound Library
   - [ ] Custom Sample Overrides
   - [ ] Getting Songs frosm Video Games
   - [ ] How to time songs
   - [ ] Making Properly Centered Spinners
   - [ ] Music Theory
   - [ ] Setting the Offset on the Correct Beat
   - [ ] Videos from Youtube
   - [ ] osu!mania Mapping Guide
- [ ] Beatmap Forum
- [ ] Beatmapping
- [ ] Beatmaps
- [ ] Beginner
- [ ] Best Of
   - [ ] 2012
- [ ] Chat Console
- [ ] Difficulties
   - [ ] osu!
      - [ ] Easy
      - [ ] Normal
      - [ ] Hard
      - [ ] Insane
      - [ ] Expert
   - [ ] osu!taiko
      - [ ] Kantan
      - [ ] Futsuu
      - [ ] Muzukashii
      - [ ] Oni
      - [ ] Ura Oni
- [ ] Do you really want to ask peppy
- [ ] FAQ
- [ ] Game Modes
   - [ ] osu!
      - [ ] v1
   - [ ] osu!catch
      - [ ] v1
   - [ ] osu!taiko
      - [ ] v1
   - [ ] osu!mania
      - [ ] v1
   - [ ] External Ports
      - [ ] opsu!
      - [ ] osu!droid
      - [ ] osu!stream
      - [ ] osu!wp
      - [ ] T-Aiko!
         - [ ] Interface
         - [ ] v1
- [ ] Game Modifiers
   - [ ] Summary
- [ ] Glossary
- [ ] Help Center
- [ ] History of osu!
   - [ ] 1
   - [ ] 2
   - [ ] 3
   - [ ] 4
   - [ ] 5
   - [ ] 6
   - [ ] The Future
   - [ ] osu!wiki
   - [ ] Release b335
- [ ] Hit Objects
- [ ] How You Can Help!
- [ ] Installation
- [ ] Interface
- [ ] Internet Relay Chat
- [ ] Legal
   - [ ] TOS
   - [ ] Copyright
- [ ] List of Guides
   - [ ] GL Support Issues
   - [ ] General tips and tricks on skill improvement
   - [ ] How to Play Mania
   - [ ] How to Run osu! on Your Mac without using Boot Camp
   - [ ] How to use the Offset Wizard
   - [ ] Recording osu!
   - [ ] Searching and Downloading Beatmaps
   - [ ] Tablet purchase
- [ ] Live streaming osu!
- [ ] Mapping Techniques
   - [ ] Basics
   - [ ] Formations
   - [ ] Jumps
   - [ ] Making Good Sliders
   - [ ] Rhythm
   - [ ] Sliders
   - [ ] Spinners
   - [ ] Unrankable
- [ ] Mascots
   - [ ] Gallery
- [ ] Modding
- [ ] Modding Guides
   - [ ] Collab Information
   - [ ] Getting Your Map Modded
   - [ ] How To Get Your Map Ranked
   - [ ] How to not Embarrass Yourself in the Modding Queues Subforum
   - [ ] How to not Embarrass Yourself in the Projects Subforum
   - [ ] Modding and Mapping
   - [ ] Starting a Beatmap Project
- [ ] Multi
- [ ] Official Songs
- [ ] Options
   - [ ] Keyboard Bindings
   - [ ] Offset Wizard
- [ ] osu! File Formats
   - [ ] Db
   - [ ] Osb
   - [ ] Osk
   - [ ] Osr
   - [ ] Osu
   - [ ] Osz
- [ ] osu! Program Files
   - [ ] User_configuration_file
- [ ] osu!store
- [ ] osu!supporter
- [ ] osu!tourney
- [ ] osu!wiki contribution guide
- [ ] People
   - [ ] Beatmap Nomination Group
   - [ ] Community Contributors
   - [ ] Global Moderation Team
   - [ ] Language Moderators
   - [ ] Osu!_Alumni
   - [ ] Quality Assurance Team
   - [ ] Support Team
   - [ ] The Team
- [ ] Performance Points
   - [ ] ppv1
- [ ] Play Styles
- [ ] Ranking Criteria
   - [ ] osu!
   - [ ] osu!catch
   - [ ] osu!mania
   - [ ] osu!taiko
- [ ] Registration
- [ ] Replay
- [ ] Reporting Bad Behaviour
   - [ ] Handling Cheating
- [ ] Rules
   - [ ] Short
- [ ] Score
   - [ ] ScoreV1
- [ ] Shortcut Key Reference 
- [ ] Skinning
   - [ ] Interface
   - [ ] Skin.ini
   - [ ] Sounds
   - [ ] Tutorial
      - [ ] Interface
      - [ ] Sounds
      - [ ] osu!
      - [ ] osu!catch
      - [ ] osu!mania
      - [ ] osu!taiko
   - [ ] osu!
   - [ ] osu!catch
   - [ ] osu!mania
   - [ ] osu!taiko
- [ ] Storyboard Scripting
   - [ ] Audio
   - [ ] Cheat Sheet
   - [ ] Commands
   - [ ] Compound Commands
   - [ ] General Rules
   - [ ] Miscellaneous
   - [ ] Objects
   - [ ] Shorthand
   - [ ] Variables
   - [ ] osu! File Toggles
- [ ] Storyboarding
- [ ] Storyboards
   - [ ] Maps
- [ ] Submission
   - [ ] Beatmap Ranking Procedure
- [ ] Tools
   - [ ] AiBat
   - [ ] SGL Tool
   - [ ] osu!MapDownloader
- [ ] Tournament Drawings
- [ ] Tournaments
   - [ ] OWC
      - [ ] 1
      - [ ] 2
      - [ ] 2013
      - [ ] 2014
      - [ ] 2015
   - [ ] CWC
      - [ ] 2014
      - [ ] 2015
      - [ ] 2016
      - [ ] 2017
   - [ ] MWC
      - [ ] 2014
      - [ ] 2015
      - [ ] 2016
         - [ ] 4K
         - [ ] 7K
   - [ ] TWC
      - [ ] 2011
      - [ ] 2014
      - [ ] 2015
      - [ ] 2016
      - [ ] 2017
   - [ ] Countries that participated in osu! tournaments
   - [ ] osu! Tag Team Multiplayer Tournament
- [ ] Twitter
- [ ] Welcome
If something is missing, write to me.

**Comment by TPGPL** [comment]
that was kinda quick

**Comment by TPGPL** [comment]
http://pastebin.com/eTk7J1Z5 this is code of this template

**Comment by TPGPL** [comment]
Template got updated

**Comment by Joehuu** [comment]
Template has since been outdated and not needed.
