### ISSUE TITLE
A translation error occurred in the chinese document about .osu (file format)

### ISSUE THREAD

**Issue by O5-7** [ppy/osu-wiki#8062]
In Osu_ (file_format)/zh.md, there is a translation error in the interpretation of x value in [HitObjects] under the mania mode。the formula of key_index should be floor(x * 键位数  / 512)

**Comment by TicClick** [comment]
@YumeMuzi is this something you would be able to fix quickly, since you know Chinese?

- https://github.com/ppy/osu-wiki/blob/0b26e3d30b47e27befdf93f171d75ec94ac3625a/wiki/Client/File_formats/Osu_(file_format)/en.md?plain=1#L303
- https://github.com/ppy/osu-wiki/blob/master/wiki/Client/File_formats/Osu_(file_format)/zh.md?plain=1#L301

**Comment by YumeMuzi** [comment]
> In Osu_ (file_format)/zh.md, there is a translation error in the interpretation of x value in [HitObjects] under the mania mode。the formula of key_index should be floor(x * 键位数 / 512)

yes, the translation is inaccurate, I'll fix it rn.

but the original text is also very confusing. for example, the `x` of LNs in osu!mania 7K are 36, 109, 182, 256, 329, 402, 475, and calculated according to this formula, the results are 0.5, 1.5, 2.5... 6.5. which conflict with their column number, 0-6. the clamp function can only handle the value `6.5` and clamping to `columnCount - 1`, or `6`. and won't affect others.

**Comment by O5-7** [comment]
> > In Osu_ (file_format)/zh.md, there is a translation error in the interpretation of x value in [HitObjects] under the mania mode。the formula of key_index should be floor(x * 键位数 / 512)
> 
> yes, the translation is inaccurate, I'll fix it rn.
> 
> but the original text is also very confusing. for example, the `x` of LNs in osu!mania 7K are 36, 109, 182, 256, 329, 402, 475, and calculated according to this formula, the results are 0.5, 1.5, 2.5... 6.5. which conflict with their column number, 0-6. the clamp function can only handle the value `6.5` and clamping to `columnCount - 1`, or `6`. and won't affect others.

clamp function? The original text is about floor(), for an input value greater than 0, the floor() function will return its integer part, which is from 0 to 6

**Comment by YumeMuzi** [comment]
> > > In Osu_ (file_format)/zh.md, there is a translation error in the interpretation of x value in [HitObjects] under the mania mode。the formula of key_index should be floor(x * 键位数 / 512)
> > 
> > 
> > yes, the translation is inaccurate, I'll fix it rn.
> > but the original text is also very confusing. for example, the `x` of LNs in osu!mania 7K are 36, 109, 182, 256, 329, 402, 475, and calculated according to this formula, the results are 0.5, 1.5, 2.5... 6.5. which conflict with their column number, 0-6. the clamp function can only handle the value `6.5` and clamping to `columnCount - 1`, or `6`. and won't affect others.
> 
> clamp function? The original text is about floor(), for an input value greater than 0, the floor() function will return its integer part, which is from 0 to 6

ok, I misunderstood the floor() function. and im going to fix the translate
