### ISSUE TITLE
Expand the .osu format page

### ISSUE THREAD

**Issue by fmang** [ppy/osu-wiki#811]
This one: https://osu.ppy.sh/help/wiki/osu!_File_Formats/Osu_(file_format)

As mentionned in https://github.com/ppy/osu/issues/1443, it's perfectible.

I'm going to work on it at https://github.com/fmang/osu-wiki/blob/formats/osu/wiki/osu!_File_Formats/Osu_(file_format)/en.md and then make a pull request hopefully next week. This issue is for the record in case someone else would like to contribute.

**Comment by osuShiro** [comment]
issued fixed in #814

**Comment by osuShiro** [comment]
pending further fixes
