### ISSUE TITLE
Add new flags to CI

### ISSUE THREAD

**Issue by Hiviexd** [ppy/osu-wiki#8135]
Currently, it's pretty easy to improperly write new flags as `::{FLAG=US}::` when in reality, it's missing spaces and should be `::{ FLAG=US }::` (happened with https://github.com/ppy/osu-wiki/pull/8134)

A CI check would do wonders in not letting this error pass to production.

**Comment by TicClick** [comment]
I'll reuse this issue to write down another thought from clayton ([via](https://discord.com/channels/188630481301012481/218677502141399041/1025134443154911234))

> [9:58 PM] clayton: all i can think of is forcing every custom span (the `:: my content here ::` thing) to be a flag since thats all we use em for
> [9:58 PM] clayton: if u fail to make the span at all though it wouldnt help
