### ISSUE TITLE
OWC#1 old Matchlinks

### ISSUE THREAD

**Issue by mugiishiro** [ppy/osu-wiki#8405]
I found theses matchlinks from the first owc#1 with archive.org and it would be cool to see them get added.
these are the only one's that got archived all the other links are gone.

matchlink of the Grand Final: https://web.archive.org/web/20110412015449/https://osu.ppy.sh/mp/494834 (NL vs TW)
matchlink of the Quarter Final: https://web.archive.org/web/20110322035734/https://osu.ppy.sh/mp/354944 (PL vs NL)
matchlink of the Round of 32: https://web.archive.org/web/20110717224653/https://osu.ppy.sh/mp/236416 (SK vs CN)

> had you tried checking archive.ph for any other links?

yes I did but archive.ph was launched a year after the owc#1
so I couldn't find anything

**Comment by WindowsMeosu** [comment]
had you tried checking archive.ph for any other links?
