### ISSUE TITLE
Add CWC and TWC 2016 prize pool figures

### ISSUE THREAD

**Issue by Teetooos** [ppy/osu-wiki#8406]
The wiki pages for the [osu!taiko World Cup 2016](https://osu.ppy.sh/wiki/en/Tournaments/TWC/2016) and the [osu!catch World Cup 2016](https://osu.ppy.sh/wiki/en/Tournaments/CWC/2016) do not mention the actual prize money figures, but only the percentages from the total prize going to each top 3 team.  This would've been fine if at the very least the total prize pool was mentioned, but obviously it's impossible to determine it like this

![prize](https://user-images.githubusercontent.com/97113773/204513194-55e33030-3095-4807-8b24-23a5cf4ab313.PNG)

I talked with peppy in an email and the exact numbers are known, it's just that they've apparently been omitted. Quote from the conversation: **"both of these tournaments were the standard 300/150/80 per player on the 1st/2nd/3rd placing teams."**

**Comment by Walavouchey** [comment]
@LeoFLT @ChillierPear
