### ISSUE TITLE
The OD Table is hard to read

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-wiki#849]
this one: <https://osu.ppy.sh/help/wiki/Beatmap_Editor/Song_Setup/img/ODTable.jpg>
Commit 0440e7a77f04c6f3b28ae2efb227dbee5a76107b (authored by myself) downscaled it to fit the width limit of 680 pixels, but now it is really hard to read (it probably would have been hard to read on the live page itself anyways).

Suggestions: use a Markdown table or simplify the image so it can fit the 680px width limit

**Comment by oopsjpeg** [comment]
Here's a revision I've made.
![odtable](https://user-images.githubusercontent.com/19850082/33197407-29b0b260-d0b3-11e7-9417-cbbc7d097e10.png)
