### ISSUE TITLE
Rewrite Interface, list of things to do

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-wiki#867]
- [ ] Update the page
- [x] Be more consistent with images (#3483) 
  - [x] Update images
  - [x] Have a single user? take the screenshots
  - [x] Make annotations consistent
  - [x] Not all screenshots need to take up the full width
- [ ] Clean up some duplicated content
  - [ ] Some information about Multi is here when it already exists on the Multi page itself (should have a link that points to Multi or vise versa instead)

**Comment by dora-0** [comment]
Is this still a valid issue? Let me see what I can do.

**Comment by TicClick** [comment]
from #2938:

> This PR contains mostly old content, so I'll close it and create a new one. Sorry to keep you waiting for a long time!

as it's been more than 6 months, I'm resetting the assignee

**Comment by The-Last-Cookie** [comment]
Is there anything else left to be done here? This issue should either be updated or closed.

**Comment by peppy** [comment]
Let's close this one.
