### ISSUE TITLE
Tools: Tools folder doesn't have a page

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-wiki#871]
add a page to the tools folder

do we still need those sub-articles?
- AiBat
- osu!MapDownloader
- SGL Tool

if not, the tools folder could be deleted instead

**Comment by sr229** [comment]
I vote to remove pages since I guess they have been superseded.

**Comment by peppy** [comment]
Really these tools should have their own local wikis on their git repositories and we should be linking to their git url if anything.

**Comment by MegaApplePi** [comment]
Should the page be more like this thread <https://osu.ppy.sh/community/forums/topics/135716> and rename the page to `Projects` or something else instead?
