### ISSUE TITLE
Request to remedy the lack of any mention of the California CCPA

### ISSUE THREAD

**Issue by irisu01** [ppy/osu-wiki#8871]
I come as a resident of California to bring up the mention of a lack of any good mention in the [osu! privacy policy](https://osu.ppy.sh/legal/en/Privacy) of any policies correlating to the [California Consumer Privacy Act (CCPA)](https://www.oag.ca.gov/privacy/ccpa), which was enacted to have a measure similar to the EU's GDPR, but are two separate things individually.

I believe having a good differentiation or a clause supporting it would be a good measure to have for those who reside in California but wish to exercise the similar privacy rights as seen in the GDPR that the CCPA grants them, such as data deletion. The act only required companies who do business in the state under three distinctive reasons to add clauses for such, but I do not believe osu! fills any of the 3 circumstances where it would be required.

The Office of the Attorney General of California has a page detailing a simplification of the clauses that the CCPA grants residents of California.
https://www.oag.ca.gov/privacy/ccpa

Feel free to close this issue if it is invalid.

**Comment by Walavouchey** [comment]
if you're talking about data deletion, retrieval and updating, that is possible for any user (not just in the EU) as outlined in https://osu.ppy.sh/legal/en/Privacy#your-rights-and-control.

**Comment by irisu01** [comment]
That was an example of the clauses the CCPA grants, and I do acknowledge that a lot of what the CCPA grants is  given in general by the osu! privacy policy, I moreso just believe an explicit mention of it would be a benefit, as I believe that is one of the priorities of notice granted by it.

**Comment by peppy** [comment]
Shouldn't be required. You can still file a request according to your local laws and we will handle it accordingly.
