### ISSUE TITLE
Update osu!dev Discord Server Verification Section

### ISSUE THREAD

**Issue by MattD0312** [ppy/osu-wiki#8951]
https://discord.com/channels/188630481301012481/188630481301012481/1082221412825182239

As per above message from the osu!dev discord server, verification is no longer required.  

https://osu.ppy.sh/wiki/en/Community/osu!dev_Discord_server

I would argue that the verification section on the above page can be changed to a section titled 'introduce yourself' where the wiki can tell users that they can introduce themselves in the introductions channel.  Alternatively the whole section can get deleted.

**Comment by 0x84f** [comment]
cant find the message but peppy said he's looking into alternatives for the verification, so might need to keep this outdated until that's implemented

**Comment by MattD0312** [comment]
![image](https://user-images.githubusercontent.com/32489206/224836700-2caf3c2e-919c-4bc3-86d0-51bcfdf02d92.png)

screenshot above is the message that i originally linked to, not sure how friendly that discord link is.

Message says 'for now' as of a week ago, guess we'll see how the experiment goes.

**Comment by peppy** [comment]
If any form of verification returns, it will be more in line with standard discord practices these days (using onboarding, automated reaction-based roles or otherwise).

The manual introduction / verification process most likely won't be returning.
