### ISSUE TITLE
No article for announcement messages

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-wiki#8996]
probably would be good to have, explain what they are, who can send them and how one can get access to the usergroup

**Comment by Hiviexd** [comment]
would be a nice article to have

> how one can get access to the usergroup

i don't think there's currently a streamlined way of getting it? afaik you'd have to dm eph/peppy explaining your use case, may be worth streamlining this by making it a support request? (unless you want to keep the usergroup closed off for some reason) @Ephemeralis thoughts
