### ISSUE TITLE
Polish Wiki Completion

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-wiki#9]
# Wiki Completion
### Getting Started
- [x] Registration
- [x] Installation
- [x] Newbie's Guide
- [ ] Game's Interface
- [x] Options
- [x] Hit Objects
- [x] Rules
- [x] Rules (simplified)
- [x] Glossary
- [ ] Shortcut Key Reference
- [x] osu! Program Files
- [x] osu! File Formats
- [x] BBCode
- [x] List of Guides
- [ ] Help Center
### osu! Game Styles
- [x] Basic explantation
- [ ] Multi-play
- [x] Standard
- [x] Taiko
- [x] Mania
- [x] Catch the Beat
- [ ] osu!stream
- [x] osu!droid
- [ ] opsu!
- [x] osu!wp
- [ ] T-Aiko
- [ ] Beats
- [ ] osu!MapDownloader
### Beatmap Editor
- [ ] Beatmap Editor
- [ ] Compose
- [ ] Design
- [ ] Timing
- [ ] Song Setup
- [x] Storyboard Scripting
- [x] Beatmapping
- [ ] Beat Snap Divisor
- [ ] Distance Snap
- [ ] Custom Sample Overrides
- [x] Kiai Time
- [ ] Mapping Techniques
- [ ] Skinning
- [ ] Skin.ini
- [ ] Storyboarding
- [ ] Difficulty appropriate gameplay elements
### Online Editing and Ranking
- [x] Beatmap Forum
- [ ] Submission
- [ ] Beatmap Approval
- [ ] How to Get Your Map Ranked
- [x] Modding
- [ ] Getting Your Map Modded
- [ ] Kudosu
- [ ] Star Priority
- [ ] Music Theory
- [ ] Audio Editing
- [ ] Ranking Criteria
- [ ] Ranking Criteria: Standard
- [ ] Ranking Criteria: Catch The Beat
- [ ] Ranking Criteria: Taiko
- [ ] Ranking Criteria: Mania
  ### World of osu!
- [x] Announcements Archive
- [ ] Beatmaps
- [ ] Game Modifiers
- [x] Achievements
- [ ] Performance Points
- [x] Play Styles
- [ ] Score
- [ ] Accuracy
- [ ] Chat Console
- [x] BanchoBot
- [x] Mascots
- [ ] Livestreaming osu!
- [ ] osu!tourney
- [x] Internet Relay Chat
- [x] Tournaments
- [x] Showcases
- [x] Contests
- [x] osu!academy
- [x] osu!talk
- [ ] osu!supporter
- [x] osu!store
### People
- [x] The Team
- [x] Administrators/Global Moderation Team
- [x] Quality Assurance Team
- [x] Beatmap Nomination Group
- [x] Language Moderators
- [x] osu! Alumni
- [x] Support Team 
- [x] Community Contributors
### Guides
- [ ] How to Run osu! on Your Mac without using Boot Camp
- [ ] GL Support Issues
- [ ] How to not Embarrass Yourself in the Modding Queues Subforum
- [ ] How to not Embarrass Yourself in the Projects Subforum
- [ ] Changing Title Text
- [ ] Starting a Beatmap Project
- [ ] Setting the Offset on the Correct Beat
- [ ] Collab Information
- [ ] Changing the Map's Artist or Title
- [ ] Making nice recording for Youtube
- [ ] Videos from YouTube
- [ ] Compressing Videos
- [ ] Getting songs from Video Games
- [ ] Basic MP3 modifications
- [ ] Reducing SB Load
- [ ] SGL Tool
- [ ] Adding custom hitsounds
- [ ] Custom Hitsound Library
- [ ] Making Properly Centered Spinners
- [ ] Cropping with Simple Backgrounds
- [ ] Cropping with Complex Backgrounds
- [ ] How to do 15° Patterns
- [ ] Making Good Sliders
- [ ] AIBat
- [ ] Fitting the Size-limit
- [ ] Mapping Taiko Difficulties
- [ ] How to time songs?
- [ ] How do beatmaps get ranked?
- [x] Handling Cheating/Foul Play
- [ ] Tips and Tricks for osu!
### Skinning
- [ ] Tutorial:
- [ ] Tutorial: Interface
- [ ] Tutorial: Sounds
- [ ] Tutorial: Standard
- [ ] Tutorial: Catch the Beat
- [ ] Tutorial: Taiko
- [ ] Tutorial: Mania
- [ ] Elements: Interface
- [ ] Elements: Sounds
- [ ] Elements: Standard
- [ ] Elements: Catch the Beat
- [ ] Elements: Taiko
- [ ] Elements: Mania
### Storyboard Scripting
- [ ] Cheat Sheet
- [ ] General Rules
- [ ] Storyboard Objects
- [ ] Commands
- [ ] Compound Commands
- [ ] Miscellaneous
- [ ] Command Shorthand
- [ ] Storyboard Audio
- [ ] Storyboard Variables
- [ ] osu File Toggles
### Mapping Techniques
- [ ] Formations
- [ ] Rhythm Techniques
- [ ] Jumping Techniques
- [ ] Unrankable Techniques
- [ ] Hit Circle Techniques
- [ ] Slider Techniques
- [ ] Spinner Techniques
- [ ] Mapping Techniques/Basics
### World Cups
- [ ] OWC 2010
- [ ] OWC 2011
- [ ] OWC 2012
- [ ] OWC 2013
- [ ] OWC 2014
- [ ] OWC 2015
- [ ] TWC 2011
- [ ] TWC 2012
- [ ] TWC 2013
- [ ] TWC 2014
- [ ] TWC 2015
- [ ] TWC 2016
- [ ] CWC 2012
- [ ] CWC 2013
- [ ] CWC 2014
- [ ] CWC 2015
- [ ] CWC 2016
- [ ] MWC 2014 (4K/7K)
- [ ] MWC 2015 (4K)
- [ ] MWC 2016 (7K)
### Making Good Sliders
- [ ] Arcs
- [ ] Waves
- [ ] Beat Blankets
- [ ] Circles
- [ ] Elbows
- [ ] Hearts
- [ ] Wiggles
- [ ] Loops
### History of osu!
- [ ] '07/'08
- [ ] '09/'10
- [ ] '11/'12
- [ ] '13/'14
- [ ] '15/'16
### osu! File Formats
- [x] .osk
- [x] .osz
- [x] .osu
- [x] .osr
- [x] .osb
- [x] .db
### Difficulties
- [x] Easy
- [x] Normal
- [ ] Hard
- [ ] Insane
- [x] Expert
- [ ] Kantan
- [ ] Futsuu
- [ ] Muzukashii
- [ ] Oni
- [ ] Ura Oni
- [ ] Cup
- [ ] Sallad
- [ ] Platter
- [ ] Rain
- [ ] Overdose
- [ ] Basic
- [ ] Novice
- [ ] Advanced
- [ ] Exhaust
- [ ] Maximum
### Osu! namespace
- [ ] About
- [ ] Copyrights
- [ ] Article Style Guide
- [x] Current events
- [ ] Autoconfirmed users
- [ ] How you can help!
### Disambiguation (article choice)
- [ ] Bancho
- [ ] Easy
- [ ] Mod
### Miscellaneous
- [ ] Code of Conduct
- [ ] T-Aiko v1.0
- [ ] Timelines
- [ ] Beatmap Editor/Menu
- [ ] AIMod
- [ ] Best of 2012
- [ ] Project: akrolsmir
- [ ] Qianese
- [ ] Report System
- [ ] Tablet purchase
- [ ] Slider
- [ ] User configuration file
- [ ] Universal Offset

**Comment by HoutarouOreki** [comment]
Mogę jakoś pomóc?

**Comment by TPGPL** [comment]
Write to me on Discord

**Comment by ticotaco72** [comment]
[x] Chat console

**Comment by mikser572** [comment]
The list is outdated
