### ISSUE TITLE
Lazer Not Launching On Older IOS Devices

### ISSUE THREAD

**Issue by Wypixla1** [ppy/osu-wiki#9142]
After Version 2023.326.1 on TestFlight, the game will no longer launch on older/un-updated devices, likely due to the fact that it automatically assigns metal even though the device cannot run it.

**Comment by Nivalyx** [comment]
I apologize in advance, but I'm afraid that you're posting your concern in the wrong place.

You might want to open the issue on [ppy/osu](https://github.com/ppy/osu) instead for this, as this repository is intended for the [osu!wiki](http://osu.ppy.sh/wiki) instead.

**Comment by Walavouchey** [comment]
as above
