### ISSUE TITLE
Article on combobreaks is incorrect about when the combobreak noise occurs

### ISSUE THREAD

**Issue by ArcskiWii** [ppy/osu-wiki#9260]
"By default, they will play a 'combobreak sound' if the player has broken a combo of 30x or higher."

https://user-images.githubusercontent.com/70870611/235334174-a80ee424-a162-4ccf-a908-d91fe3705866.mp4

Provided is a video showing that combobreaks occur when one's combo is >=21, not >=30.

**Comment by Walavouchey** [comment]
https://osu.ppy.sh/wiki/en/Gameplay/Judgement/Combobreak

can confirm that it's indeed >=21 going by stable code, and that lazer has the [same threshold](https://github.com/ppy/osu/blob/6a04708a7e9801949c6c7ac7ddf6a4d7fa0835e5/osu.Game/Screens/Play/ComboEffects.cs#L59)
