### ISSUE TITLE
Osu!lazer won't run

### ISSUE THREAD

**Issue by Brxby** [ppy/osu-wiki#9268]
I have stable installed and it works perfectly, but when I try to run lazer nothing happens.
Here are the event data and system data from the event logs (I'll attach a screenshot for you to read it better :)
- System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Version 0 
 
   Level 2 
 
   Task 100 
 
   Opcode 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2023-04-30T17:33:47.4858715Z 
 
   EventRecordID 2242387 
 
   Correlation 
 
  - Execution 

   [ ProcessID]  0 
   [ ThreadID]  0 
 
   Channel Application 
 
   Security 
 

- EventData 

   osu!.exe 
   0.0.0.0 
   63ed8286 
   EZFRD64.DLL 
   0.0.0.0 
   4693218c 
   c0000005 
   0000000000003654 
   25f4 
   01d97b89eac02bcf 
   C:\Users\Moni\AppData\Local\osulazer\app-2023.403.0\osu!.exe 
   C:\Windows\USB Vibration\7906\EZFRD64.DLL 
   6f488287-41a7-48bb-b68f-542c02e46203

![Screenshot 2023-04-30 204648](https://user-images.githubusercontent.com/120403978/235368213-fa0bf659-aaa2-4d8b-bb4a-149e438d051d.png)

![Screenshot 2023-04-30 204604](https://user-images.githubusercontent.com/120403978/235368175-851d61e1-95ca-4ce2-b041-55dbe0738761.png)

**Comment by Walavouchey** [comment]
post in https://github.com/ppy/osu/discussions instead
