### ISSUE TITLE
`index/Bot Account` Unforced minimum criterion

### ISSUE THREAD

**Issue by JustRoxy** [ppy/osu-wiki#9294]
According to the current wiki one of the criteria is:
* The bot is fully open-source and has complete public documentation

At the time it does not seem to be enforced according to these chat bots, which have no associated fully open-source projects:
* [Maid Bot](https://osu.ppy.sh/users/16173747)
* [Elitebotix](https://osu.ppy.sh/users/31050083)

**Comment by TicClick** [comment]
I think you should direct this question to support@ppy.sh

**Comment by Walavouchey** [comment]
as above
