### ISSUE TITLE
Establish the "Welcome" page as a "portal" to other articles on the wiki with a *brief* overview of what osu! is about

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-wiki#94]
Put plainly, the Welcome page currently isn't cutting it.

It is currently far too verbose, spans across several topics which likely need their own dedicated pages and essentially deluges the user in a wealth of information that they're probably not really ready for.

A good Welcome page should do the following:

- [ ] Provide a clear, concise summary (<250 chars) of what the game is, what is available in the game (gamemodes, etc) as a starting point
- [ ] Branch into links to pages for common points of interest, such as individual gamemodes and "Getting Started" style pages for each one
- [ ] A section dedicated to the beatmapping/modding process, with links to pages describing the major details of the system and how people can get involved
- [ ] A section dedicated to "Current Events", from running official tournaments to major events
- [ ] A contributor section dedicated to linking to this repository and introducing users to how they might contribute (it is a wiki, after all)
- [ ] It also needs to not look shit.

Clear, concise and relatively neutral English is important here. I'll make a few passes of this myself to provide an example as a working base.

We should start here and work outwards. The Welcome page is the first point of entry for people looking to find information, so we need to make it as easy as possible for them to find that information.

**Comment by iamanai** [comment]
How's this for a concise summary?

"osu! is a free-to-win competitive rhythm game. It includes four gamemodes: osu!standard, osu!taiko, osu!catch, and osu!mania. Each player's progress is tracked and ranked on a global scale against all other osu! players."

**Comment by sr229** [comment]
#177 serves as a rough draft for this issue.

**Comment by kj415j45** [comment]
Welcome page is rewrting by our group, ref: osu-translate-zh/osu-wiki#16 (en) osu-translate-zh/osu-wiki#17 (zh)

trying to finished it in 1 month

btw, we need reviews on `#16`

**Comment by Deardrops** [comment]
@Ephemeralis It's not a good idea that adding **Current Event** to `welcome` page.
As the osu! website has the specific page index and introduce these content. We don't need to leave them in `welcome` page. In the meanwhile, It's a *double loading* that updating them in `welcome` page.
