### ISSUE TITLE
osu! Projects Compilation - All osu! projects in one post

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-wiki#966]
part of #962 and related to #871 

---

List copied from <https://osu.ppy.sh/community/forums/topics/135716>. A new folder called `/wiki/Projects` will replace `/wiki/Tools` and `/wiki/Game_Modes/External_Ports`. Each project will be sorted if they appear to be "active" and listed alphabetically without respect of platform.

The format for each project will look like this:

```
## Active (or the other heading)

- name - [forum](link) - [GitHub](link) - [Website](link)
```

Unless there are objections to any of the above, I will be working on it like so

---

## PC

- [ ] [\[Windows 8\] Desktop composition disabler](https://osu.ppy.sh/community/forums/topics/177218)
  - **Pending PR #967**
- [ ] [Approach Rate Calculator](https://osu.ppy.sh/community/forums/topics/225398)
  - **Pending PR #967**
- [ ] [AIBat](https://osu.ppy.sh/community/forums/topics/55305)
  - **Pending PR #967**
- [ ] [Auto-downloader for Bloodcat (osu! beatmaps mirror)](https://osu.ppy.sh/community/forums/topics/166347)
  - **Pending PR #967**
- [ ] [Bulk Beatmap downloader](https://osu.ppy.sh/community/forums/topics/221482)
  - **Pending PR #967**
- [ ] [ClickMeter](https://osu.ppy.sh/community/forums/topics/117038)
  - **Pending PR #967**
- [ ] [Cursor Tracing Program (osu!trace)](https://osu.ppy.sh/community/forums/topics/303844)
  - **Pending PR #967**
- [ ] [Hitsounds copier](https://osu.ppy.sh/community/forums/topics/131540)
  - **Pending PR #967**
- [ ] [MyLittleOsu (Beatmap Download Manager)](https://osu.ppy.sh/community/forums/topics/199196)
  - **Pending PR #967**
- [ ] [o!verlay - Transparent-like menu bg creator!](https://osu.ppy.sh/community/forums/topics/216611)
  - **Pending PR #967**
- [ ] [o2jam to osu!mania converter](https://osu.ppy.sh/community/forums/topics/121149)
  - **Pending PR #967**
- [ ] [opsu! - an open-source osu! client (UNOFFICIAL)](https://osu.ppy.sh/community/forums/topics/221726)
  - **Pending PR #967**
- [ ] [OSU Beatmap downloader](https://osu.ppy.sh/community/forums/topics/134646) **No official support**
  - **Pending PR #967**
- [ ] [osu! (OS X)](https://osu.ppy.sh/community/forums/topics/56460)
  - **Pending PR #967**
- [ ] [osu! API library](https://osu.ppy.sh/community/forums/topics/141331)
  - **Pending PR #967**
- [ ] [osu! AR11Maker](https://osu.ppy.sh/community/forums/topics/218783)
  - **Pending PR #967**
- [ ] [osu! Beatmap API](https://osu.ppy.sh/community/forums/topics/218783)
  - **Pending PR #967**
- [ ] [osu! Beatmap BPM Changer](https://osu.ppy.sh/community/forums/topics/218783)
  - **Pending PR #967**
- [ ] [osu! Beatmap Modifier (sliders, ar, cs, od)](https://osu.ppy.sh/community/forums/topics/178878)
  - **Pending PR #967**
- [ ] [osu! changelog & search (Rainmeter)](https://osu.ppy.sh/community/forums/topics/102068)
  - **Pending PR #967**
- [ ] [osu! Input Delay Remover](https://osu.ppy.sh/community/forums/topics/218783)
  - **Pending PR #967**
- [ ] [osu! last.fm scrobbler](https://osu.ppy.sh/community/forums/topics/68899)
  - **Pending PR #967**
- [ ] [osu! MIE (editing multiple .ini files)](https://osu.ppy.sh/community/forums/topics/161122)
  - **Pending PR #967**
- [ ] [osu! mouse simulator for Leap](https://osu.ppy.sh/community/forums/topics/139360)
  - **Pending PR #967**
- [ ] [osu! Music Player](https://osu.ppy.sh/community/forums/topics/257881)
  - **Pending PR #967**
- [ ] [osu! Public Release (2007-09)](https://osu.ppy.sh/community/forums/topics/130144)
  - **Pending PR #967**
- [ ] [osu! Replay Analyzer (preview)](https://osu.ppy.sh/community/forums/topics/218783)
  - **Pending PR #967**
- [ ] [osu! Replay API](https://osu.ppy.sh/community/forums/topics/218783)
  - **Pending PR #967**
- [ ] [osu! Skin Manager](https://osu.ppy.sh/community/forums/topics/231747)
  - **Pending PR #967**
- [ ] [osu! Stats Watcher](https://osu.ppy.sh/community/forums/topics/269483)
  - **Pending PR #967**
- [ ] [osu! Trainer - find maps near your skill](https://osu.ppy.sh/community/forums/topics/209560)
  - **Pending PR #967**
- [ ] [osu!AR10](https://osu.ppy.sh/community/forums/topics/245309)
  - **Pending PR #967**
- [ ] [osu!calm - enjoy a more silent startup!](https://osu.ppy.sh/community/forums/topics/193086)
  - **Pending PR #967**
- [ ] [osu!Collections](https://osu.ppy.sh/community/forums/topics/131103) **No official support**
  - **Pending PR #967**
- [ ] [osu!DND (for Skype) v2 \[22/07/14\]](https://osu.ppy.sh/community/forums/topics/227784)
  - **Pending PR #967**
- [ ] [osu!HitCounter - Count your clicks](https://osu.ppy.sh/community/forums/topics/260456)
  - **Pending PR #967**
- [ ] [osu!Post - Live osu! status for your signatures](https://osu.ppy.sh/community/forums/topics/164486) **Beta**
  - **Pending PR #967**
- [ ] [osu!Profile](https://osu.ppy.sh/community/forums/topics/252160)
  - **Pending PR #967**
- [ ] [osu!rc - osu! irc client (in alpha test)](https://osu.ppy.sh/community/forums/topics/265602)
  - **Pending PR #967**
- [ ] [osu!Skype](https://osu.ppy.sh/community/forums/topics/260145)
  - **Pending PR #967**
- [ ] [osu!Sync | Share your beatmaps](https://osu.ppy.sh/community/forums/topics/270446)
  - **Pending PR #967**
- [ ] [osu!Tapspeed-Meter](https://osu.ppy.sh/community/forums/topics/247716)
  - **Pending PR #967**
- [ ] [osu!tt - count your time spent in osu!](https://osu.ppy.sh/community/forums/topics/302790)
  - **Pending PR #967**
- [ ] [Osu!UserInfo](https://osu.ppy.sh/community/forums/topics/210220)
  - **Pending PR #967**
- [ ] [osu!vd (osu! Video Deleter)](https://osu.ppy.sh/community/forums/topics/210509)
  - **Pending PR #967**
- [ ] [osu!widget](https://osu.ppy.sh/community/forums/topics/250902)
  - **Pending PR #967**
- [ ] [Q! me up! -An osu! Matchmaking Client](https://osu.ppy.sh/community/forums/topics/165834)
  - **Pending PR #967**
- [ ] [SGL Tool - Generate Storyboards](https://osu.ppy.sh/community/forums/topics/118733)
  - **Pending PR #967**
- [ ] [Skype tool for osu!](https://osu.ppy.sh/community/forums/topics/232479)
  - **Pending PR #967**
- [ ] [SpinnyProgram - Test your spinning speed!](https://osu.ppy.sh/community/forums/topics/140878)
  - **Pending PR #967**
- [ ] [Stream speed tester](https://osu.ppy.sh/community/forums/topics/35610)
  - **Pending PR #967**
- [ ] [Synaptic Absolution](https://osu.ppy.sh/community/forums/topics/515)
  - **Pending PR #967**

### Work in progress

- [ ] [Osu Skin Creator](https://osu.ppy.sh/community/forums/topics/116424) **Work in progress**
  - **Pending PR #967**
- [ ] [Osu!Desktop Tools](https://osu.ppy.sh/community/forums/topics/236646)
  - **Pending PR #967**

## Web

- [ ] [\[osu!\] - \[web\] extended pp listing](https://osu.ppy.sh/community/forums/topics/253951)
  - **Pending PR #967**
- [ ] [osu stats](https://osu.ppy.sh/community/forums/topics/51911)
  - **Pending PR #967**
- [ ] [osu! Beatmap Pack Mirror](https://osu.ppy.sh/community/forums/topics/57381)
  - **Pending PR #967**
- [ ] [osu! Community Localisation Project](https://osu.ppy.sh/community/forums/topics/104342)
  - **Pending PR #967**
- [ ] [osu! level calculator](https://osu.ppy.sh/community/forums/topics/199230)
  - **Pending PR #967**
- [ ] [osu! Ranked Beatmap Mirror](https://osu.ppy.sh/community/forums/topics/137156)
  - **Pending PR #967**
- [ ] [osu! signature thread](https://osu.ppy.sh/community/forums/topics/245394)
  - **Pending PR #967**
- [ ] [osu! Skins Database](https://osu.ppy.sh/community/forums/topics/137046)
  - **Pending PR #967**
- [ ] [osu!Bancho stats and logs!](https://osu.ppy.sh/community/forums/topics/111417)
  - **Pending PR #967**
- [ ] [osu!grab v.2](https://osu.ppy.sh/community/forums/topics/259116)
  - **Pending PR #967**
- [ ] [osu!record - automatic osu! replay .OSR to Youtube service](https://osu.ppy.sh/community/forums/topics/108092)
  - **Pending PR #967**
- [ ] [osu!station - The beatmap radio station](https://osu.ppy.sh/community/forums/topics/236417)
  - **Pending PR #967**
- [ ] [osu!time](https://osu.ppy.sh/community/forums/topics/219948)
  - **Pending PR #967**
- [ ] [osu!track User Stats Tracker](https://osu.ppy.sh/community/forums/topics/212151)
  - **Pending PR #967**
- [ ] [osu!userbar](https://osu.ppy.sh/community/forums/topics/136268)
  - **Pending PR #967**
- [ ] [osu!wiki project](https://osu.ppy.sh/community/forums/topics/68479)
  - **Pending PR #967**
- [ ] [osudl project - find and download beatmaps!](https://osu.ppy.sh/community/forums/topics/263650)
  - **Pending PR #967**
- [ ] [osuReImg (WIP) - Generate signature images from your replays](https://osu.ppy.sh/community/forums/topics/304209)
  - **Pending PR #967**
- [ ] [pp graphics](https://osu.ppy.sh/community/forums/topics/270866)
  - **Pending PR #967**

### Work in progress

- [ ] [osu! uebu](https://osu.ppy.sh/community/forums/topics/159414) **Work in progress**
  - **Pending PR #967**

## Android

- [ ] [AR/OD calculator](https://osu.ppy.sh/community/forums/topics/227510)
  - **Pending PR #967**
- [ ] [opsu! - an open-source osu! client (UNOFFICIAL)](https://osu.ppy.sh/community/forums/topics/221726)
  - **Pending PR #967**
- [ ] [osu!droid](https://osu.ppy.sh/community/forums/topics/62680) **buggy as hell**
  - **Pending PR #967**
- [ ] [osu!Rank](https://osu.ppy.sh/community/forums/topics/133966)
  - **Pending PR #967**
- [ ] [T-Aiko!](https://osu.ppy.sh/community/forums/topics/58640)
  - **Pending PR #967**

## BlackBerry

- [ ] [Osu!BB](https://osu.ppy.sh/community/forums/topics/130589)
  - **Pending PR #967**

## iPhone

- [ ] [osu!stream](https://osustream.com) (External link)
  - **Pending PR #967**

## Windows Phone

- [ ] [osu! WP](https://osu.ppy.sh/community/forums/topics/121936)
  - **Pending PR #967**

## AiMod

- [ ] [Jump detector](https://osu.ppy.sh/community/forums/topics/161352)
  - **Pending PR #967**
- [ ] [osu!tp's difficulty calculator](https://osu.ppy.sh/community/forums/topics/164057)
  - **Pending PR #967**

## Streaming

- [ ] [\[ORB\] osu!RequestBot](https://osu.ppy.sh/community/forums/topics/175723)
  - **Pending PR #967**
- [ ] [osu!StreamCompanion](https://osu.ppy.sh/community/forums/topics/209616)
  - **Pending PR #967**

## Random

- [ ] [Lua Storyboarding System](https://osu.ppy.sh/community/forums/topics/103321)
  - **Pending PR #967**
- [ ] [Osu Music Library](https://osu.ppy.sh/community/forums/topics/267236)
  - **Pending PR #967**
- [ ] [osu! Windows 60 fps animated cursors](https://osu.ppy.sh/community/forums/topics/86671)
  - **Pending PR #967**
- [ ] [Osu!track Ingame IRC-based Stats Updater/Viewer Bot](https://osu.ppy.sh/community/forums/topics/233167)
  - **Pending PR #967**

**Comment by Deardrops** [comment]
How about create a repo on github, called `awesome-osu` ?
these project you listed above will be update frequently, I personly think it it not proper to hold them in `osu!wiki`.
If create a `awesome-osu` page, it could include more contents like most useful urls, short brief of these items, etc. more importantly, easy for every to contributed to this independent page/repo .

**Comment by MegaApplePi** [comment]
@Deardrops I'm don't think that we should have another repo just to hold a list of (possibly dead) projects. I see why someone would do that, but the dev of the project must be the one responsible for their project's information/wiki (so it wouldn't make sense for their project information to be in another repo rather than theirs). However, most of the projects listed above appears to be abandoned years ago (which makes me wonder if the foundation of using that compilation list is shaky.)

The main thing that I was wanting to do (but forgot at the time) is link to the forum and/or repository and no more. I'll restart my progress and instead include most of the listed projects for archival purposes instead.
