### ISSUE TITLE
Include Community Choice (formerly Best of) in the Contests article

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-wiki#982]
(Note: the description of this issue was modified to match up with the most recent comments)

Best of and Community Choice articles should be removed. Replacing it will be links in the Contest page.

**Comment by sr229** [comment]
Auto-assigning to self.

**Comment by Joehuu** [comment]
Is anyone doing this? I'll do it.

**Comment by Joehuu** [comment]
I'm wondering if these kinds of articles are necessary. It's just listing beatmaps from the news article. We also have the contests page.

**Comment by cl8n** [comment]
i don't think the actual page is needed for these, but they should be indexed under contests probably?

**Comment by MegaApplePi** [comment]
Alright, I'll look into doing that.
